#!/usr/bin/env bash
# Generate the Go package reference for the Hugo site from GoDocs.
#
# Parity with the live MkDocs pipeline (.github/workflows/docs.yml), which runs
# gomarkdoc over a fixed package list into docs/go/{{.Dir}}.md. Here the same
# package set is rendered, then flattened + front-mattered for Hugo:
#   * gomarkdoc's `{{.Dir}}.md` template nests files (internal/domain.md), which
#     would create empty "internal"/"pkg" section nodes with no _index.md in the
#     Docsy sidebar. We render to a temp dir, then flatten to a single level
#     (internal-domain.md) with the import path as the title, so the reference
#     is one flat, ordered list under /reference/go/.
#   * a front-matter block (title / linkTitle / weight) is prepended; the leading
#     "<!-- Code generated -->" comment and the "# <pkg>" H1 are stripped (Docsy
#     renders the front-matter title as the page <h1>).
#
# All other links gomarkdoc emits are absolute GitHub blob URLs (source links)
# and in-page anchors — nothing to rewrite.
#
# Idempotent: reruns overwrite the generated *.md and never touch _index.md.
# The generated tree IS committed (parallel-track preview convenience); CI
# reruns this before `hugo` so the pages can never drift from source.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT_DIR="${REPO_ROOT}/website/content/reference/go"

# The exported package set — MUST match docs.yml so the two references agree.
PKGS=(
  ./internal/domain ./internal/scheduler ./internal/executor ./internal/dispatch
  ./internal/agent ./internal/agentrpc ./internal/storage ./internal/auth
  ./internal/config ./internal/cli ./internal/api ./pkg/client
)

cd "${REPO_ROOT}"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

echo "gen-go: running gomarkdoc over ${#PKGS[@]} packages"
go run github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest \
  --output "${TMP_DIR}/{{.Dir}}.md" \
  --repository.url https://github.com/neochaotic/leoflow \
  --repository.default-branch main \
  "${PKGS[@]}"

echo "gen-go: flattening + post-processing into ${OUT_DIR}"
# Pass the ordered package list as argv so weights follow the docs.yml order.
python3 - "${TMP_DIR}" "${OUT_DIR}" "${PKGS[@]}" <<'PY'
import os, re, sys

tmp_dir, out_dir = sys.argv[1], sys.argv[2]
order = [p.strip()[2:] if p.strip().startswith("./") else p.strip()
         for p in sys.argv[3:] if p.strip()]

# Clear previously generated flat pages (keep the hand-written _index.md).
for f in os.listdir(out_dir):
    if f.endswith(".md") and f != "_index.md":
        os.remove(os.path.join(out_dir, f))

for weight, pkg in enumerate(order, start=1):
    src = os.path.join(tmp_dir, *pkg.split("/")) + ".md"
    if not os.path.exists(src):
        raise SystemExit(f"gen-go: expected gomarkdoc output missing: {src}")
    with open(src, encoding="utf-8") as fh:
        body = fh.read()

    # Drop the "<!-- Code generated by gomarkdoc. DO NOT EDIT -->" banner and
    # the leading "# <pkg>" H1 (front-matter title becomes the <h1>). \s* soaks
    # up the blank line gomarkdoc puts between the banner and the H1.
    body = re.sub(r"^<!-- Code generated.*?-->\n", "", body, count=1)
    body = re.sub(r"^\s*# .*\n", "", body, count=1)
    body = body.lstrip("\n")

    flat = pkg.replace("/", "-") + ".md"
    fm = (
        "---\n"
        f"title: \"{pkg}\"\n"
        f"linkTitle: \"{pkg}\"\n"
        f"weight: {weight}\n"
        "---\n\n"
    )
    with open(os.path.join(out_dir, flat), "w", encoding="utf-8") as fh:
        fh.write(fm + body)

print(f"gen-go: wrote {len(order)} package page(s)")
PY

echo "gen-go: done"
