// proto/agent.proto
// Communication protocol between the Leoflow Control Plane and the worker Agent.
// The Agent runs as PID 1 inside every task pod and connects back to the Control Plane on startup.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARN        LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_WARN",
		4: "LOG_LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_WARN":        3,
		"LOG_LEVEL_ERROR":       4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0
	TaskState_TASK_STATE_RUNNING     TaskState = 1
	TaskState_TASK_STATE_SUCCESS     TaskState = 2
	TaskState_TASK_STATE_FAILED      TaskState = 3
	TaskState_TASK_STATE_SKIPPED     TaskState = 4
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		1: "TASK_STATE_RUNNING",
		2: "TASK_STATE_SUCCESS",
		3: "TASK_STATE_FAILED",
		4: "TASK_STATE_SKIPPED",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED": 0,
		"TASK_STATE_RUNNING":     1,
		"TASK_STATE_SUCCESS":     2,
		"TASK_STATE_FAILED":      3,
		"TASK_STATE_SKIPPED":     4,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[1].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[1]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

// GetVariablesRequest is empty; the calling task instance is identified by its
// agent token in metadata (the tenant is derived from it).
type GetVariablesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVariablesRequest) Reset() {
	*x = GetVariablesRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVariablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariablesRequest) ProtoMessage() {}

func (x *GetVariablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariablesRequest.ProtoReflect.Descriptor instead.
func (*GetVariablesRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type GetVariablesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key -> value, exported by the agent as AIRFLOW_VAR_<KEY>.
	Variables     map[string]string `protobuf:"bytes,1,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVariablesResponse) Reset() {
	*x = GetVariablesResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVariablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariablesResponse) ProtoMessage() {}

func (x *GetVariablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariablesResponse.ProtoReflect.Descriptor instead.
func (*GetVariablesResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *GetVariablesResponse) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

type GetConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionsRequest) Reset() {
	*x = GetConnectionsRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionsRequest) ProtoMessage() {}

func (x *GetConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionsRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

type GetConnectionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// conn_id -> Airflow connection URI, exported as AIRFLOW_CONN_<CONN_ID>.
	ConnectionUris map[string]string `protobuf:"bytes,1,rep,name=connection_uris,json=connectionUris,proto3" json:"connection_uris,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConnectionsResponse) Reset() {
	*x = GetConnectionsResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionsResponse) ProtoMessage() {}

func (x *GetConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionsResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *GetConnectionsResponse) GetConnectionUris() map[string]string {
	if x != nil {
		return x.ConnectionUris
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion  string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Environment   map[string]string      `protobuf:"bytes,3,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // selected env vars for diagnostics
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned correlation token for subsequent calls.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Server clock for skew detection.
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

type GetTaskSpecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskSpecRequest) Reset() {
	*x = GetTaskSpecRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskSpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskSpecRequest) ProtoMessage() {}

func (x *GetTaskSpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskSpecRequest.ProtoReflect.Descriptor instead.
func (*GetTaskSpecRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

type TaskSpec struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	TenantId                string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DagId                   string                 `protobuf:"bytes,2,opt,name=dag_id,json=dagId,proto3" json:"dag_id,omitempty"`
	DagVersion              string                 `protobuf:"bytes,3,opt,name=dag_version,json=dagVersion,proto3" json:"dag_version,omitempty"`
	RunId                   string                 `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TaskId                  string                 `protobuf:"bytes,5,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TryNumber               int32                  `protobuf:"varint,6,opt,name=try_number,json=tryNumber,proto3" json:"try_number,omitempty"`
	Operator                string                 `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"` // 'python', 'bash', 'http_api'
	Entrypoint              string                 `protobuf:"bytes,8,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Environment             map[string]string      `protobuf:"bytes,9,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XcomInputMapping        map[string]string      `protobuf:"bytes,10,rep,name=xcom_input_mapping,json=xcomInputMapping,proto3" json:"xcom_input_mapping,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // param_name -> upstream_task_id
	ExecutionTimeoutSeconds int32                  `protobuf:"varint,11,opt,name=execution_timeout_seconds,json=executionTimeoutSeconds,proto3" json:"execution_timeout_seconds,omitempty"`
	Extra                   *structpb.Struct       `protobuf:"bytes,12,opt,name=extra,proto3" json:"extra,omitempty"`                             // operator-specific fields
	ParamsJson              string                 `protobuf:"bytes,13,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"` // TaskFlow literal call args, JSON-encoded (#115)
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TaskSpec) Reset() {
	*x = TaskSpec{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSpec) ProtoMessage() {}

func (x *TaskSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSpec.ProtoReflect.Descriptor instead.
func (*TaskSpec) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *TaskSpec) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TaskSpec) GetDagId() string {
	if x != nil {
		return x.DagId
	}
	return ""
}

func (x *TaskSpec) GetDagVersion() string {
	if x != nil {
		return x.DagVersion
	}
	return ""
}

func (x *TaskSpec) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TaskSpec) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskSpec) GetTryNumber() int32 {
	if x != nil {
		return x.TryNumber
	}
	return 0
}

func (x *TaskSpec) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *TaskSpec) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *TaskSpec) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *TaskSpec) GetXcomInputMapping() map[string]string {
	if x != nil {
		return x.XcomInputMapping
	}
	return nil
}

func (x *TaskSpec) GetExecutionTimeoutSeconds() int32 {
	if x != nil {
		return x.ExecutionTimeoutSeconds
	}
	return 0
}

func (x *TaskSpec) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *TaskSpec) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

type FetchXComRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UpstreamTaskId string                 `protobuf:"bytes,1,opt,name=upstream_task_id,json=upstreamTaskId,proto3" json:"upstream_task_id,omitempty"`
	Key            string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"` // defaults to 'return_value'
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FetchXComRequest) Reset() {
	*x = FetchXComRequest{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchXComRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchXComRequest) ProtoMessage() {}

func (x *FetchXComRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchXComRequest.ProtoReflect.Descriptor instead.
func (*FetchXComRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *FetchXComRequest) GetUpstreamTaskId() string {
	if x != nil {
		return x.UpstreamTaskId
	}
	return ""
}

func (x *FetchXComRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type FetchXComResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`                                // JSON-encoded payload
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // 'application/json' by default
	SizeBytes     int32                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchXComResponse) Reset() {
	*x = FetchXComResponse{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchXComResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchXComResponse) ProtoMessage() {}

func (x *FetchXComResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchXComResponse.ProtoReflect.Descriptor instead.
func (*FetchXComResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *FetchXComResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FetchXComResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FetchXComResponse) GetSizeBytes() int32 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FetchXComResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PushXComRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // defaults to 'return_value'
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // JSON-encoded payload, max 256KB
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushXComRequest) Reset() {
	*x = PushXComRequest{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushXComRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushXComRequest) ProtoMessage() {}

func (x *PushXComRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushXComRequest.ProtoReflect.Descriptor instead.
func (*PushXComRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *PushXComRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PushXComRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PushXComRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type PushXComResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Accepted        bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectionReason string                 `protobuf:"bytes,2,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"` // empty if accepted
	TtlSeconds      int32                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`               // server-set TTL
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PushXComResponse) Reset() {
	*x = PushXComResponse{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushXComResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushXComResponse) ProtoMessage() {}

func (x *PushXComResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushXComResponse.ProtoReflect.Descriptor instead.
func (*PushXComResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *PushXComResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PushXComResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *PushXComResponse) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Level         LogLevel               `protobuf:"varint,2,opt,name=level,proto3,enum=leoflow.agent.v1.LogLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Stream        string                 `protobuf:"bytes,4,opt,name=stream,proto3" json:"stream,omitempty"` // 'stdout' or 'stderr'
	LineNumber    int64                  `protobuf:"varint,5,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *LogLine) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *LogLine) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogLine) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogLine) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogLine) GetLineNumber() int64 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

type LogAck struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	AcknowledgedThroughLine int64                  `protobuf:"varint,1,opt,name=acknowledged_through_line,json=acknowledgedThroughLine,proto3" json:"acknowledged_through_line,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *LogAck) Reset() {
	*x = LogAck{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogAck) ProtoMessage() {}

func (x *LogAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogAck.ProtoReflect.Descriptor instead.
func (*LogAck) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *LogAck) GetAcknowledgedThroughLine() int64 {
	if x != nil {
		return x.AcknowledgedThroughLine
	}
	return 0
}

type ReportStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         TaskState              `protobuf:"varint,1,opt,name=state,proto3,enum=leoflow.agent.v1.TaskState" json:"state,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`            // for terminal states
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // for failed state
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStateRequest) Reset() {
	*x = ReportStateRequest{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStateRequest) ProtoMessage() {}

func (x *ReportStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStateRequest.ProtoReflect.Descriptor instead.
func (*ReportStateRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ReportStateRequest) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *ReportStateRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ReportStateRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ReportStateRequest) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type ReportStateResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	// If the Control Plane wants the task to stop (cancellation), it signals here.
	ShouldTerminate bool `protobuf:"varint,2,opt,name=should_terminate,json=shouldTerminate,proto3" json:"should_terminate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportStateResponse) Reset() {
	*x = ReportStateResponse{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStateResponse) ProtoMessage() {}

func (x *ReportStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStateResponse.ProtoReflect.Descriptor instead.
func (*ReportStateResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ReportStateResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *ReportStateResponse) GetShouldTerminate() bool {
	if x != nil {
		return x.ShouldTerminate
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	CustomMetrics map[string]float64     `protobuf:"bytes,2,rep,name=custom_metrics,json=customMetrics,proto3" json:"custom_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // optional task-reported metrics
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *HeartbeatRequest) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *HeartbeatRequest) GetCustomMetrics() map[string]float64 {
	if x != nil {
		return x.CustomMetrics
	}
	return nil
}

type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ShouldTerminate bool                   `protobuf:"varint,1,opt,name=should_terminate,json=shouldTerminate,proto3" json:"should_terminate,omitempty"`
	ServerTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *HeartbeatResponse) GetShouldTerminate() bool {
	if x != nil {
		return x.ShouldTerminate
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x10leoflow.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x15\n" +
	"\x13GetVariablesRequest\"\xa9\x01\n" +
	"\x14GetVariablesResponse\x12S\n" +
	"\tvariables\x18\x01 \x03(\v25.leoflow.agent.v1.GetVariablesResponse.VariablesEntryR\tvariables\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x17\n" +
	"\x15GetConnectionsRequest\"\xc2\x01\n" +
	"\x16GetConnectionsResponse\x12e\n" +
	"\x0fconnection_uris\x18\x01 \x03(\v2<.leoflow.agent.v1.GetConnectionsResponse.ConnectionUrisEntryR\x0econnectionUris\x1aA\n" +
	"\x13ConnectionUrisEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe8\x01\n" +
	"\x0fRegisterRequest\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12T\n" +
	"\venvironment\x18\x03 \x03(\v22.leoflow.agent.v1.RegisterRequest.EnvironmentEntryR\venvironment\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"\x14\n" +
	"\x12GetTaskSpecRequest\"\xaa\x05\n" +
	"\bTaskSpec\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06dag_id\x18\x02 \x01(\tR\x05dagId\x12\x1f\n" +
	"\vdag_version\x18\x03 \x01(\tR\n" +
	"dagVersion\x12\x15\n" +
	"\x06run_id\x18\x04 \x01(\tR\x05runId\x12\x17\n" +
	"\atask_id\x18\x05 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"try_number\x18\x06 \x01(\x05R\ttryNumber\x12\x1a\n" +
	"\boperator\x18\a \x01(\tR\boperator\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\b \x01(\tR\n" +
	"entrypoint\x12M\n" +
	"\venvironment\x18\t \x03(\v2+.leoflow.agent.v1.TaskSpec.EnvironmentEntryR\venvironment\x12^\n" +
	"\x12xcom_input_mapping\x18\n" +
	" \x03(\v20.leoflow.agent.v1.TaskSpec.XcomInputMappingEntryR\x10xcomInputMapping\x12:\n" +
	"\x19execution_timeout_seconds\x18\v \x01(\x05R\x17executionTimeoutSeconds\x12-\n" +
	"\x05extra\x18\f \x01(\v2\x17.google.protobuf.StructR\x05extra\x12\x1f\n" +
	"\vparams_json\x18\r \x01(\tR\n" +
	"paramsJson\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aC\n" +
	"\x15XcomInputMappingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x10FetchXComRequest\x12(\n" +
	"\x10upstream_task_id\x18\x01 \x01(\tR\x0eupstreamTaskId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\xa6\x01\n" +
	"\x11FetchXComResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x05R\tsizeBytes\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\\\n" +
	"\x0fPushXComRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"z\n" +
	"\x10PushXComResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12)\n" +
	"\x10rejection_reason\x18\x02 \x01(\tR\x0frejectionReason\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x05R\n" +
	"ttlSeconds\"\xbe\x01\n" +
	"\aLogLine\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x120\n" +
	"\x05level\x18\x02 \x01(\x0e2\x1a.leoflow.agent.v1.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06stream\x18\x04 \x01(\tR\x06stream\x12\x1f\n" +
	"\vline_number\x18\x05 \x01(\x03R\n" +
	"lineNumber\"D\n" +
	"\x06LogAck\x12:\n" +
	"\x19acknowledged_through_line\x18\x01 \x01(\x03R\x17acknowledgedThroughLine\"\xc6\x01\n" +
	"\x12ReportStateRequest\x121\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1b.leoflow.agent.v1.TaskStateR\x05state\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"d\n" +
	"\x13ReportStateResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12)\n" +
	"\x10should_terminate\x18\x02 \x01(\bR\x0fshouldTerminate\"\xe7\x01\n" +
	"\x10HeartbeatRequest\x123\n" +
	"\asent_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12\\\n" +
	"\x0ecustom_metrics\x18\x02 \x03(\v25.leoflow.agent.v1.HeartbeatRequest.CustomMetricsEntryR\rcustomMetrics\x1a@\n" +
	"\x12CustomMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"{\n" +
	"\x11HeartbeatResponse\x12)\n" +
	"\x10should_terminate\x18\x01 \x01(\bR\x0fshouldTerminate\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime*w\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x03\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x04*\x86\x01\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_STATE_RUNNING\x10\x01\x12\x16\n" +
	"\x12TASK_STATE_SUCCESS\x10\x02\x12\x15\n" +
	"\x11TASK_STATE_FAILED\x10\x03\x12\x16\n" +
	"\x12TASK_STATE_SKIPPED\x10\x042\x98\x06\n" +
	"\fAgentService\x12Q\n" +
	"\bRegister\x12!.leoflow.agent.v1.RegisterRequest\x1a\".leoflow.agent.v1.RegisterResponse\x12O\n" +
	"\vGetTaskSpec\x12$.leoflow.agent.v1.GetTaskSpecRequest\x1a\x1a.leoflow.agent.v1.TaskSpec\x12T\n" +
	"\tFetchXCom\x12\".leoflow.agent.v1.FetchXComRequest\x1a#.leoflow.agent.v1.FetchXComResponse\x12Q\n" +
	"\bPushXCom\x12!.leoflow.agent.v1.PushXComRequest\x1a\".leoflow.agent.v1.PushXComResponse\x12E\n" +
	"\n" +
	"StreamLogs\x12\x19.leoflow.agent.v1.LogLine\x1a\x18.leoflow.agent.v1.LogAck(\x010\x01\x12Z\n" +
	"\vReportState\x12$.leoflow.agent.v1.ReportStateRequest\x1a%.leoflow.agent.v1.ReportStateResponse\x12T\n" +
	"\tHeartbeat\x12\".leoflow.agent.v1.HeartbeatRequest\x1a#.leoflow.agent.v1.HeartbeatResponse\x12]\n" +
	"\fGetVariables\x12%.leoflow.agent.v1.GetVariablesRequest\x1a&.leoflow.agent.v1.GetVariablesResponse\x12c\n" +
	"\x0eGetConnections\x12'.leoflow.agent.v1.GetConnectionsRequest\x1a(.leoflow.agent.v1.GetConnectionsResponseB6Z4github.com/neochaotic/leoflow/proto/agent/v1;agentv1b\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_agent_proto_goTypes = []any{
	(LogLevel)(0),                  // 0: leoflow.agent.v1.LogLevel
	(TaskState)(0),                 // 1: leoflow.agent.v1.TaskState
	(*GetVariablesRequest)(nil),    // 2: leoflow.agent.v1.GetVariablesRequest
	(*GetVariablesResponse)(nil),   // 3: leoflow.agent.v1.GetVariablesResponse
	(*GetConnectionsRequest)(nil),  // 4: leoflow.agent.v1.GetConnectionsRequest
	(*GetConnectionsResponse)(nil), // 5: leoflow.agent.v1.GetConnectionsResponse
	(*RegisterRequest)(nil),        // 6: leoflow.agent.v1.RegisterRequest
	(*RegisterResponse)(nil),       // 7: leoflow.agent.v1.RegisterResponse
	(*GetTaskSpecRequest)(nil),     // 8: leoflow.agent.v1.GetTaskSpecRequest
	(*TaskSpec)(nil),               // 9: leoflow.agent.v1.TaskSpec
	(*FetchXComRequest)(nil),       // 10: leoflow.agent.v1.FetchXComRequest
	(*FetchXComResponse)(nil),      // 11: leoflow.agent.v1.FetchXComResponse
	(*PushXComRequest)(nil),        // 12: leoflow.agent.v1.PushXComRequest
	(*PushXComResponse)(nil),       // 13: leoflow.agent.v1.PushXComResponse
	(*LogLine)(nil),                // 14: leoflow.agent.v1.LogLine
	(*LogAck)(nil),                 // 15: leoflow.agent.v1.LogAck
	(*ReportStateRequest)(nil),     // 16: leoflow.agent.v1.ReportStateRequest
	(*ReportStateResponse)(nil),    // 17: leoflow.agent.v1.ReportStateResponse
	(*HeartbeatRequest)(nil),       // 18: leoflow.agent.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 19: leoflow.agent.v1.HeartbeatResponse
	nil,                            // 20: leoflow.agent.v1.GetVariablesResponse.VariablesEntry
	nil,                            // 21: leoflow.agent.v1.GetConnectionsResponse.ConnectionUrisEntry
	nil,                            // 22: leoflow.agent.v1.RegisterRequest.EnvironmentEntry
	nil,                            // 23: leoflow.agent.v1.TaskSpec.EnvironmentEntry
	nil,                            // 24: leoflow.agent.v1.TaskSpec.XcomInputMappingEntry
	nil,                            // 25: leoflow.agent.v1.HeartbeatRequest.CustomMetricsEntry
	(*timestamppb.Timestamp)(nil),  // 26: google.protobuf.Timestamp
	(*structpb.Struct)(nil),        // 27: google.protobuf.Struct
}
var file_agent_proto_depIdxs = []int32{
	20, // 0: leoflow.agent.v1.GetVariablesResponse.variables:type_name -> leoflow.agent.v1.GetVariablesResponse.VariablesEntry
	21, // 1: leoflow.agent.v1.GetConnectionsResponse.connection_uris:type_name -> leoflow.agent.v1.GetConnectionsResponse.ConnectionUrisEntry
	22, // 2: leoflow.agent.v1.RegisterRequest.environment:type_name -> leoflow.agent.v1.RegisterRequest.EnvironmentEntry
	26, // 3: leoflow.agent.v1.RegisterResponse.server_time:type_name -> google.protobuf.Timestamp
	23, // 4: leoflow.agent.v1.TaskSpec.environment:type_name -> leoflow.agent.v1.TaskSpec.EnvironmentEntry
	24, // 5: leoflow.agent.v1.TaskSpec.xcom_input_mapping:type_name -> leoflow.agent.v1.TaskSpec.XcomInputMappingEntry
	27, // 6: leoflow.agent.v1.TaskSpec.extra:type_name -> google.protobuf.Struct
	26, // 7: leoflow.agent.v1.FetchXComResponse.created_at:type_name -> google.protobuf.Timestamp
	26, // 8: leoflow.agent.v1.LogLine.time:type_name -> google.protobuf.Timestamp
	0,  // 9: leoflow.agent.v1.LogLine.level:type_name -> leoflow.agent.v1.LogLevel
	1,  // 10: leoflow.agent.v1.ReportStateRequest.state:type_name -> leoflow.agent.v1.TaskState
	26, // 11: leoflow.agent.v1.ReportStateRequest.occurred_at:type_name -> google.protobuf.Timestamp
	26, // 12: leoflow.agent.v1.HeartbeatRequest.sent_at:type_name -> google.protobuf.Timestamp
	25, // 13: leoflow.agent.v1.HeartbeatRequest.custom_metrics:type_name -> leoflow.agent.v1.HeartbeatRequest.CustomMetricsEntry
	26, // 14: leoflow.agent.v1.HeartbeatResponse.server_time:type_name -> google.protobuf.Timestamp
	6,  // 15: leoflow.agent.v1.AgentService.Register:input_type -> leoflow.agent.v1.RegisterRequest
	8,  // 16: leoflow.agent.v1.AgentService.GetTaskSpec:input_type -> leoflow.agent.v1.GetTaskSpecRequest
	10, // 17: leoflow.agent.v1.AgentService.FetchXCom:input_type -> leoflow.agent.v1.FetchXComRequest
	12, // 18: leoflow.agent.v1.AgentService.PushXCom:input_type -> leoflow.agent.v1.PushXComRequest
	14, // 19: leoflow.agent.v1.AgentService.StreamLogs:input_type -> leoflow.agent.v1.LogLine
	16, // 20: leoflow.agent.v1.AgentService.ReportState:input_type -> leoflow.agent.v1.ReportStateRequest
	18, // 21: leoflow.agent.v1.AgentService.Heartbeat:input_type -> leoflow.agent.v1.HeartbeatRequest
	2,  // 22: leoflow.agent.v1.AgentService.GetVariables:input_type -> leoflow.agent.v1.GetVariablesRequest
	4,  // 23: leoflow.agent.v1.AgentService.GetConnections:input_type -> leoflow.agent.v1.GetConnectionsRequest
	7,  // 24: leoflow.agent.v1.AgentService.Register:output_type -> leoflow.agent.v1.RegisterResponse
	9,  // 25: leoflow.agent.v1.AgentService.GetTaskSpec:output_type -> leoflow.agent.v1.TaskSpec
	11, // 26: leoflow.agent.v1.AgentService.FetchXCom:output_type -> leoflow.agent.v1.FetchXComResponse
	13, // 27: leoflow.agent.v1.AgentService.PushXCom:output_type -> leoflow.agent.v1.PushXComResponse
	15, // 28: leoflow.agent.v1.AgentService.StreamLogs:output_type -> leoflow.agent.v1.LogAck
	17, // 29: leoflow.agent.v1.AgentService.ReportState:output_type -> leoflow.agent.v1.ReportStateResponse
	19, // 30: leoflow.agent.v1.AgentService.Heartbeat:output_type -> leoflow.agent.v1.HeartbeatResponse
	3,  // 31: leoflow.agent.v1.AgentService.GetVariables:output_type -> leoflow.agent.v1.GetVariablesResponse
	5,  // 32: leoflow.agent.v1.AgentService.GetConnections:output_type -> leoflow.agent.v1.GetConnectionsResponse
	24, // [24:33] is the sub-list for method output_type
	15, // [15:24] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
