// proto/agent.proto
// Communication protocol between the Leoflow Control Plane and the worker Agent.
// The Agent runs as PID 1 inside every task pod and connects back to the Control Plane on startup.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARN        LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_WARN",
		4: "LOG_LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_WARN":        3,
		"LOG_LEVEL_ERROR":       4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0
	TaskState_TASK_STATE_RUNNING     TaskState = 1
	TaskState_TASK_STATE_SUCCESS     TaskState = 2
	TaskState_TASK_STATE_FAILED      TaskState = 3
	TaskState_TASK_STATE_SKIPPED     TaskState = 4
	// A reschedule-mode sensor released its pod; re-dispatch at reschedule_at,
	// without consuming retry budget (ADR 0040 Phase B, #380). Distinct from
	// FAILED so the scheduler reschedules rather than failing/retrying the task.
	TaskState_TASK_STATE_UP_FOR_RESCHEDULE TaskState = 5
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		1: "TASK_STATE_RUNNING",
		2: "TASK_STATE_SUCCESS",
		3: "TASK_STATE_FAILED",
		4: "TASK_STATE_SKIPPED",
		5: "TASK_STATE_UP_FOR_RESCHEDULE",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED":       0,
		"TASK_STATE_RUNNING":           1,
		"TASK_STATE_SUCCESS":           2,
		"TASK_STATE_FAILED":            3,
		"TASK_STATE_SKIPPED":           4,
		"TASK_STATE_UP_FOR_RESCHEDULE": 5,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[1].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[1]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

// GetVariablesRequest is empty; the calling task instance is identified by its
// agent token in metadata (the tenant is derived from it).
type GetVariablesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVariablesRequest) Reset() {
	*x = GetVariablesRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVariablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariablesRequest) ProtoMessage() {}

func (x *GetVariablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariablesRequest.ProtoReflect.Descriptor instead.
func (*GetVariablesRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type GetVariablesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key -> value, exported by the agent as AIRFLOW_VAR_<KEY>.
	Variables     map[string]string `protobuf:"bytes,1,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVariablesResponse) Reset() {
	*x = GetVariablesResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVariablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariablesResponse) ProtoMessage() {}

func (x *GetVariablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariablesResponse.ProtoReflect.Descriptor instead.
func (*GetVariablesResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *GetVariablesResponse) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

type GetConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionsRequest) Reset() {
	*x = GetConnectionsRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionsRequest) ProtoMessage() {}

func (x *GetConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionsRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

type GetConnectionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// conn_id -> Airflow connection URI, exported as AIRFLOW_CONN_<CONN_ID>.
	ConnectionUris map[string]string `protobuf:"bytes,1,rep,name=connection_uris,json=connectionUris,proto3" json:"connection_uris,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConnectionsResponse) Reset() {
	*x = GetConnectionsResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionsResponse) ProtoMessage() {}

func (x *GetConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionsResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *GetConnectionsResponse) GetConnectionUris() map[string]string {
	if x != nil {
		return x.ConnectionUris
	}
	return nil
}

// ExchangeTokenRequest is empty; the agent presents its projected ServiceAccount
// token as the bootstrap bearer in the authorization metadata. The Control Plane
// derives everything it needs (the pod, hence the task instance) from that token
// via a Kubernetes TokenReview.
type ExchangeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeTokenRequest) Reset() {
	*x = ExchangeTokenRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeTokenRequest) ProtoMessage() {}

func (x *ExchangeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeTokenRequest.ProtoReflect.Descriptor instead.
func (*ExchangeTokenRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

type ExchangeTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A freshly minted, task-scoped agent JWT — the same identity scoped and
	// liveness-checked on the secret path. The agent swaps its bearer to this
	// value for every subsequent RPC. Never logged.
	AgentToken    string `protobuf:"bytes,1,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeTokenResponse) Reset() {
	*x = ExchangeTokenResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeTokenResponse) ProtoMessage() {}

func (x *ExchangeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeTokenResponse.ProtoReflect.Descriptor instead.
func (*ExchangeTokenResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ExchangeTokenResponse) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion  string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Environment   map[string]string      `protobuf:"bytes,3,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // selected env vars for diagnostics
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned correlation token for subsequent calls.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Server clock for skew detection.
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

type GetTaskSpecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskSpecRequest) Reset() {
	*x = GetTaskSpecRequest{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskSpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskSpecRequest) ProtoMessage() {}

func (x *GetTaskSpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskSpecRequest.ProtoReflect.Descriptor instead.
func (*GetTaskSpecRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

type TaskSpec struct {
	state                   protoimpl.MessageState    `protogen:"open.v1"`
	TenantId                string                    `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DagId                   string                    `protobuf:"bytes,2,opt,name=dag_id,json=dagId,proto3" json:"dag_id,omitempty"`
	DagVersion              string                    `protobuf:"bytes,3,opt,name=dag_version,json=dagVersion,proto3" json:"dag_version,omitempty"`
	RunId                   string                    `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TaskId                  string                    `protobuf:"bytes,5,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TryNumber               int32                     `protobuf:"varint,6,opt,name=try_number,json=tryNumber,proto3" json:"try_number,omitempty"`
	Operator                string                    `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"` // 'python', 'bash', 'airflow_operator'
	Entrypoint              string                    `protobuf:"bytes,8,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Environment             map[string]string         `protobuf:"bytes,9,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XcomInputMapping        map[string]*XComUpstreams `protobuf:"bytes,10,rep,name=xcom_input_mapping,json=xcomInputMapping,proto3" json:"xcom_input_mapping,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // param_name -> ordered list of upstream task_ids (1 = single, N = fan-in)
	ExecutionTimeoutSeconds int32                     `protobuf:"varint,11,opt,name=execution_timeout_seconds,json=executionTimeoutSeconds,proto3" json:"execution_timeout_seconds,omitempty"`
	Extra                   *structpb.Struct          `protobuf:"bytes,12,opt,name=extra,proto3" json:"extra,omitempty"`                                                        // operator-specific fields
	CallArgsJson            string                    `protobuf:"bytes,13,opt,name=call_args_json,json=callArgsJson,proto3" json:"call_args_json,omitempty"`                    // TaskFlow literal call args, JSON-encoded (#115). Named call_args to leave 'params' free for Airflow's DAG-run params (#148).
	OperatorClass           string                    `protobuf:"bytes,14,opt,name=operator_class,json=operatorClass,proto3" json:"operator_class,omitempty"`                   // For operator='airflow_operator': the dotted provider operator/sensor class the runtime imports and executes (ADR 0040).
	OperatorArgsJson        string                    `protobuf:"bytes,15,opt,name=operator_args_json,json=operatorArgsJson,proto3" json:"operator_args_json,omitempty"`        // For operator='airflow_operator': the operator's constructor kwargs, JSON-encoded. Delivered to the runtime as LEOFLOW_OPERATOR_ARGS.
	LogicalDate             string                    `protobuf:"bytes,16,opt,name=logical_date,json=logicalDate,proto3" json:"logical_date,omitempty"`                         // The DagRun's logical date, RFC3339. The agent derives the runtime's LEOFLOW_TS (this value) and LEOFLOW_DS (the date) so the standalone operator context has a real ds/ts (ADR 0040). Empty leaves them unset.
	DependsOn               []string                  `protobuf:"bytes,17,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`                               // The task's upstream task_ids. The agent fetches each one's return_value and delivers them as the LEOFLOW_XCOM_BY_TASK map so a captured operator's ti.xcom_pull(<id>) resolves it (chained operators, ADR 0040).
	DataIntervalStart       string                    `protobuf:"bytes,18,opt,name=data_interval_start,json=dataIntervalStart,proto3" json:"data_interval_start,omitempty"`     // The DagRun's data interval start, RFC3339. The agent stamps LEOFLOW_DATA_INTERVAL_START so the standalone operator context exposes data_interval_start (ADR 0040). Empty leaves it unset.
	DataIntervalEnd         string                    `protobuf:"bytes,19,opt,name=data_interval_end,json=dataIntervalEnd,proto3" json:"data_interval_end,omitempty"`           // The DagRun's data interval end, RFC3339. Stamped as LEOFLOW_DATA_INTERVAL_END -> context data_interval_end. Empty leaves it unset.
	ParamsJson              string                    `protobuf:"bytes,20,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`                            // The DagRun's params/conf, JSON-encoded (#148). Stamped as LEOFLOW_PARAMS so the standalone operator context exposes context['params'] / {{ params.X }}. Empty leaves params={}.
	FirstRescheduleAt       string                    `protobuf:"bytes,21,opt,name=first_reschedule_at,json=firstRescheduleAt,proto3" json:"first_reschedule_at,omitempty"`     // For a reschedule-mode sensor re-dispatched after poking not-ready (#380): the time it FIRST entered reschedule, RFC3339. Stamped as LEOFLOW_FIRST_RESCHEDULE_AT so get_first_reschedule_date returns the real value and the sensor honors its cumulative timeout. Empty on the first attempt.
	MaxTries                int32                     `protobuf:"varint,22,opt,name=max_tries,json=maxTries,proto3" json:"max_tries,omitempty"`                                 // The task's total attempt budget (retries + 1). The agent stamps LEOFLOW_MAX_TRIES so the runtime fires on_failure_callback only on the terminal attempt (try_number == max_tries), never on an intermediate retry (#424).
	OnFailureCallback       bool                      `protobuf:"varint,23,opt,name=on_failure_callback,json=onFailureCallback,proto3" json:"on_failure_callback,omitempty"`    // The task declares an Airflow on_failure_callback (#424). The agent stamps LEOFLOW_ON_FAILURE_CALLBACK=1 so the runtime re-imports dag.py and runs it in-process on the task's final failure. The callable itself is not carried.
	DeclaredVariables       []string                  `protobuf:"bytes,24,rep,name=declared_variables,json=declaredVariables,proto3" json:"declared_variables,omitempty"`       // The variable names this task declared (leoflow.yaml). The agent asks a pod-side external secret resolver only for declared names, so declaration stays the scope authority for externally-sourced secrets too (ADR 0060 / ADR 0055).
	DeclaredConnections     []string                  `protobuf:"bytes,25,rep,name=declared_connections,json=declaredConnections,proto3" json:"declared_connections,omitempty"` // The connection ids this task declared (leoflow.yaml). Same role as declared_variables for connections.
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TaskSpec) Reset() {
	*x = TaskSpec{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSpec) ProtoMessage() {}

func (x *TaskSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSpec.ProtoReflect.Descriptor instead.
func (*TaskSpec) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *TaskSpec) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TaskSpec) GetDagId() string {
	if x != nil {
		return x.DagId
	}
	return ""
}

func (x *TaskSpec) GetDagVersion() string {
	if x != nil {
		return x.DagVersion
	}
	return ""
}

func (x *TaskSpec) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TaskSpec) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskSpec) GetTryNumber() int32 {
	if x != nil {
		return x.TryNumber
	}
	return 0
}

func (x *TaskSpec) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *TaskSpec) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *TaskSpec) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *TaskSpec) GetXcomInputMapping() map[string]*XComUpstreams {
	if x != nil {
		return x.XcomInputMapping
	}
	return nil
}

func (x *TaskSpec) GetExecutionTimeoutSeconds() int32 {
	if x != nil {
		return x.ExecutionTimeoutSeconds
	}
	return 0
}

func (x *TaskSpec) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *TaskSpec) GetCallArgsJson() string {
	if x != nil {
		return x.CallArgsJson
	}
	return ""
}

func (x *TaskSpec) GetOperatorClass() string {
	if x != nil {
		return x.OperatorClass
	}
	return ""
}

func (x *TaskSpec) GetOperatorArgsJson() string {
	if x != nil {
		return x.OperatorArgsJson
	}
	return ""
}

func (x *TaskSpec) GetLogicalDate() string {
	if x != nil {
		return x.LogicalDate
	}
	return ""
}

func (x *TaskSpec) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *TaskSpec) GetDataIntervalStart() string {
	if x != nil {
		return x.DataIntervalStart
	}
	return ""
}

func (x *TaskSpec) GetDataIntervalEnd() string {
	if x != nil {
		return x.DataIntervalEnd
	}
	return ""
}

func (x *TaskSpec) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

func (x *TaskSpec) GetFirstRescheduleAt() string {
	if x != nil {
		return x.FirstRescheduleAt
	}
	return ""
}

func (x *TaskSpec) GetMaxTries() int32 {
	if x != nil {
		return x.MaxTries
	}
	return 0
}

func (x *TaskSpec) GetOnFailureCallback() bool {
	if x != nil {
		return x.OnFailureCallback
	}
	return false
}

func (x *TaskSpec) GetDeclaredVariables() []string {
	if x != nil {
		return x.DeclaredVariables
	}
	return nil
}

func (x *TaskSpec) GetDeclaredConnections() []string {
	if x != nil {
		return x.DeclaredConnections
	}
	return nil
}

// XComUpstreams is the list of upstream task_ids whose return_values feed one
// parameter. A single upstream is `task_ids: ["extract"]`; fan-in (binding a
// list of upstreams to a parameter) is `task_ids: ["a", "b", "c"]`. The runtime
// receives a JSON array when len > 1, and a single value when len == 1 — so a
// fan-in parameter is delivered as a list, a normal parameter as the value.
type XComUpstreams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskIds       []string               `protobuf:"bytes,1,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XComUpstreams) Reset() {
	*x = XComUpstreams{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XComUpstreams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XComUpstreams) ProtoMessage() {}

func (x *XComUpstreams) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XComUpstreams.ProtoReflect.Descriptor instead.
func (*XComUpstreams) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *XComUpstreams) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

type FetchXComRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UpstreamTaskId string                 `protobuf:"bytes,1,opt,name=upstream_task_id,json=upstreamTaskId,proto3" json:"upstream_task_id,omitempty"`
	Key            string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"` // defaults to 'return_value'
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FetchXComRequest) Reset() {
	*x = FetchXComRequest{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchXComRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchXComRequest) ProtoMessage() {}

func (x *FetchXComRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchXComRequest.ProtoReflect.Descriptor instead.
func (*FetchXComRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *FetchXComRequest) GetUpstreamTaskId() string {
	if x != nil {
		return x.UpstreamTaskId
	}
	return ""
}

func (x *FetchXComRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type FetchXComResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`                                // JSON-encoded payload
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // 'application/json' by default
	SizeBytes     int32                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchXComResponse) Reset() {
	*x = FetchXComResponse{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchXComResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchXComResponse) ProtoMessage() {}

func (x *FetchXComResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchXComResponse.ProtoReflect.Descriptor instead.
func (*FetchXComResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *FetchXComResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FetchXComResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FetchXComResponse) GetSizeBytes() int32 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FetchXComResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PushXComRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // defaults to 'return_value'
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // JSON-encoded payload, max 256KB
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushXComRequest) Reset() {
	*x = PushXComRequest{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushXComRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushXComRequest) ProtoMessage() {}

func (x *PushXComRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushXComRequest.ProtoReflect.Descriptor instead.
func (*PushXComRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *PushXComRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PushXComRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PushXComRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type PushXComResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Accepted        bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectionReason string                 `protobuf:"bytes,2,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"` // empty if accepted
	TtlSeconds      int32                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`               // server-set TTL
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PushXComResponse) Reset() {
	*x = PushXComResponse{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushXComResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushXComResponse) ProtoMessage() {}

func (x *PushXComResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushXComResponse.ProtoReflect.Descriptor instead.
func (*PushXComResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *PushXComResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PushXComResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *PushXComResponse) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Level         LogLevel               `protobuf:"varint,2,opt,name=level,proto3,enum=leoflow.agent.v1.LogLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Stream        string                 `protobuf:"bytes,4,opt,name=stream,proto3" json:"stream,omitempty"` // 'stdout' or 'stderr'
	LineNumber    int64                  `protobuf:"varint,5,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *LogLine) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *LogLine) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogLine) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogLine) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogLine) GetLineNumber() int64 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

type LogAck struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	AcknowledgedThroughLine int64                  `protobuf:"varint,1,opt,name=acknowledged_through_line,json=acknowledgedThroughLine,proto3" json:"acknowledged_through_line,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *LogAck) Reset() {
	*x = LogAck{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogAck) ProtoMessage() {}

func (x *LogAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogAck.ProtoReflect.Descriptor instead.
func (*LogAck) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *LogAck) GetAcknowledgedThroughLine() int64 {
	if x != nil {
		return x.AcknowledgedThroughLine
	}
	return 0
}

type ReportStateRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	State        TaskState              `protobuf:"varint,1,opt,name=state,proto3,enum=leoflow.agent.v1.TaskState" json:"state,omitempty"`
	ExitCode     int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`            // for terminal states
	ErrorMessage string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // for failed state
	OccurredAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// For TASK_STATE_UP_FOR_RESCHEDULE: the earliest time the scheduler may
	// re-dispatch this task instance (a reschedule-mode sensor poked not-ready).
	RescheduleAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=reschedule_at,json=rescheduleAt,proto3" json:"reschedule_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStateRequest) Reset() {
	*x = ReportStateRequest{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStateRequest) ProtoMessage() {}

func (x *ReportStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStateRequest.ProtoReflect.Descriptor instead.
func (*ReportStateRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *ReportStateRequest) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *ReportStateRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ReportStateRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ReportStateRequest) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *ReportStateRequest) GetRescheduleAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RescheduleAt
	}
	return nil
}

type ReportStateResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	// If the Control Plane wants the task to stop (cancellation), it signals here.
	ShouldTerminate bool `protobuf:"varint,2,opt,name=should_terminate,json=shouldTerminate,proto3" json:"should_terminate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportStateResponse) Reset() {
	*x = ReportStateResponse{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStateResponse) ProtoMessage() {}

func (x *ReportStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStateResponse.ProtoReflect.Descriptor instead.
func (*ReportStateResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ReportStateResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *ReportStateResponse) GetShouldTerminate() bool {
	if x != nil {
		return x.ShouldTerminate
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	CustomMetrics map[string]float64     `protobuf:"bytes,2,rep,name=custom_metrics,json=customMetrics,proto3" json:"custom_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // optional task-reported metrics
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

func (x *HeartbeatRequest) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *HeartbeatRequest) GetCustomMetrics() map[string]float64 {
	if x != nil {
		return x.CustomMetrics
	}
	return nil
}

// WorkAssignment is one unit of per-attempt work the control plane hands to a
// warm worker over AwaitAssignment (ADR 0058 N1b). The control plane mints the
// attempt_token and generates assignment_id; the worker replies with an
// AssignmentAck referencing assignment_id.
type WorkAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId  string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"` // control-plane-generated correlation id for this hand-off
	AttemptToken  string                 `protobuf:"bytes,2,opt,name=attempt_token,json=attemptToken,proto3" json:"attempt_token,omitempty"` // per-attempt agent JWT the worker adopts for this attempt; NEVER logged
	DagRunId      string                 `protobuf:"bytes,3,opt,name=dag_run_id,json=dagRunId,proto3" json:"dag_run_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TryNumber     int32                  `protobuf:"varint,5,opt,name=try_number,json=tryNumber,proto3" json:"try_number,omitempty"`
	DagVersionId  string                 `protobuf:"bytes,6,opt,name=dag_version_id,json=dagVersionId,proto3" json:"dag_version_id,omitempty"` // the pool identity this assignment belongs to
	LeaseSeconds  int64                  `protobuf:"varint,7,opt,name=lease_seconds,json=leaseSeconds,proto3" json:"lease_seconds,omitempty"`  // ack deadline: unacked within it => the attempt is reclaimed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkAssignment) Reset() {
	*x = WorkAssignment{}
	mi := &file_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkAssignment) ProtoMessage() {}

func (x *WorkAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkAssignment.ProtoReflect.Descriptor instead.
func (*WorkAssignment) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{20}
}

func (x *WorkAssignment) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *WorkAssignment) GetAttemptToken() string {
	if x != nil {
		return x.AttemptToken
	}
	return ""
}

func (x *WorkAssignment) GetDagRunId() string {
	if x != nil {
		return x.DagRunId
	}
	return ""
}

func (x *WorkAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *WorkAssignment) GetTryNumber() int32 {
	if x != nil {
		return x.TryNumber
	}
	return 0
}

func (x *WorkAssignment) GetDagVersionId() string {
	if x != nil {
		return x.DagVersionId
	}
	return ""
}

func (x *WorkAssignment) GetLeaseSeconds() int64 {
	if x != nil {
		return x.LeaseSeconds
	}
	return 0
}

// WorkerMessage is everything a warm worker sends UP the AwaitAssignment stream:
// its one initial registration, then per-assignment acks and slot-free signals.
type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*WorkerMessage_Register
	//	*WorkerMessage_Ack
	//	*WorkerMessage_SlotFree
	Msg           isWorkerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{21}
}

func (x *WorkerMessage) GetMsg() isWorkerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WorkerMessage) GetRegister() *WorkerRegister {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *WorkerMessage) GetAck() *AssignmentAck {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *WorkerMessage) GetSlotFree() *SlotFree {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_SlotFree); ok {
			return x.SlotFree
		}
	}
	return nil
}

type isWorkerMessage_Msg interface {
	isWorkerMessage_Msg()
}

type WorkerMessage_Register struct {
	Register *WorkerRegister `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type WorkerMessage_Ack struct {
	Ack *AssignmentAck `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type WorkerMessage_SlotFree struct {
	SlotFree *SlotFree `protobuf:"bytes,3,opt,name=slot_free,json=slotFree,proto3,oneof"`
}

func (*WorkerMessage_Register) isWorkerMessage_Msg() {}

func (*WorkerMessage_Ack) isWorkerMessage_Msg() {}

func (*WorkerMessage_SlotFree) isWorkerMessage_Msg() {}

// WorkerRegister is the mandatory first WorkerMessage. dag_version_id names which
// pool the worker serves. The worker's IDENTITY (registry key) is taken from its
// authenticated pod/bootstrap credential on the stream context, NOT from this
// payload — a worker must not be able to claim an arbitrary identity here.
type WorkerRegister struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	DagVersionId string                 `protobuf:"bytes,1,opt,name=dag_version_id,json=dagVersionId,proto3" json:"dag_version_id,omitempty"`
	// pod_name is the worker's OWN Kubernetes pod name, delivered to the
	// container via the downward API (LEOFLOW_POD_NAME). It is the durable key
	// the control plane binds a started attempt to (warm_worker_id on the running
	// TI) so a later reaper can match bound attempts against the live warm-pod set
	// ListWarmPods returns, even after a leader failover. Unlike an identity, it
	// is a locator, not a credential: the worker's authenticated identity still
	// comes from its bearer token on the stream context, never from this field.
	PodName       string `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerRegister) Reset() {
	*x = WorkerRegister{}
	mi := &file_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRegister) ProtoMessage() {}

func (x *WorkerRegister) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRegister.ProtoReflect.Descriptor instead.
func (*WorkerRegister) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{22}
}

func (x *WorkerRegister) GetDagVersionId() string {
	if x != nil {
		return x.DagVersionId
	}
	return ""
}

func (x *WorkerRegister) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

// AssignmentAck answers a WorkAssignment. started=true means the worker began the
// attempt (the control plane marks it active and cancels the lease). started=false
// means the worker refuses or cannot start it (the control plane reclaims it).
type AssignmentAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId  string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	Started       bool                   `protobuf:"varint,2,opt,name=started,proto3" json:"started,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignmentAck) Reset() {
	*x = AssignmentAck{}
	mi := &file_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignmentAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignmentAck) ProtoMessage() {}

func (x *AssignmentAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignmentAck.ProtoReflect.Descriptor instead.
func (*AssignmentAck) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{23}
}

func (x *AssignmentAck) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *AssignmentAck) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

// SlotFree signals that the worker freed an execution slot. Reserved for the
// placement layer (N1b1-place); the transport carries it now and the registry
// records it.
type SlotFree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotFree) Reset() {
	*x = SlotFree{}
	mi := &file_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotFree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotFree) ProtoMessage() {}

func (x *SlotFree) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotFree.ProtoReflect.Descriptor instead.
func (*SlotFree) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{24}
}

type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ShouldTerminate bool                   `protobuf:"varint,1,opt,name=should_terminate,json=shouldTerminate,proto3" json:"should_terminate,omitempty"`
	ServerTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	// A freshly minted, task-scoped agent token the control plane issues when the
	// heartbeat proves the attempt is still live (ADR 0055 Fix #4). When non-empty
	// the agent atomically swaps its bearer to this value, so a long task keeps a
	// working credential while the short per-attempt TTL bounds a stolen/finished
	// one. Empty means "keep the current token" (no renewal this beat, or the
	// attempt is superseded/past its lifetime ceiling). Never logged.
	RenewedToken  string `protobuf:"bytes,3,opt,name=renewed_token,json=renewedToken,proto3" json:"renewed_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{25}
}

func (x *HeartbeatResponse) GetShouldTerminate() bool {
	if x != nil {
		return x.ShouldTerminate
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *HeartbeatResponse) GetRenewedToken() string {
	if x != nil {
		return x.RenewedToken
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x10leoflow.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x15\n" +
	"\x13GetVariablesRequest\"\xa9\x01\n" +
	"\x14GetVariablesResponse\x12S\n" +
	"\tvariables\x18\x01 \x03(\v25.leoflow.agent.v1.GetVariablesResponse.VariablesEntryR\tvariables\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x17\n" +
	"\x15GetConnectionsRequest\"\xc2\x01\n" +
	"\x16GetConnectionsResponse\x12e\n" +
	"\x0fconnection_uris\x18\x01 \x03(\v2<.leoflow.agent.v1.GetConnectionsResponse.ConnectionUrisEntryR\x0econnectionUris\x1aA\n" +
	"\x13ConnectionUrisEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x16\n" +
	"\x14ExchangeTokenRequest\"8\n" +
	"\x15ExchangeTokenResponse\x12\x1f\n" +
	"\vagent_token\x18\x01 \x01(\tR\n" +
	"agentToken\"\xe8\x01\n" +
	"\x0fRegisterRequest\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12T\n" +
	"\venvironment\x18\x03 \x03(\v22.leoflow.agent.v1.RegisterRequest.EnvironmentEntryR\venvironment\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"\x14\n" +
	"\x12GetTaskSpecRequest\"\xc3\t\n" +
	"\bTaskSpec\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06dag_id\x18\x02 \x01(\tR\x05dagId\x12\x1f\n" +
	"\vdag_version\x18\x03 \x01(\tR\n" +
	"dagVersion\x12\x15\n" +
	"\x06run_id\x18\x04 \x01(\tR\x05runId\x12\x17\n" +
	"\atask_id\x18\x05 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"try_number\x18\x06 \x01(\x05R\ttryNumber\x12\x1a\n" +
	"\boperator\x18\a \x01(\tR\boperator\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\b \x01(\tR\n" +
	"entrypoint\x12M\n" +
	"\venvironment\x18\t \x03(\v2+.leoflow.agent.v1.TaskSpec.EnvironmentEntryR\venvironment\x12^\n" +
	"\x12xcom_input_mapping\x18\n" +
	" \x03(\v20.leoflow.agent.v1.TaskSpec.XcomInputMappingEntryR\x10xcomInputMapping\x12:\n" +
	"\x19execution_timeout_seconds\x18\v \x01(\x05R\x17executionTimeoutSeconds\x12-\n" +
	"\x05extra\x18\f \x01(\v2\x17.google.protobuf.StructR\x05extra\x12$\n" +
	"\x0ecall_args_json\x18\r \x01(\tR\fcallArgsJson\x12%\n" +
	"\x0eoperator_class\x18\x0e \x01(\tR\roperatorClass\x12,\n" +
	"\x12operator_args_json\x18\x0f \x01(\tR\x10operatorArgsJson\x12!\n" +
	"\flogical_date\x18\x10 \x01(\tR\vlogicalDate\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x11 \x03(\tR\tdependsOn\x12.\n" +
	"\x13data_interval_start\x18\x12 \x01(\tR\x11dataIntervalStart\x12*\n" +
	"\x11data_interval_end\x18\x13 \x01(\tR\x0fdataIntervalEnd\x12\x1f\n" +
	"\vparams_json\x18\x14 \x01(\tR\n" +
	"paramsJson\x12.\n" +
	"\x13first_reschedule_at\x18\x15 \x01(\tR\x11firstRescheduleAt\x12\x1b\n" +
	"\tmax_tries\x18\x16 \x01(\x05R\bmaxTries\x12.\n" +
	"\x13on_failure_callback\x18\x17 \x01(\bR\x11onFailureCallback\x12-\n" +
	"\x12declared_variables\x18\x18 \x03(\tR\x11declaredVariables\x121\n" +
	"\x14declared_connections\x18\x19 \x03(\tR\x13declaredConnections\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1ad\n" +
	"\x15XcomInputMappingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.leoflow.agent.v1.XComUpstreamsR\x05value:\x028\x01\"*\n" +
	"\rXComUpstreams\x12\x19\n" +
	"\btask_ids\x18\x01 \x03(\tR\ataskIds\"N\n" +
	"\x10FetchXComRequest\x12(\n" +
	"\x10upstream_task_id\x18\x01 \x01(\tR\x0eupstreamTaskId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\xa6\x01\n" +
	"\x11FetchXComResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x05R\tsizeBytes\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\\\n" +
	"\x0fPushXComRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"z\n" +
	"\x10PushXComResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12)\n" +
	"\x10rejection_reason\x18\x02 \x01(\tR\x0frejectionReason\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x05R\n" +
	"ttlSeconds\"\xbe\x01\n" +
	"\aLogLine\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x120\n" +
	"\x05level\x18\x02 \x01(\x0e2\x1a.leoflow.agent.v1.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06stream\x18\x04 \x01(\tR\x06stream\x12\x1f\n" +
	"\vline_number\x18\x05 \x01(\x03R\n" +
	"lineNumber\"D\n" +
	"\x06LogAck\x12:\n" +
	"\x19acknowledged_through_line\x18\x01 \x01(\x03R\x17acknowledgedThroughLine\"\x87\x02\n" +
	"\x12ReportStateRequest\x121\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1b.leoflow.agent.v1.TaskStateR\x05state\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12?\n" +
	"\rreschedule_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\frescheduleAt\"d\n" +
	"\x13ReportStateResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12)\n" +
	"\x10should_terminate\x18\x02 \x01(\bR\x0fshouldTerminate\"\xe7\x01\n" +
	"\x10HeartbeatRequest\x123\n" +
	"\asent_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12\\\n" +
	"\x0ecustom_metrics\x18\x02 \x03(\v25.leoflow.agent.v1.HeartbeatRequest.CustomMetricsEntryR\rcustomMetrics\x1a@\n" +
	"\x12CustomMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xfb\x01\n" +
	"\x0eWorkAssignment\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12#\n" +
	"\rattempt_token\x18\x02 \x01(\tR\fattemptToken\x12\x1c\n" +
	"\n" +
	"dag_run_id\x18\x03 \x01(\tR\bdagRunId\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"try_number\x18\x05 \x01(\x05R\ttryNumber\x12$\n" +
	"\x0edag_version_id\x18\x06 \x01(\tR\fdagVersionId\x12#\n" +
	"\rlease_seconds\x18\a \x01(\x03R\fleaseSeconds\"\xc6\x01\n" +
	"\rWorkerMessage\x12>\n" +
	"\bregister\x18\x01 \x01(\v2 .leoflow.agent.v1.WorkerRegisterH\x00R\bregister\x123\n" +
	"\x03ack\x18\x02 \x01(\v2\x1f.leoflow.agent.v1.AssignmentAckH\x00R\x03ack\x129\n" +
	"\tslot_free\x18\x03 \x01(\v2\x1a.leoflow.agent.v1.SlotFreeH\x00R\bslotFreeB\x05\n" +
	"\x03msg\"Q\n" +
	"\x0eWorkerRegister\x12$\n" +
	"\x0edag_version_id\x18\x01 \x01(\tR\fdagVersionId\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\"N\n" +
	"\rAssignmentAck\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12\x18\n" +
	"\astarted\x18\x02 \x01(\bR\astarted\"\n" +
	"\n" +
	"\bSlotFree\"\xa0\x01\n" +
	"\x11HeartbeatResponse\x12)\n" +
	"\x10should_terminate\x18\x01 \x01(\bR\x0fshouldTerminate\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x12#\n" +
	"\rrenewed_token\x18\x03 \x01(\tR\frenewedToken*w\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x03\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x04*\xa8\x01\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_STATE_RUNNING\x10\x01\x12\x16\n" +
	"\x12TASK_STATE_SUCCESS\x10\x02\x12\x15\n" +
	"\x11TASK_STATE_FAILED\x10\x03\x12\x16\n" +
	"\x12TASK_STATE_SKIPPED\x10\x04\x12 \n" +
	"\x1cTASK_STATE_UP_FOR_RESCHEDULE\x10\x052\xd4\a\n" +
	"\fAgentService\x12`\n" +
	"\rExchangeToken\x12&.leoflow.agent.v1.ExchangeTokenRequest\x1a'.leoflow.agent.v1.ExchangeTokenResponse\x12Q\n" +
	"\bRegister\x12!.leoflow.agent.v1.RegisterRequest\x1a\".leoflow.agent.v1.RegisterResponse\x12O\n" +
	"\vGetTaskSpec\x12$.leoflow.agent.v1.GetTaskSpecRequest\x1a\x1a.leoflow.agent.v1.TaskSpec\x12T\n" +
	"\tFetchXCom\x12\".leoflow.agent.v1.FetchXComRequest\x1a#.leoflow.agent.v1.FetchXComResponse\x12Q\n" +
	"\bPushXCom\x12!.leoflow.agent.v1.PushXComRequest\x1a\".leoflow.agent.v1.PushXComResponse\x12E\n" +
	"\n" +
	"StreamLogs\x12\x19.leoflow.agent.v1.LogLine\x1a\x18.leoflow.agent.v1.LogAck(\x010\x01\x12Z\n" +
	"\vReportState\x12$.leoflow.agent.v1.ReportStateRequest\x1a%.leoflow.agent.v1.ReportStateResponse\x12T\n" +
	"\tHeartbeat\x12\".leoflow.agent.v1.HeartbeatRequest\x1a#.leoflow.agent.v1.HeartbeatResponse\x12]\n" +
	"\fGetVariables\x12%.leoflow.agent.v1.GetVariablesRequest\x1a&.leoflow.agent.v1.GetVariablesResponse\x12c\n" +
	"\x0eGetConnections\x12'.leoflow.agent.v1.GetConnectionsRequest\x1a(.leoflow.agent.v1.GetConnectionsResponse\x12X\n" +
	"\x0fAwaitAssignment\x12\x1f.leoflow.agent.v1.WorkerMessage\x1a .leoflow.agent.v1.WorkAssignment(\x010\x01B6Z4github.com/neochaotic/leoflow/proto/agent/v1;agentv1b\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_agent_proto_goTypes = []any{
	(LogLevel)(0),                  // 0: leoflow.agent.v1.LogLevel
	(TaskState)(0),                 // 1: leoflow.agent.v1.TaskState
	(*GetVariablesRequest)(nil),    // 2: leoflow.agent.v1.GetVariablesRequest
	(*GetVariablesResponse)(nil),   // 3: leoflow.agent.v1.GetVariablesResponse
	(*GetConnectionsRequest)(nil),  // 4: leoflow.agent.v1.GetConnectionsRequest
	(*GetConnectionsResponse)(nil), // 5: leoflow.agent.v1.GetConnectionsResponse
	(*ExchangeTokenRequest)(nil),   // 6: leoflow.agent.v1.ExchangeTokenRequest
	(*ExchangeTokenResponse)(nil),  // 7: leoflow.agent.v1.ExchangeTokenResponse
	(*RegisterRequest)(nil),        // 8: leoflow.agent.v1.RegisterRequest
	(*RegisterResponse)(nil),       // 9: leoflow.agent.v1.RegisterResponse
	(*GetTaskSpecRequest)(nil),     // 10: leoflow.agent.v1.GetTaskSpecRequest
	(*TaskSpec)(nil),               // 11: leoflow.agent.v1.TaskSpec
	(*XComUpstreams)(nil),          // 12: leoflow.agent.v1.XComUpstreams
	(*FetchXComRequest)(nil),       // 13: leoflow.agent.v1.FetchXComRequest
	(*FetchXComResponse)(nil),      // 14: leoflow.agent.v1.FetchXComResponse
	(*PushXComRequest)(nil),        // 15: leoflow.agent.v1.PushXComRequest
	(*PushXComResponse)(nil),       // 16: leoflow.agent.v1.PushXComResponse
	(*LogLine)(nil),                // 17: leoflow.agent.v1.LogLine
	(*LogAck)(nil),                 // 18: leoflow.agent.v1.LogAck
	(*ReportStateRequest)(nil),     // 19: leoflow.agent.v1.ReportStateRequest
	(*ReportStateResponse)(nil),    // 20: leoflow.agent.v1.ReportStateResponse
	(*HeartbeatRequest)(nil),       // 21: leoflow.agent.v1.HeartbeatRequest
	(*WorkAssignment)(nil),         // 22: leoflow.agent.v1.WorkAssignment
	(*WorkerMessage)(nil),          // 23: leoflow.agent.v1.WorkerMessage
	(*WorkerRegister)(nil),         // 24: leoflow.agent.v1.WorkerRegister
	(*AssignmentAck)(nil),          // 25: leoflow.agent.v1.AssignmentAck
	(*SlotFree)(nil),               // 26: leoflow.agent.v1.SlotFree
	(*HeartbeatResponse)(nil),      // 27: leoflow.agent.v1.HeartbeatResponse
	nil,                            // 28: leoflow.agent.v1.GetVariablesResponse.VariablesEntry
	nil,                            // 29: leoflow.agent.v1.GetConnectionsResponse.ConnectionUrisEntry
	nil,                            // 30: leoflow.agent.v1.RegisterRequest.EnvironmentEntry
	nil,                            // 31: leoflow.agent.v1.TaskSpec.EnvironmentEntry
	nil,                            // 32: leoflow.agent.v1.TaskSpec.XcomInputMappingEntry
	nil,                            // 33: leoflow.agent.v1.HeartbeatRequest.CustomMetricsEntry
	(*timestamppb.Timestamp)(nil),  // 34: google.protobuf.Timestamp
	(*structpb.Struct)(nil),        // 35: google.protobuf.Struct
}
var file_agent_proto_depIdxs = []int32{
	28, // 0: leoflow.agent.v1.GetVariablesResponse.variables:type_name -> leoflow.agent.v1.GetVariablesResponse.VariablesEntry
	29, // 1: leoflow.agent.v1.GetConnectionsResponse.connection_uris:type_name -> leoflow.agent.v1.GetConnectionsResponse.ConnectionUrisEntry
	30, // 2: leoflow.agent.v1.RegisterRequest.environment:type_name -> leoflow.agent.v1.RegisterRequest.EnvironmentEntry
	34, // 3: leoflow.agent.v1.RegisterResponse.server_time:type_name -> google.protobuf.Timestamp
	31, // 4: leoflow.agent.v1.TaskSpec.environment:type_name -> leoflow.agent.v1.TaskSpec.EnvironmentEntry
	32, // 5: leoflow.agent.v1.TaskSpec.xcom_input_mapping:type_name -> leoflow.agent.v1.TaskSpec.XcomInputMappingEntry
	35, // 6: leoflow.agent.v1.TaskSpec.extra:type_name -> google.protobuf.Struct
	34, // 7: leoflow.agent.v1.FetchXComResponse.created_at:type_name -> google.protobuf.Timestamp
	34, // 8: leoflow.agent.v1.LogLine.time:type_name -> google.protobuf.Timestamp
	0,  // 9: leoflow.agent.v1.LogLine.level:type_name -> leoflow.agent.v1.LogLevel
	1,  // 10: leoflow.agent.v1.ReportStateRequest.state:type_name -> leoflow.agent.v1.TaskState
	34, // 11: leoflow.agent.v1.ReportStateRequest.occurred_at:type_name -> google.protobuf.Timestamp
	34, // 12: leoflow.agent.v1.ReportStateRequest.reschedule_at:type_name -> google.protobuf.Timestamp
	34, // 13: leoflow.agent.v1.HeartbeatRequest.sent_at:type_name -> google.protobuf.Timestamp
	33, // 14: leoflow.agent.v1.HeartbeatRequest.custom_metrics:type_name -> leoflow.agent.v1.HeartbeatRequest.CustomMetricsEntry
	24, // 15: leoflow.agent.v1.WorkerMessage.register:type_name -> leoflow.agent.v1.WorkerRegister
	25, // 16: leoflow.agent.v1.WorkerMessage.ack:type_name -> leoflow.agent.v1.AssignmentAck
	26, // 17: leoflow.agent.v1.WorkerMessage.slot_free:type_name -> leoflow.agent.v1.SlotFree
	34, // 18: leoflow.agent.v1.HeartbeatResponse.server_time:type_name -> google.protobuf.Timestamp
	12, // 19: leoflow.agent.v1.TaskSpec.XcomInputMappingEntry.value:type_name -> leoflow.agent.v1.XComUpstreams
	6,  // 20: leoflow.agent.v1.AgentService.ExchangeToken:input_type -> leoflow.agent.v1.ExchangeTokenRequest
	8,  // 21: leoflow.agent.v1.AgentService.Register:input_type -> leoflow.agent.v1.RegisterRequest
	10, // 22: leoflow.agent.v1.AgentService.GetTaskSpec:input_type -> leoflow.agent.v1.GetTaskSpecRequest
	13, // 23: leoflow.agent.v1.AgentService.FetchXCom:input_type -> leoflow.agent.v1.FetchXComRequest
	15, // 24: leoflow.agent.v1.AgentService.PushXCom:input_type -> leoflow.agent.v1.PushXComRequest
	17, // 25: leoflow.agent.v1.AgentService.StreamLogs:input_type -> leoflow.agent.v1.LogLine
	19, // 26: leoflow.agent.v1.AgentService.ReportState:input_type -> leoflow.agent.v1.ReportStateRequest
	21, // 27: leoflow.agent.v1.AgentService.Heartbeat:input_type -> leoflow.agent.v1.HeartbeatRequest
	2,  // 28: leoflow.agent.v1.AgentService.GetVariables:input_type -> leoflow.agent.v1.GetVariablesRequest
	4,  // 29: leoflow.agent.v1.AgentService.GetConnections:input_type -> leoflow.agent.v1.GetConnectionsRequest
	23, // 30: leoflow.agent.v1.AgentService.AwaitAssignment:input_type -> leoflow.agent.v1.WorkerMessage
	7,  // 31: leoflow.agent.v1.AgentService.ExchangeToken:output_type -> leoflow.agent.v1.ExchangeTokenResponse
	9,  // 32: leoflow.agent.v1.AgentService.Register:output_type -> leoflow.agent.v1.RegisterResponse
	11, // 33: leoflow.agent.v1.AgentService.GetTaskSpec:output_type -> leoflow.agent.v1.TaskSpec
	14, // 34: leoflow.agent.v1.AgentService.FetchXCom:output_type -> leoflow.agent.v1.FetchXComResponse
	16, // 35: leoflow.agent.v1.AgentService.PushXCom:output_type -> leoflow.agent.v1.PushXComResponse
	18, // 36: leoflow.agent.v1.AgentService.StreamLogs:output_type -> leoflow.agent.v1.LogAck
	20, // 37: leoflow.agent.v1.AgentService.ReportState:output_type -> leoflow.agent.v1.ReportStateResponse
	27, // 38: leoflow.agent.v1.AgentService.Heartbeat:output_type -> leoflow.agent.v1.HeartbeatResponse
	3,  // 39: leoflow.agent.v1.AgentService.GetVariables:output_type -> leoflow.agent.v1.GetVariablesResponse
	5,  // 40: leoflow.agent.v1.AgentService.GetConnections:output_type -> leoflow.agent.v1.GetConnectionsResponse
	22, // 41: leoflow.agent.v1.AgentService.AwaitAssignment:output_type -> leoflow.agent.v1.WorkAssignment
	31, // [31:42] is the sub-list for method output_type
	20, // [20:31] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[21].OneofWrappers = []any{
		(*WorkerMessage_Register)(nil),
		(*WorkerMessage_Ack)(nil),
		(*WorkerMessage_SlotFree)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
