#!/usr/bin/env bash
#
# 02-install-leoflow.sh — Install Leoflow Pro on the test cluster (Bitnami path).
#
# This is the "evaluate the chart end-to-end" install:
#   - in-cluster plain official Postgres + Redis (cheapest; NOT production — no
#     HA, ephemeral emptyDir storage). We use the official images instead of the
#     Bitnami charts because Bitnami moved versioned images behind a paywall /
#     to docker.io/bitnamilegacy in Aug 2025, breaking pinned chart installs.
#     The managed-services path (Cloud SQL + Memorystore) is the next step,
#     documented as 03 in the README.
#   - cert-manager issues the agent <-> control-plane gRPC server cert, and we
#     publish the signing CA as a ConfigMap the chart hands to task pods
#     (agentTLS is ON by default for Pro, issue #58).
#   - all credentials are GENERATED LOCALLY into a gitignored values.local.yaml
#     and never committed.
#
# Prereqs: ./00-create-cluster.sh and ./01-install-addons.sh already ran.
# Idempotent: helm upgrade --install + kubectl apply are safe to re-run. The
# generated secrets persist in values.local.yaml so re-runs keep the same creds.
#
# Usage:
#   ./02-install-leoflow.sh
#   IMAGE_TAG=v0.0.1-prealpha.28 NAMESPACE=leoflow ./02-install-leoflow.sh
#
set -euo pipefail

# ---- Parameters (override via environment) ---------------------------------
NAMESPACE="${NAMESPACE:-leoflow}"        # server targets the 'leoflow' ns for task pods
RELEASE="${RELEASE:-leoflow}"            # helm release name == chart fullname 'leoflow'
# NOTE: server images are tagged WITHOUT a leading 'v' (e.g. 0.0.1-prealpha.28);
# migrate accepts both. Keep the no-'v' form so a single tag works for both.
IMAGE_TAG="${IMAGE_TAG:-0.0.1-prealpha.28}"  # pin server + migrate image (values.yaml requires explicit pin)
PG_IMAGE="${PG_IMAGE:-postgres:16-alpine}"    # official Postgres image (test datastore)
REDIS_IMAGE="${REDIS_IMAGE:-redis:7-alpine}"  # official Redis image (test datastore)
LOGS_PVC_SIZE="${LOGS_PVC_SIZE:-5Gi}"    # small + cheap for the test (default chart is 50Gi)

# Resolve paths relative to this script so it runs from anywhere.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHART_DIR="$(cd "$SCRIPT_DIR/../../helm/leoflow" && pwd)"
VALUES_LOCAL="$SCRIPT_DIR/values.local.yaml"   # gitignored — holds generated secrets

# Cert-manager resource names for the agent-TLS channel.
SERVER_CERT_SECRET="leoflow-agent-tls"
CA_CONFIGMAP="leoflow-agent-ca"

log() { printf '\n\033[1;34m==>\033[0m %s\n' "$*"; }
die() { printf '\n\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

command -v openssl >/dev/null || die "openssl is required to generate secrets."
kubectl cluster-info >/dev/null 2>&1 || die "No reachable cluster. Run ./00-create-cluster.sh first."
kubectl get ns cert-manager >/dev/null 2>&1 || die "cert-manager not found. Run ./01-install-addons.sh first."

# ---- 0. Namespace -----------------------------------------------------------
log "Ensuring namespace '$NAMESPACE'"
kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

# ---- 1. Generate credentials ONCE into a gitignored values file ------------
# Re-runs reuse the existing file so creds stay stable across upgrades.
if [ -f "$VALUES_LOCAL" ]; then
  log "Reusing existing $VALUES_LOCAL (generated secrets preserved)"
  # Recover the PG password robustly: prefer the live cluster Secret (source of
  # truth); fall back to parsing the DSN in the values file. Never parse a
  # comment line — a manual edit must not silently break the re-run.
  PG_PASSWORD="$(kubectl -n "$NAMESPACE" get secret pg-postgresql -o jsonpath='{.data.password}' 2>/dev/null | base64 -d || true)"
  if [ -z "$PG_PASSWORD" ]; then
    PG_PASSWORD="$(sed -n 's#.*postgres://leoflow:\([^@]*\)@.*#\1#p' "$VALUES_LOCAL" | head -1)"
  fi
  [ -n "$PG_PASSWORD" ] || die "Could not recover the PG password from the cluster Secret or $VALUES_LOCAL."
else
  log "Generating credentials -> $VALUES_LOCAL (gitignored, never committed)"
  PG_PASSWORD="$(openssl rand -hex 16)"
  JWT_SECRET="$(openssl rand -base64 64 | tr -d '\n')"
  SECRET_KEY="$(openssl rand -hex 16)"          # 32 bytes (64 hex) for AES-256
  BOOTSTRAP_PASSWORD="$(openssl rand -hex 12)"  # initial admin password

  cat > "$VALUES_LOCAL" <<EOF
# GENERATED by 02-install-leoflow.sh — DO NOT COMMIT (gitignored).
# Contains the Postgres password + Leoflow secrets for this test install.
# (The PG password is embedded in database.url below; re-runs recover it from
#  the cluster Secret, falling back to that DSN — never from a comment.)

database:
  url: postgres://leoflow:${PG_PASSWORD}@pg-postgresql.${NAMESPACE}.svc.cluster.local:5432/leoflow?sslmode=disable
redis:
  url: redis://redis-master.${NAMESPACE}.svc.cluster.local:6379/0

auth:
  jwtSecret: "${JWT_SECRET}"
secretKey: "${SECRET_KEY}"
bootstrap:
  password: "${BOOTSTRAP_PASSWORD}"

image:
  tag: "${IMAGE_TAG}"
migrations:
  image:
    tag: "${IMAGE_TAG}"

replicaCount: 1

# Agent <-> control-plane gRPC TLS (issue #58), wired to cert-manager output.
agentTLS:
  enabled: true
  serverCertSecret: "${SERVER_CERT_SECRET}"
  caConfigMap: "${CA_CONFIGMAP}"

# Small, cheap durable log volume for the test (chart default is 50Gi).
logs:
  persistence:
    enabled: true
    size: ${LOGS_PVC_SIZE}
EOF
  chmod 600 "$VALUES_LOCAL"
  log "Initial admin login: admin@leoflow.local / ${BOOTSTRAP_PASSWORD}  (also in $VALUES_LOCAL)"
fi

# ---- 2. Official Postgres + Redis (ephemeral emptyDir, no persistence) ------
# Plain upstream images. Service names match the DSNs in values.local.yaml:
#   pg-postgresql:5432  and  redis-master:6379  (Bitnami-style names kept stable).
log "Deploying Postgres ($PG_IMAGE) + Redis ($REDIS_IMAGE) — ephemeral test datastores"
kubectl apply -n "$NAMESPACE" -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: pg-postgresql
type: Opaque
stringData:
  password: "${PG_PASSWORD}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-postgresql
  labels: { app: pg-postgresql }
spec:
  replicas: 1
  selector: { matchLabels: { app: pg-postgresql } }
  template:
    metadata:
      labels: { app: pg-postgresql }
    spec:
      containers:
        - name: postgres
          image: ${PG_IMAGE}
          env:
            - name: POSTGRES_USER
              value: leoflow
            - name: POSTGRES_DB
              value: leoflow
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: pg-postgresql, key: password } }
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports: [{ containerPort: 5432 }]
          resources:
            requests: { cpu: 100m, memory: 128Mi }
            limits: { cpu: "1", memory: 512Mi }
          readinessProbe:
            exec: { command: ["pg_isready", "-U", "leoflow", "-d", "leoflow"] }
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - { name: data, mountPath: /var/lib/postgresql/data }
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pg-postgresql
spec:
  selector: { app: pg-postgresql }
  ports: [{ port: 5432, targetPort: 5432 }]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels: { app: redis-master }
spec:
  replicas: 1
  selector: { matchLabels: { app: redis-master } }
  template:
    metadata:
      labels: { app: redis-master }
    spec:
      containers:
        - name: redis
          image: ${REDIS_IMAGE}
          args: ["--save", "", "--appendonly", "no"]
          ports: [{ containerPort: 6379 }]
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits: { cpu: 500m, memory: 256Mi }
          readinessProbe:
            exec: { command: ["redis-cli", "ping"] }
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
spec:
  selector: { app: redis-master }
  ports: [{ port: 6379, targetPort: 6379 }]
EOF

log "Waiting for Postgres + Redis to be ready"
kubectl -n "$NAMESPACE" rollout status deploy/pg-postgresql --timeout=180s
kubectl -n "$NAMESPACE" rollout status deploy/redis-master --timeout=120s

# ---- 3. Agent-TLS: cert-manager issuer + CA + server cert ------------------
# Two-tier (self-signed root CA -> server leaf) so the CA we hand to task pods
# is a real CA, not a self-signed leaf. dnsNames cover the in-cluster gRPC
# service the agent dials: <release>.<ns>.svc.cluster.local:9091.
log "Creating cert-manager Issuer + CA + server certificate for the agent channel"
kubectl apply -n "$NAMESPACE" -f - <<EOF
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: leoflow-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: leoflow-ca
spec:
  isCA: true
  commonName: leoflow-agent-ca
  secretName: leoflow-ca
  duration: 87600h    # 10y
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: leoflow-selfsigned
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: leoflow-ca-issuer
spec:
  ca:
    secretName: leoflow-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${SERVER_CERT_SECRET}
spec:
  secretName: ${SERVER_CERT_SECRET}
  duration: 8760h     # 1y
  dnsNames:
    - ${RELEASE}
    - ${RELEASE}.${NAMESPACE}
    - ${RELEASE}.${NAMESPACE}.svc
    - ${RELEASE}.${NAMESPACE}.svc.cluster.local
  issuerRef:
    name: leoflow-ca-issuer
    kind: Issuer
EOF

log "Waiting for the server certificate to be issued"
kubectl wait -n "$NAMESPACE" --for=condition=Ready certificate/"$SERVER_CERT_SECRET" --timeout=120s

# ---- 4. Publish the CA as a ConfigMap for task pods ------------------------
# The chart passes this ConfigMap name to the dispatcher; task pods mount its
# ca.crt so the agent verifies the server cert.
log "Publishing CA into ConfigMap '$CA_CONFIGMAP'"
CA_CRT="$(kubectl get secret "$SERVER_CERT_SECRET" -n "$NAMESPACE" -o jsonpath='{.data.ca\.crt}' | base64 -d)"
[ -n "$CA_CRT" ] || die "Could not read ca.crt from $SERVER_CERT_SECRET."
kubectl create configmap "$CA_CONFIGMAP" -n "$NAMESPACE" \
  --from-literal=ca.crt="$CA_CRT" \
  --dry-run=client -o yaml | kubectl apply -f -

# ---- 5. Pre-flight: the chart still wires the agentTLS knobs ----------------
# Cheap guard so a renamed/removed agentTLS knob fails loudly here instead of
# producing a silently misconfigured (insecure or non-booting) install.
log "Pre-flight: verifying the chart renders the agentTLS server cert + CA"
RENDERED="$(helm template "$RELEASE" "$CHART_DIR" -f "$VALUES_LOCAL" 2>/dev/null || true)"
echo "$RENDERED" | grep -q "$SERVER_CERT_SECRET" \
  || die "Chart render does not reference agentTLS.serverCertSecret ($SERVER_CERT_SECRET). The chart's agentTLS knobs may have changed — aborting before a misconfigured install."
echo "$RENDERED" | grep -q "$CA_CONFIGMAP" \
  || die "Chart render does not reference agentTLS.caConfigMap ($CA_CONFIGMAP). The chart's agentTLS knobs may have changed — aborting."

# ---- 6. Install Leoflow -----------------------------------------------------
log "Installing Leoflow (release '$RELEASE', image tag $IMAGE_TAG)"
helm upgrade --install "$RELEASE" "$CHART_DIR" \
  -n "$NAMESPACE" \
  -f "$VALUES_LOCAL" \
  --wait --timeout 8m

# ---- 7. Verify --------------------------------------------------------------
log "Rollout status"
kubectl -n "$NAMESPACE" rollout status "deploy/$RELEASE" --timeout=240s
kubectl -n "$NAMESPACE" get pods

cat <<EOF

$(printf '\033[1;32m==> Leoflow Pro installed.\033[0m')

Open the UI:
  kubectl -n $NAMESPACE port-forward svc/$RELEASE 8080:8080
  # then browse http://127.0.0.1:8080/
  # login username: admin@leoflow.local  (the bootstrap admin email, NOT "admin")
  # password: see bootstrap.password in $VALUES_LOCAL

Readiness:
  curl -fsS http://127.0.0.1:8080/readyz

Next (managed datastores): see README "03 — managed datastores (Cloud SQL + Memorystore)".
EOF
