#!/usr/bin/env bash
#
# 02-install-leoflow.sh — Install Leoflow Pro on the test cluster (Bitnami path).
#
# This is the "evaluate the chart end-to-end" install:
#   - in-cluster Bitnami Postgres + Redis (cheapest; NOT production — no HA, no
#     persistence). The managed-services path (Cloud SQL + Memorystore) is the
#     next step, documented as 03 in the README.
#   - cert-manager issues the agent <-> control-plane gRPC server cert, and we
#     publish the signing CA as a ConfigMap the chart hands to task pods
#     (agentTLS is ON by default for Pro, issue #58).
#   - all credentials are GENERATED LOCALLY into a gitignored values.local.yaml
#     and never committed.
#
# Prereqs: ./00-create-cluster.sh and ./01-install-addons.sh already ran.
# Idempotent: helm upgrade --install + kubectl apply are safe to re-run. The
# generated secrets persist in values.local.yaml so re-runs keep the same creds.
#
# Usage:
#   ./02-install-leoflow.sh
#   IMAGE_TAG=v0.0.1-prealpha.28 NAMESPACE=leoflow ./02-install-leoflow.sh
#
set -euo pipefail

# ---- Parameters (override via environment) ---------------------------------
NAMESPACE="${NAMESPACE:-leoflow}"        # server targets the 'leoflow' ns for task pods
RELEASE="${RELEASE:-leoflow}"            # helm release name == chart fullname 'leoflow'
IMAGE_TAG="${IMAGE_TAG:-v0.0.1-prealpha.28}"  # pin server + migrate image (values.yaml requires explicit pin)
PG_CHART_VERSION="${PG_CHART_VERSION:-16}"    # bitnami/postgresql major
REDIS_CHART_VERSION="${REDIS_CHART_VERSION:-20}"  # bitnami/redis major
LOGS_PVC_SIZE="${LOGS_PVC_SIZE:-5Gi}"    # small + cheap for the test (default chart is 50Gi)

# Resolve paths relative to this script so it runs from anywhere.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHART_DIR="$(cd "$SCRIPT_DIR/../../helm/leoflow" && pwd)"
VALUES_LOCAL="$SCRIPT_DIR/values.local.yaml"   # gitignored — holds generated secrets

# Cert-manager resource names for the agent-TLS channel.
SERVER_CERT_SECRET="leoflow-agent-tls"
CA_CONFIGMAP="leoflow-agent-ca"

log() { printf '\n\033[1;34m==>\033[0m %s\n' "$*"; }
die() { printf '\n\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

command -v openssl >/dev/null || die "openssl is required to generate secrets."
kubectl cluster-info >/dev/null 2>&1 || die "No reachable cluster. Run ./00-create-cluster.sh first."
kubectl get ns cert-manager >/dev/null 2>&1 || die "cert-manager not found. Run ./01-install-addons.sh first."

# ---- 0. Namespace -----------------------------------------------------------
log "Ensuring namespace '$NAMESPACE'"
kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

# ---- 1. Generate credentials ONCE into a gitignored values file ------------
# Re-runs reuse the existing file so creds stay stable across upgrades.
if [ -f "$VALUES_LOCAL" ]; then
  log "Reusing existing $VALUES_LOCAL (generated secrets preserved)"
  PG_PASSWORD="$(grep -E '^[[:space:]]*# pgPassword:' "$VALUES_LOCAL" | awk '{print $3}')"
else
  log "Generating credentials -> $VALUES_LOCAL (gitignored, never committed)"
  PG_PASSWORD="$(openssl rand -hex 16)"
  JWT_SECRET="$(openssl rand -base64 64 | tr -d '\n')"
  SECRET_KEY="$(openssl rand -hex 16)"          # 32 bytes (64 hex) for AES-256
  BOOTSTRAP_PASSWORD="$(openssl rand -hex 12)"  # initial admin password

  cat > "$VALUES_LOCAL" <<EOF
# GENERATED by 02-install-leoflow.sh — DO NOT COMMIT (gitignored).
# Contains the Bitnami Postgres password + Leoflow secrets for this test install.
# pgPassword: ${PG_PASSWORD}

database:
  url: postgres://leoflow:${PG_PASSWORD}@pg-postgresql.${NAMESPACE}.svc.cluster.local:5432/leoflow?sslmode=disable
redis:
  url: redis://redis-master.${NAMESPACE}.svc.cluster.local:6379/0

auth:
  jwtSecret: "${JWT_SECRET}"
secretKey: "${SECRET_KEY}"
bootstrap:
  password: "${BOOTSTRAP_PASSWORD}"

image:
  tag: "${IMAGE_TAG}"
migrations:
  image:
    tag: "${IMAGE_TAG}"

replicaCount: 1

# Agent <-> control-plane gRPC TLS (issue #58), wired to cert-manager output.
agentTLS:
  enabled: true
  serverCertSecret: "${SERVER_CERT_SECRET}"
  caConfigMap: "${CA_CONFIGMAP}"

# Small, cheap durable log volume for the test (chart default is 50Gi).
logs:
  persistence:
    enabled: true
    size: ${LOGS_PVC_SIZE}
EOF
  chmod 600 "$VALUES_LOCAL"
  log "Initial admin password: ${BOOTSTRAP_PASSWORD}  (also stored in $VALUES_LOCAL)"
fi

# ---- 2. Bitnami Postgres + Redis (ephemeral, no persistence) ---------------
log "Installing Bitnami Postgres (chart major $PG_CHART_VERSION)"
helm upgrade --install pg oci://registry-1.docker.io/bitnamicharts/postgresql \
  --version "$PG_CHART_VERSION" -n "$NAMESPACE" \
  --set auth.username=leoflow \
  --set auth.password="$PG_PASSWORD" \
  --set auth.database=leoflow \
  --set primary.persistence.enabled=false \
  --wait --timeout 5m

log "Installing Bitnami Redis (chart major $REDIS_CHART_VERSION)"
helm upgrade --install redis oci://registry-1.docker.io/bitnamicharts/redis \
  --version "$REDIS_CHART_VERSION" -n "$NAMESPACE" \
  --set auth.enabled=false \
  --set architecture=standalone \
  --set master.persistence.enabled=false \
  --wait --timeout 5m

# ---- 3. Agent-TLS: cert-manager issuer + CA + server cert ------------------
# Two-tier (self-signed root CA -> server leaf) so the CA we hand to task pods
# is a real CA, not a self-signed leaf. dnsNames cover the in-cluster gRPC
# service the agent dials: <release>.<ns>.svc.cluster.local:9091.
log "Creating cert-manager Issuer + CA + server certificate for the agent channel"
kubectl apply -n "$NAMESPACE" -f - <<EOF
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: leoflow-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: leoflow-ca
spec:
  isCA: true
  commonName: leoflow-agent-ca
  secretName: leoflow-ca
  duration: 87600h    # 10y
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: leoflow-selfsigned
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: leoflow-ca-issuer
spec:
  ca:
    secretName: leoflow-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${SERVER_CERT_SECRET}
spec:
  secretName: ${SERVER_CERT_SECRET}
  duration: 8760h     # 1y
  dnsNames:
    - ${RELEASE}
    - ${RELEASE}.${NAMESPACE}
    - ${RELEASE}.${NAMESPACE}.svc
    - ${RELEASE}.${NAMESPACE}.svc.cluster.local
  issuerRef:
    name: leoflow-ca-issuer
    kind: Issuer
EOF

log "Waiting for the server certificate to be issued"
kubectl wait -n "$NAMESPACE" --for=condition=Ready certificate/"$SERVER_CERT_SECRET" --timeout=120s

# ---- 4. Publish the CA as a ConfigMap for task pods ------------------------
# The chart passes this ConfigMap name to the dispatcher; task pods mount its
# ca.crt so the agent verifies the server cert.
log "Publishing CA into ConfigMap '$CA_CONFIGMAP'"
CA_CRT="$(kubectl get secret "$SERVER_CERT_SECRET" -n "$NAMESPACE" -o jsonpath='{.data.ca\.crt}' | base64 -d)"
[ -n "$CA_CRT" ] || die "Could not read ca.crt from $SERVER_CERT_SECRET."
kubectl create configmap "$CA_CONFIGMAP" -n "$NAMESPACE" \
  --from-literal=ca.crt="$CA_CRT" \
  --dry-run=client -o yaml | kubectl apply -f -

# ---- 5. Install Leoflow -----------------------------------------------------
log "Installing Leoflow (release '$RELEASE', image tag $IMAGE_TAG)"
helm upgrade --install "$RELEASE" "$CHART_DIR" \
  -n "$NAMESPACE" \
  -f "$VALUES_LOCAL" \
  --wait --timeout 8m

# ---- 6. Verify --------------------------------------------------------------
log "Rollout status"
kubectl -n "$NAMESPACE" rollout status "deploy/$RELEASE" --timeout=240s
kubectl -n "$NAMESPACE" get pods

cat <<EOF

$(printf '\033[1;32m==> Leoflow Pro installed.\033[0m')

Open the UI:
  kubectl -n $NAMESPACE port-forward svc/$RELEASE 8080:8080
  # then browse http://127.0.0.1:8080/  (login: admin / see $VALUES_LOCAL)

Readiness:
  curl -fsS http://127.0.0.1:8080/readyz

Next (managed datastores): see README "03 — managed datastores (Cloud SQL + Memorystore)".
EOF
