#!/usr/bin/env bash
# Regenerate the ADR list in docs/adrs.md from the H1 title of each
# docs/adr/NNNN-*.md, so the index never drifts from the files. Only the block
# between the markers is generated; the intro above it is preserved.
#
#   scripts/gen-adr-index.sh            # rewrite docs/adrs.md in place
#   scripts/gen-adr-index.sh --check    # exit 1 if docs/adrs.md is stale (CI)
set -euo pipefail
cd "$(dirname "$0")/.."

index="docs/adrs.md"
begin="<!-- BEGIN ADR INDEX (generated by scripts/gen-adr-index.sh — do not edit by hand) -->"
end="<!-- END ADR INDEX -->"

# One bullet per ADR, ordered by filename (which is the ADR number).
list=""
for f in $(printf '%s\n' docs/adr/[0-9]*.md | sort); do
	title=$(sed -n 's/^# //p' "$f" | head -1)
	if [ -z "$title" ]; then
		echo "gen-adr-index: $f has no '# ' title line" >&2
		exit 1
	fi
	list="${list}- [${title}](adr/$(basename "$f"))"$'\n'
done

# Rebuild the file: lines up to and including BEGIN, then the generated list, then
# END and everything after it. Pure bash (portable; BSD awk mangles newlines).
generated=""
skip=0
while IFS= read -r line || [ -n "$line" ]; do
	if [ "$line" = "$begin" ]; then
		generated="${generated}${line}"$'\n'"${list}${end}"$'\n'
		skip=1
		continue
	fi
	if [ "$line" = "$end" ]; then
		skip=0
		continue
	fi
	[ "$skip" = 1 ] && continue
	generated="${generated}${line}"$'\n'
done <"$index"

if [ "${1:-}" = "--check" ]; then
	if ! diff -q <(printf '%s' "$generated") "$index" >/dev/null; then
		echo "docs/adrs.md is out of date — run scripts/gen-adr-index.sh" >&2
		exit 1
	fi
	echo "docs/adrs.md is up to date"
else
	printf '%s' "$generated" >"$index"
	echo "wrote $index"
fi
