// Package config loads Leoflow configuration from defaults, an optional config
// file, and LEOFLOW_* environment variables, with flags taking precedence.
package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/pflag"
	"github.com/spf13/viper"
)

// Default configuration values applied when nothing else sets a key.
const (
	defaultServerURL = "http://localhost:8080"
	defaultLogLevel  = "info"
	defaultParserCmd = "python3 -m leoflow_parser"
)

// flagToKey maps CLI flag names (kebab-case) to configuration keys (snake_case)
// so that a changed flag overrides the corresponding env var and file value.
var flagToKey = map[string]string{
	"server-url": "server_url",
	"log-level":  "log_level",
	"registry":   "registry",
	"parser-cmd": "parser_cmd",
}

// Config holds the developer CLI configuration.
type Config struct {
	// ServerURL is the control plane base URL used by push and auth create-token.
	ServerURL string `mapstructure:"server_url"`
	// LogLevel is reserved for CLI log verbosity (not yet wired).
	LogLevel string `mapstructure:"log_level"`
	// Registry is reserved for the image registry used by image build (ADR 0003).
	Registry string `mapstructure:"registry"`
	// ParserCmd is the command used to invoke the Python parser from compile.
	ParserCmd string `mapstructure:"parser_cmd"`

	// Lite-edition settings written by `leoflow setup` and read by `leoflow lite`.
	// Workspace is the default directory holding the user's DAG projects.
	Workspace string `mapstructure:"workspace"`
	// LiteExecutor is the chosen executor: "subprocess" (local) or "k8s" (mini-cluster).
	LiteExecutor string `mapstructure:"lite_executor"`
	// LitePort is the UI/API port for the Lite control plane.
	LitePort int `mapstructure:"lite_port"`
	// AdminEmail is the Lite admin login created at bootstrap.
	AdminEmail string `mapstructure:"admin_email"`
	// AdminPasswordHash is the bcrypt hash of the generated admin password; the
	// plaintext is shown once at setup and never stored (Lite only).
	AdminPasswordHash string `mapstructure:"admin_password_hash"`
	// JWTSecret is the per-install Lite JWT signing secret, generated by
	// `leoflow setup` (random, 64 hex chars) and persisted alongside the admin
	// hash. Rotating it on every fresh install invalidates browser tokens from a
	// prior install — so a reinstall greets the user with the login screen and
	// the freshly printed credentials actually do something (#121). Empty on
	// legacy installs; the lite runner falls back to the dev-only constant with
	// a warning so the upgrade does not break existing setups.
	JWTSecret string `mapstructure:"jwt_secret"`
}

// DefaultConfigFile returns the default configuration file path,
// ~/.leoflow/config.yaml.
func DefaultConfigFile() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolving home directory: %w", err)
	}
	return filepath.Join(home, ".leoflow", "config.yaml"), nil
}

// Load assembles configuration from defaults, the given file (when non-empty),
// LEOFLOW_* environment variables, and the provided flag set, in increasing
// order of precedence. A nil flag set or empty file path is ignored.
func Load(configFile string, flags *pflag.FlagSet) (*Config, error) {
	v := viper.New()
	v.SetDefault("server_url", defaultServerURL)
	v.SetDefault("log_level", defaultLogLevel)
	v.SetDefault("parser_cmd", defaultParserCmd)
	v.SetDefault("registry", "")

	v.SetEnvPrefix("LEOFLOW")
	v.SetEnvKeyReplacer(strings.NewReplacer("-", "_"))
	v.AutomaticEnv()

	if configFile != "" {
		v.SetConfigFile(configFile)
		if err := v.ReadInConfig(); err != nil {
			return nil, fmt.Errorf("reading config file %q: %w", configFile, err)
		}
	}

	if flags != nil {
		for flagName, key := range flagToKey {
			if f := flags.Lookup(flagName); f != nil {
				if err := v.BindPFlag(key, f); err != nil {
					return nil, fmt.Errorf("binding flag %q: %w", flagName, err)
				}
			}
		}
	}

	var c Config
	if err := v.Unmarshal(&c); err != nil {
		return nil, fmt.Errorf("unmarshaling config: %w", err)
	}
	return &c, nil
}
