// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connections.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countConnections = `-- name: CountConnections :one
SELECT count(*) FROM connections WHERE tenant_id = $1
`

func (q *Queries) CountConnections(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countConnections, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteConnection = `-- name: DeleteConnection :execrows
DELETE FROM connections WHERE tenant_id = $1 AND conn_id = $2
`

type DeleteConnectionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ConnID   string      `json:"conn_id"`
}

func (q *Queries) DeleteConnection(ctx context.Context, arg DeleteConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnection, arg.TenantID, arg.ConnID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConnection = `-- name: GetConnection :one
SELECT conn_id, conn_type, host, conn_schema, login, password, port, extra, description
FROM connections
WHERE tenant_id = $1 AND conn_id = $2
`

type GetConnectionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ConnID   string      `json:"conn_id"`
}

type GetConnectionRow struct {
	ConnID      string  `json:"conn_id"`
	ConnType    string  `json:"conn_type"`
	Host        *string `json:"host"`
	ConnSchema  *string `json:"conn_schema"`
	Login       *string `json:"login"`
	Password    *string `json:"password"`
	Port        *int32  `json:"port"`
	Extra       *string `json:"extra"`
	Description *string `json:"description"`
}

func (q *Queries) GetConnection(ctx context.Context, arg GetConnectionParams) (GetConnectionRow, error) {
	row := q.db.QueryRow(ctx, getConnection, arg.TenantID, arg.ConnID)
	var i GetConnectionRow
	err := row.Scan(
		&i.ConnID,
		&i.ConnType,
		&i.Host,
		&i.ConnSchema,
		&i.Login,
		&i.Password,
		&i.Port,
		&i.Extra,
		&i.Description,
	)
	return i, err
}

const listConnections = `-- name: ListConnections :many
SELECT conn_id, conn_type, host, conn_schema, login, port, extra, description
FROM connections
WHERE tenant_id = $1
ORDER BY conn_id
LIMIT $2 OFFSET $3
`

type ListConnectionsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type ListConnectionsRow struct {
	ConnID      string  `json:"conn_id"`
	ConnType    string  `json:"conn_type"`
	Host        *string `json:"host"`
	ConnSchema  *string `json:"conn_schema"`
	Login       *string `json:"login"`
	Port        *int32  `json:"port"`
	Extra       *string `json:"extra"`
	Description *string `json:"description"`
}

func (q *Queries) ListConnections(ctx context.Context, arg ListConnectionsParams) ([]ListConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listConnections, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConnectionsRow{}
	for rows.Next() {
		var i ListConnectionsRow
		if err := rows.Scan(
			&i.ConnID,
			&i.ConnType,
			&i.Host,
			&i.ConnSchema,
			&i.Login,
			&i.Port,
			&i.Extra,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConnection = `-- name: UpsertConnection :exec
INSERT INTO connections (tenant_id, conn_id, conn_type, host, conn_schema, login, password, port, extra, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (tenant_id, conn_id) DO UPDATE SET
    conn_type = EXCLUDED.conn_type,
    host = EXCLUDED.host,
    conn_schema = EXCLUDED.conn_schema,
    login = EXCLUDED.login,
    password = EXCLUDED.password,
    port = EXCLUDED.port,
    extra = EXCLUDED.extra,
    description = EXCLUDED.description,
    updated_at = now()
`

type UpsertConnectionParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ConnID      string      `json:"conn_id"`
	ConnType    string      `json:"conn_type"`
	Host        *string     `json:"host"`
	ConnSchema  *string     `json:"conn_schema"`
	Login       *string     `json:"login"`
	Password    *string     `json:"password"`
	Port        *int32      `json:"port"`
	Extra       *string     `json:"extra"`
	Description *string     `json:"description"`
}

func (q *Queries) UpsertConnection(ctx context.Context, arg UpsertConnectionParams) error {
	_, err := q.db.Exec(ctx, upsertConnection,
		arg.TenantID,
		arg.ConnID,
		arg.ConnType,
		arg.Host,
		arg.ConnSchema,
		arg.Login,
		arg.Password,
		arg.Port,
		arg.Extra,
		arg.Description,
	)
	return err
}
