// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connections.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countConnections = `-- name: CountConnections :one
SELECT count(*) FROM connections WHERE tenant_id = $1
`

func (q *Queries) CountConnections(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countConnections, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteConnection = `-- name: DeleteConnection :execrows
DELETE FROM connections WHERE tenant_id = $1 AND conn_id = $2
`

type DeleteConnectionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ConnID   string      `json:"conn_id"`
}

func (q *Queries) DeleteConnection(ctx context.Context, arg DeleteConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnection, arg.TenantID, arg.ConnID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const existingConnectionIDs = `-- name: ExistingConnectionIDs :many
SELECT conn_id FROM connections
WHERE tenant_id = $1 AND conn_id = ANY($2::text[])
`

type ExistingConnectionIDsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ConnIds  []string    `json:"conn_ids"`
}

// The subset of the given conn_ids that exist for the tenant. Used to reject a
// DAG that declares an unknown connection at registration (ADR 0055 D6); a name
// absent from the result does not exist.
func (q *Queries) ExistingConnectionIDs(ctx context.Context, arg ExistingConnectionIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, existingConnectionIDs, arg.TenantID, arg.ConnIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var conn_id string
		if err := rows.Scan(&conn_id); err != nil {
			return nil, err
		}
		items = append(items, conn_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConnection = `-- name: GetConnection :one
SELECT conn_id, conn_type, host, conn_schema, login, password, port, extra, description
FROM connections
WHERE tenant_id = $1 AND conn_id = $2
`

type GetConnectionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ConnID   string      `json:"conn_id"`
}

type GetConnectionRow struct {
	ConnID      string  `json:"conn_id"`
	ConnType    string  `json:"conn_type"`
	Host        *string `json:"host"`
	ConnSchema  *string `json:"conn_schema"`
	Login       *string `json:"login"`
	Password    *string `json:"password"`
	Port        *int32  `json:"port"`
	Extra       *string `json:"extra"`
	Description *string `json:"description"`
}

func (q *Queries) GetConnection(ctx context.Context, arg GetConnectionParams) (GetConnectionRow, error) {
	row := q.db.QueryRow(ctx, getConnection, arg.TenantID, arg.ConnID)
	var i GetConnectionRow
	err := row.Scan(
		&i.ConnID,
		&i.ConnType,
		&i.Host,
		&i.ConnSchema,
		&i.Login,
		&i.Password,
		&i.Port,
		&i.Extra,
		&i.Description,
	)
	return i, err
}

const listConnectionSecrets = `-- name: ListConnectionSecrets :many
SELECT conn_id, conn_type, host, conn_schema, login, password, port, extra
FROM connections
WHERE tenant_id = $1
ORDER BY conn_id
`

type ListConnectionSecretsRow struct {
	ConnID     string  `json:"conn_id"`
	ConnType   string  `json:"conn_type"`
	Host       *string `json:"host"`
	ConnSchema *string `json:"conn_schema"`
	Login      *string `json:"login"`
	Password   *string `json:"password"`
	Port       *int32  `json:"port"`
	Extra      *string `json:"extra"`
}

// All of a tenant's connections WITH the encrypted password, for delivering
// credentials to task pods (ADR 0021). Never use this for UI/API responses,
// which must mask the password.
func (q *Queries) ListConnectionSecrets(ctx context.Context, tenantID pgtype.UUID) ([]ListConnectionSecretsRow, error) {
	rows, err := q.db.Query(ctx, listConnectionSecrets, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConnectionSecretsRow{}
	for rows.Next() {
		var i ListConnectionSecretsRow
		if err := rows.Scan(
			&i.ConnID,
			&i.ConnType,
			&i.Host,
			&i.ConnSchema,
			&i.Login,
			&i.Password,
			&i.Port,
			&i.Extra,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectionSecretsScoped = `-- name: ListConnectionSecretsScoped :many
SELECT conn_id, conn_type, host, conn_schema, login, password, port, extra
FROM connections
WHERE tenant_id = $1 AND conn_id = ANY($2::text[])
ORDER BY conn_id
`

type ListConnectionSecretsScopedParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ConnIds  []string    `json:"conn_ids"`
}

type ListConnectionSecretsScopedRow struct {
	ConnID     string  `json:"conn_id"`
	ConnType   string  `json:"conn_type"`
	Host       *string `json:"host"`
	ConnSchema *string `json:"conn_schema"`
	Login      *string `json:"login"`
	Password   *string `json:"password"`
	Port       *int32  `json:"port"`
	Extra      *string `json:"extra"`
}

// The tenant's connections WITH the encrypted password, restricted to the given
// conn_ids and filtered in the query (ADR 0055 D1: scope in the SQL, never
// post-filter the decrypted whole vault). Never use this for UI/API responses,
// which must mask the password. Used under secret_scoping: enforce so a task
// receives only the connections it declared. An empty conn_id set never reaches
// here — the handler returns nothing without a query.
func (q *Queries) ListConnectionSecretsScoped(ctx context.Context, arg ListConnectionSecretsScopedParams) ([]ListConnectionSecretsScopedRow, error) {
	rows, err := q.db.Query(ctx, listConnectionSecretsScoped, arg.TenantID, arg.ConnIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConnectionSecretsScopedRow{}
	for rows.Next() {
		var i ListConnectionSecretsScopedRow
		if err := rows.Scan(
			&i.ConnID,
			&i.ConnType,
			&i.Host,
			&i.ConnSchema,
			&i.Login,
			&i.Password,
			&i.Port,
			&i.Extra,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnections = `-- name: ListConnections :many
SELECT conn_id, conn_type, host, conn_schema, login, port, extra, description
FROM connections
WHERE tenant_id = $1
ORDER BY conn_id
LIMIT $2 OFFSET $3
`

type ListConnectionsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type ListConnectionsRow struct {
	ConnID      string  `json:"conn_id"`
	ConnType    string  `json:"conn_type"`
	Host        *string `json:"host"`
	ConnSchema  *string `json:"conn_schema"`
	Login       *string `json:"login"`
	Port        *int32  `json:"port"`
	Extra       *string `json:"extra"`
	Description *string `json:"description"`
}

func (q *Queries) ListConnections(ctx context.Context, arg ListConnectionsParams) ([]ListConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listConnections, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConnectionsRow{}
	for rows.Next() {
		var i ListConnectionsRow
		if err := rows.Scan(
			&i.ConnID,
			&i.ConnType,
			&i.Host,
			&i.ConnSchema,
			&i.Login,
			&i.Port,
			&i.Extra,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConnection = `-- name: UpsertConnection :exec
INSERT INTO connections (tenant_id, conn_id, conn_type, host, conn_schema, login, password, port, extra, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (tenant_id, conn_id) DO UPDATE SET
    conn_type = EXCLUDED.conn_type,
    host = COALESCE(EXCLUDED.host, connections.host),
    conn_schema = COALESCE(EXCLUDED.conn_schema, connections.conn_schema),
    login = COALESCE(EXCLUDED.login, connections.login),
    password = COALESCE(EXCLUDED.password, connections.password),
    port = COALESCE(EXCLUDED.port, connections.port),
    extra = COALESCE(EXCLUDED.extra, connections.extra),
    description = COALESCE(EXCLUDED.description, connections.description),
    updated_at = now()
`

type UpsertConnectionParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ConnID      string      `json:"conn_id"`
	ConnType    string      `json:"conn_type"`
	Host        *string     `json:"host"`
	ConnSchema  *string     `json:"conn_schema"`
	Login       *string     `json:"login"`
	Password    *string     `json:"password"`
	Port        *int32      `json:"port"`
	Extra       *string     `json:"extra"`
	Description *string     `json:"description"`
}

// Tri-state write (#887): COALESCE(EXCLUDED.col, connections.col) preserves the
// stored value when the param is NULL, overwrites it when the param is a value,
// and clears it when the param is a non-NULL empty string. A NULL param is how a
// partial `set` stays safe — changing only --host must not wipe the (unreadable)
// password — while an explicit empty string now clears a field, and a masked
// secret ("***") is mapped to NULL by the caller so it preserves rather than
// overwrites (#874). conn_type is required on every write, so it is a plain
// overwrite.
func (q *Queries) UpsertConnection(ctx context.Context, arg UpsertConnectionParams) error {
	_, err := q.db.Exec(ctx, upsertConnection,
		arg.TenantID,
		arg.ConnID,
		arg.ConnType,
		arg.Host,
		arg.ConnSchema,
		arg.Login,
		arg.Password,
		arg.Port,
		arg.Extra,
		arg.Description,
	)
	return err
}
