// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package queries

import (
	"context"
)

// iteratorForCreateTaskInstances implements pgx.CopyFromSource.
type iteratorForCreateTaskInstances struct {
	rows                 []CreateTaskInstancesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTaskInstances) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTaskInstances) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TenantID,
		r.rows[0].DagRunID,
		r.rows[0].TaskID,
		r.rows[0].Operator,
		r.rows[0].MaxTries,
		r.rows[0].State,
		r.rows[0].Pool,
		r.rows[0].TryNumber,
	}, nil
}

func (r iteratorForCreateTaskInstances) Err() error {
	return nil
}

// Batched form of CreateTaskInstance: materializes every task of one run in a
// single COPY instead of T INSERT round-trips. The caller supplies one param row
// per task with try_number pinned to 1 (matching CreateTaskInstance's literal)
// and pool carried through so cross-DAG pool occupancy is attributed correctly;
// columns omitted from the list take their table defaults, so the rows are
// byte-identical to the loop — only the statement count changes (T INSERTs → 1 COPY).
func (q *Queries) CreateTaskInstances(ctx context.Context, arg []CreateTaskInstancesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"task_instances"}, []string{"tenant_id", "dag_run_id", "task_id", "operator", "max_tries", "state", "pool", "try_number"}, &iteratorForCreateTaskInstances{rows: arg})
}
