// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package queries

import (
	"context"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO dag_favorites (tenant_id, user_id, dag_id)
SELECT t.id, $1, $2
FROM tenants t
WHERE t.name = $3
ON CONFLICT (tenant_id, user_id, dag_id) DO NOTHING
`

type AddFavoriteParams struct {
	UserID string `json:"user_id"`
	DagID  string `json:"dag_id"`
	Tenant string `json:"tenant"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.DagID, arg.Tenant)
	return err
}

const listFavoriteDagIDs = `-- name: ListFavoriteDagIDs :many
SELECT f.dag_id
FROM dag_favorites f
JOIN tenants t ON t.id = f.tenant_id
WHERE t.name = $1 AND f.user_id = $2
`

type ListFavoriteDagIDsParams struct {
	Tenant string `json:"tenant"`
	UserID string `json:"user_id"`
}

func (q *Queries) ListFavoriteDagIDs(ctx context.Context, arg ListFavoriteDagIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listFavoriteDagIDs, arg.Tenant, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var dag_id string
		if err := rows.Scan(&dag_id); err != nil {
			return nil, err
		}
		items = append(items, dag_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM dag_favorites
WHERE tenant_id = (SELECT id FROM tenants WHERE name = $1)
  AND user_id = $2
  AND dag_id = $3
`

type RemoveFavoriteParams struct {
	Tenant string `json:"tenant"`
	UserID string `json:"user_id"`
	DagID  string `json:"dag_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.Tenant, arg.UserID, arg.DagID)
	return err
}
