// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import_errors.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteImportError = `-- name: DeleteImportError :exec
DELETE FROM import_errors
WHERE tenant_id = (SELECT id FROM tenants WHERE name = $1)
  AND filename = $2
`

type DeleteImportErrorParams struct {
	Tenant   string `json:"tenant"`
	Filename string `json:"filename"`
}

func (q *Queries) DeleteImportError(ctx context.Context, arg DeleteImportErrorParams) error {
	_, err := q.db.Exec(ctx, deleteImportError, arg.Tenant, arg.Filename)
	return err
}

const listImportErrors = `-- name: ListImportErrors :many
SELECT e.id, e.filename, e.stacktrace, e.bundle_name, e.created_at
FROM import_errors e
JOIN tenants t ON t.id = e.tenant_id
WHERE t.name = $1
ORDER BY e.created_at DESC
`

type ListImportErrorsRow struct {
	ID         pgtype.UUID        `json:"id"`
	Filename   string             `json:"filename"`
	Stacktrace string             `json:"stacktrace"`
	BundleName *string            `json:"bundle_name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListImportErrors(ctx context.Context, tenant string) ([]ListImportErrorsRow, error) {
	rows, err := q.db.Query(ctx, listImportErrors, tenant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImportErrorsRow{}
	for rows.Next() {
		var i ListImportErrorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Stacktrace,
			&i.BundleName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertImportError = `-- name: UpsertImportError :exec
INSERT INTO import_errors (tenant_id, filename, stacktrace, bundle_name)
SELECT t.id, $1, $2, $3
FROM tenants t
WHERE t.name = $4
ON CONFLICT (tenant_id, filename)
DO UPDATE SET stacktrace = EXCLUDED.stacktrace,
              bundle_name = EXCLUDED.bundle_name,
              created_at = now()
`

type UpsertImportErrorParams struct {
	Filename   string  `json:"filename"`
	Stacktrace string  `json:"stacktrace"`
	BundleName *string `json:"bundle_name"`
	Tenant     string  `json:"tenant"`
}

func (q *Queries) UpsertImportError(ctx context.Context, arg UpsertImportErrorParams) error {
	_, err := q.db.Exec(ctx, upsertImportError,
		arg.Filename,
		arg.Stacktrace,
		arg.BundleName,
		arg.Tenant,
	)
	return err
}
