// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type DagRunState string

const (
	DagRunStateQueued  DagRunState = "queued"
	DagRunStateRunning DagRunState = "running"
	DagRunStateSuccess DagRunState = "success"
	DagRunStateFailed  DagRunState = "failed"
)

func (e *DagRunState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DagRunState(s)
	case string:
		*e = DagRunState(s)
	default:
		return fmt.Errorf("unsupported scan type for DagRunState: %T", src)
	}
	return nil
}

type NullDagRunState struct {
	DagRunState DagRunState `json:"dag_run_state"`
	Valid       bool        `json:"valid"` // Valid is true if DagRunState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDagRunState) Scan(value interface{}) error {
	if value == nil {
		ns.DagRunState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DagRunState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDagRunState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DagRunState), nil
}

type DagRunTrigger string

const (
	DagRunTriggerScheduled DagRunTrigger = "scheduled"
	DagRunTriggerManual    DagRunTrigger = "manual"
	DagRunTriggerBackfill  DagRunTrigger = "backfill"
	DagRunTriggerDataset   DagRunTrigger = "dataset"
)

func (e *DagRunTrigger) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DagRunTrigger(s)
	case string:
		*e = DagRunTrigger(s)
	default:
		return fmt.Errorf("unsupported scan type for DagRunTrigger: %T", src)
	}
	return nil
}

type NullDagRunTrigger struct {
	DagRunTrigger DagRunTrigger `json:"dag_run_trigger"`
	Valid         bool          `json:"valid"` // Valid is true if DagRunTrigger is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDagRunTrigger) Scan(value interface{}) error {
	if value == nil {
		ns.DagRunTrigger, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DagRunTrigger.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDagRunTrigger) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DagRunTrigger), nil
}

type TaskState string

const (
	TaskStateNone           TaskState = "none"
	TaskStateScheduled      TaskState = "scheduled"
	TaskStateQueued         TaskState = "queued"
	TaskStateRunning        TaskState = "running"
	TaskStateDeferred       TaskState = "deferred"
	TaskStateSuccess        TaskState = "success"
	TaskStateFailed         TaskState = "failed"
	TaskStateSkipped        TaskState = "skipped"
	TaskStateUpstreamFailed TaskState = "upstream_failed"
	TaskStateUpForRetry     TaskState = "up_for_retry"
)

func (e *TaskState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskState(s)
	case string:
		*e = TaskState(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskState: %T", src)
	}
	return nil
}

type NullTaskState struct {
	TaskState TaskState `json:"task_state"`
	Valid     bool      `json:"valid"` // Valid is true if TaskState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskState) Scan(value interface{}) error {
	if value == nil {
		ns.TaskState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskState), nil
}

type AuditLog struct {
	ID           int64              `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Action       string             `json:"action"`
	ResourceType *string            `json:"resource_type"`
	ResourceID   *string            `json:"resource_id"`
	Metadata     []byte             `json:"metadata"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	UserAgent    *string            `json:"user_agent"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
}

type Dag struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	DagID            string             `json:"dag_id"`
	Description      *string            `json:"description"`
	IsPaused         bool               `json:"is_paused"`
	IsActive         bool               `json:"is_active"`
	Owner            *string            `json:"owner"`
	Tags             []string           `json:"tags"`
	Schedule         *string            `json:"schedule"`
	ScheduleTimezone *string            `json:"schedule_timezone"`
	StartDate        pgtype.Timestamptz `json:"start_date"`
	EndDate          pgtype.Timestamptz `json:"end_date"`
	MaxActiveRuns    int32              `json:"max_active_runs"`
	Catchup          bool               `json:"catchup"`
	CurrentVersionID pgtype.UUID        `json:"current_version_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type DagRun struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	DagID             pgtype.UUID        `json:"dag_id"`
	DagVersionID      pgtype.UUID        `json:"dag_version_id"`
	RunID             string             `json:"run_id"`
	LogicalDate       pgtype.Timestamptz `json:"logical_date"`
	DataIntervalStart pgtype.Timestamptz `json:"data_interval_start"`
	DataIntervalEnd   pgtype.Timestamptz `json:"data_interval_end"`
	State             DagRunState        `json:"state"`
	Trigger           DagRunTrigger      `json:"trigger"`
	Conf              []byte             `json:"conf"`
	TriggeredBy       pgtype.UUID        `json:"triggered_by"`
	QueuedAt          pgtype.Timestamptz `json:"queued_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	EndedAt           pgtype.Timestamptz `json:"ended_at"`
	Note              *string            `json:"note"`
}

type DagVersion struct {
	ID             pgtype.UUID        `json:"id"`
	DagID          pgtype.UUID        `json:"dag_id"`
	Version        string             `json:"version"`
	ImageReference string             `json:"image_reference"`
	Spec           []byte             `json:"spec"`
	SpecHash       string             `json:"spec_hash"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Permission struct {
	ID          pgtype.UUID `json:"id"`
	Action      string      `json:"action"`
	Resource    string      `json:"resource"`
	Description *string     `json:"description"`
}

type Replica struct {
	ID              pgtype.UUID        `json:"id"`
	Hostname        string             `json:"hostname"`
	ProcessID       int32              `json:"process_id"`
	Version         string             `json:"version"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	IsLeader        bool               `json:"is_leader"`
	Role            string             `json:"role"`
	Metadata        []byte             `json:"metadata"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RolePermission struct {
	RoleID       pgtype.UUID        `json:"role_id"`
	PermissionID pgtype.UUID        `json:"permission_id"`
	GrantedAt    pgtype.Timestamptz `json:"granted_at"`
}

type SchedulerLoop struct {
	ID             int64              `json:"id"`
	ReplicaID      pgtype.UUID        `json:"replica_id"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	EndedAt        pgtype.Timestamptz `json:"ended_at"`
	DurationMs     int32              `json:"duration_ms"`
	DagsExamined   int32              `json:"dags_examined"`
	RunsCreated    int32              `json:"runs_created"`
	TasksScheduled int32              `json:"tasks_scheduled"`
	Errors         int32              `json:"errors"`
}

type TaskInstance struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	DagRunID        pgtype.UUID        `json:"dag_run_id"`
	TaskID          string             `json:"task_id"`
	MapIndex        int32              `json:"map_index"`
	TryNumber       int32              `json:"try_number"`
	MaxTries        int32              `json:"max_tries"`
	State           TaskState          `json:"state"`
	Pool            *string            `json:"pool"`
	Operator        string             `json:"operator"`
	QueuedAt        pgtype.Timestamptz `json:"queued_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	DurationSeconds *float64           `json:"duration_seconds"`
	PodName         *string            `json:"pod_name"`
	NodeName        *string            `json:"node_name"`
	ExitCode        *int32             `json:"exit_code"`
	ErrorMessage    *string            `json:"error_message"`
	LogUrl          *string            `json:"log_url"`
	Hostname        *string            `json:"hostname"`
	Note            *string            `json:"note"`
}

type TaskStateHistory struct {
	ID             int64              `json:"id"`
	TaskInstanceID pgtype.UUID        `json:"task_instance_id"`
	FromState      *TaskState         `json:"from_state"`
	ToState        TaskState          `json:"to_state"`
	TransitionedAt pgtype.Timestamptz `json:"transitioned_at"`
	Reason         *string            `json:"reason"`
	Actor          *string            `json:"actor"`
}

type Tenant struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	DisplayName *string            `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Email        string             `json:"email"`
	PasswordHash *string            `json:"password_hash"`
	OidcSubject  *string            `json:"oidc_subject"`
	OidcProvider *string            `json:"oidc_provider"`
	IsActive     bool               `json:"is_active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserRole struct {
	UserID    pgtype.UUID        `json:"user_id"`
	RoleID    pgtype.UUID        `json:"role_id"`
	GrantedAt pgtype.Timestamptz `json:"granted_at"`
}

type XcomIndex struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	DagRunID    pgtype.UUID        `json:"dag_run_id"`
	TaskID      string             `json:"task_id"`
	Key         string             `json:"key"`
	RedisKey    string             `json:"redis_key"`
	SizeBytes   int32              `json:"size_bytes"`
	ContentType string             `json:"content_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}
