// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pools.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPools = `-- name: CountPools :one
SELECT count(*) FROM pools WHERE tenant_id = $1
`

func (q *Queries) CountPools(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPools, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePool = `-- name: DeletePool :execrows
DELETE FROM pools WHERE tenant_id = $1 AND name = $2 AND is_default = false
`

type DeletePoolParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
}

// The implicit default pool is never deletable (Airflow parity): the guard is in
// the query so a direct call cannot orphan the fallback pool the gate resolves to.
func (q *Queries) DeletePool(ctx context.Context, arg DeletePoolParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePool, arg.TenantID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPool = `-- name: GetPool :one
SELECT name, slots, description, is_default
FROM pools
WHERE tenant_id = $1 AND name = $2
`

type GetPoolParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
}

type GetPoolRow struct {
	Name        string  `json:"name"`
	Slots       int32   `json:"slots"`
	Description *string `json:"description"`
	IsDefault   bool    `json:"is_default"`
}

func (q *Queries) GetPool(ctx context.Context, arg GetPoolParams) (GetPoolRow, error) {
	row := q.db.QueryRow(ctx, getPool, arg.TenantID, arg.Name)
	var i GetPoolRow
	err := row.Scan(
		&i.Name,
		&i.Slots,
		&i.Description,
		&i.IsDefault,
	)
	return i, err
}

const listPools = `-- name: ListPools :many
SELECT name, slots, description, is_default
FROM pools
WHERE tenant_id = $1
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListPoolsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type ListPoolsRow struct {
	Name        string  `json:"name"`
	Slots       int32   `json:"slots"`
	Description *string `json:"description"`
	IsDefault   bool    `json:"is_default"`
}

func (q *Queries) ListPools(ctx context.Context, arg ListPoolsParams) ([]ListPoolsRow, error) {
	rows, err := q.db.Query(ctx, listPools, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPoolsRow{}
	for rows.Next() {
		var i ListPoolsRow
		if err := rows.Scan(
			&i.Name,
			&i.Slots,
			&i.Description,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const poolBudgets = `-- name: PoolBudgets :many
SELECT tenant_id, name, slots FROM pools
`

type PoolBudgetsRow struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
	Slots    int32       `json:"slots"`
}

// Every named pool's slot cap across all tenants, for the scheduler's per-tick
// cross-DAG admission budget (ADR 0053 Stage 3). Keyed by (tenant_id, name) so a
// pool name is scoped to its tenant. Pro-only: Lite never calls this.
func (q *Queries) PoolBudgets(ctx context.Context) ([]PoolBudgetsRow, error) {
	rows, err := q.db.Query(ctx, poolBudgets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoolBudgetsRow{}
	for rows.Next() {
		var i PoolBudgetsRow
		if err := rows.Scan(&i.TenantID, &i.Name, &i.Slots); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const poolSlotUsage = `-- name: PoolSlotUsage :many
SELECT COALESCE(pool, 'default_pool') AS pool, state, count(*) AS n
FROM task_instances
WHERE tenant_id = $1 AND state IN ('scheduled', 'queued', 'running', 'deferred')
GROUP BY COALESCE(pool, 'default_pool'), state
`

type PoolSlotUsageRow struct {
	Pool  string    `json:"pool"`
	State TaskState `json:"state"`
	N     int64     `json:"n"`
}

// Per-pool occupancy for a tenant: how many of the tenant's task instances sit in
// each non-terminal state, grouped by the instance's pool (a NULL pool is the
// implicit default_pool). Feeds the Airflow PoolResponse occupancy fields; the
// gate itself counts queued+running as the occupied slots.
func (q *Queries) PoolSlotUsage(ctx context.Context, tenantID pgtype.UUID) ([]PoolSlotUsageRow, error) {
	rows, err := q.db.Query(ctx, poolSlotUsage, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoolSlotUsageRow{}
	for rows.Next() {
		var i PoolSlotUsageRow
		if err := rows.Scan(&i.Pool, &i.State, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPool = `-- name: UpsertPool :exec
INSERT INTO pools (tenant_id, name, slots, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, name) DO UPDATE SET
    slots = EXCLUDED.slots,
    description = EXCLUDED.description,
    updated_at = now()
`

type UpsertPoolParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	Name        string      `json:"name"`
	Slots       int32       `json:"slots"`
	Description *string     `json:"description"`
}

func (q *Queries) UpsertPool(ctx context.Context, arg UpsertPoolParams) error {
	_, err := q.db.Exec(ctx, upsertPool,
		arg.TenantID,
		arg.Name,
		arg.Slots,
		arg.Description,
	)
	return err
}
