// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountDags(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	GetDagByDagID(ctx context.Context, arg GetDagByDagIDParams) (Dag, error)
	GetDagVersionByHash(ctx context.Context, arg GetDagVersionByHashParams) (DagVersion, error)
	GetDefaultTenant(ctx context.Context) (GetDefaultTenantRow, error)
	GetTenantByName(ctx context.Context, name string) (GetTenantByNameRow, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error)
	GetUserPermissions(ctx context.Context, userID pgtype.UUID) ([]GetUserPermissionsRow, error)
	GetUserRoles(ctx context.Context, userID pgtype.UUID) ([]string, error)
	InsertDagVersion(ctx context.Context, arg InsertDagVersionParams) (DagVersion, error)
	ListDags(ctx context.Context, arg ListDagsParams) ([]Dag, error)
	SetCurrentDagVersion(ctx context.Context, arg SetCurrentDagVersionParams) error
	SetDagPaused(ctx context.Context, arg SetDagPausedParams) (Dag, error)
	UpsertDag(ctx context.Context, arg UpsertDagParams) (Dag, error)
}

var _ Querier = (*Queries)(nil)
