// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	CountDagRunsByDag(ctx context.Context, dagID pgtype.UUID) (int64, error)
	CountDags(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountUsers(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateDagRun(ctx context.Context, arg CreateDagRunParams) (DagRun, error)
	CreateScheduledRunByDagID(ctx context.Context, arg CreateScheduledRunByDagIDParams) error
	CreateTaskInstance(ctx context.Context, arg CreateTaskInstanceParams) (TaskInstance, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error)
	GetDagByDagID(ctx context.Context, arg GetDagByDagIDParams) (Dag, error)
	GetDagRun(ctx context.Context, arg GetDagRunParams) (DagRun, error)
	GetDagRunByID(ctx context.Context, id pgtype.UUID) (DagRun, error)
	GetDagVersionByHash(ctx context.Context, arg GetDagVersionByHashParams) (DagVersion, error)
	GetDagVersionByID(ctx context.Context, id pgtype.UUID) (DagVersion, error)
	GetDefaultTenant(ctx context.Context) (GetDefaultTenantRow, error)
	GetRoleByName(ctx context.Context, arg GetRoleByNameParams) (pgtype.UUID, error)
	GetTenantByName(ctx context.Context, name string) (GetTenantByNameRow, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error)
	GetUserPermissions(ctx context.Context, userID pgtype.UUID) ([]GetUserPermissionsRow, error)
	GetUserRoles(ctx context.Context, userID pgtype.UUID) ([]string, error)
	InsertDagVersion(ctx context.Context, arg InsertDagVersionParams) (DagVersion, error)
	ListActiveDagRuns(ctx context.Context) ([]DagRun, error)
	ListDagRunsByDag(ctx context.Context, arg ListDagRunsByDagParams) ([]DagRun, error)
	ListDags(ctx context.Context, arg ListDagsParams) ([]Dag, error)
	ListScheduledDags(ctx context.Context) ([]ListScheduledDagsRow, error)
	ListTaskInstancesByRun(ctx context.Context, dagRunID pgtype.UUID) ([]TaskInstance, error)
	ResetTaskInstanceToNone(ctx context.Context, arg ResetTaskInstanceToNoneParams) error
	SetCurrentDagVersion(ctx context.Context, arg SetCurrentDagVersionParams) error
	SetDagPaused(ctx context.Context, arg SetDagPausedParams) (Dag, error)
	UpdateDagRunState(ctx context.Context, arg UpdateDagRunStateParams) (DagRun, error)
	UpdateTaskInstanceState(ctx context.Context, arg UpdateTaskInstanceStateParams) (TaskInstance, error)
	UpdateTaskInstanceStateByRunTask(ctx context.Context, arg UpdateTaskInstanceStateByRunTaskParams) error
	UpsertDag(ctx context.Context, arg UpsertDagParams) (Dag, error)
}

var _ Querier = (*Queries)(nil)
