// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDagRunStatesInWindow = `-- name: CountDagRunStatesInWindow :many
SELECT r.state AS state, count(*) AS n
FROM dag_runs r
JOIN dags d ON d.id = r.dag_id
WHERE d.tenant_id = $1 AND r.logical_date >= $2 AND r.logical_date <= $3
GROUP BY r.state
`

type CountDagRunStatesInWindowParams struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	LogicalDate   pgtype.Timestamptz `json:"logical_date"`
	LogicalDate_2 pgtype.Timestamptz `json:"logical_date_2"`
}

type CountDagRunStatesInWindowRow struct {
	State DagRunState `json:"state"`
	N     int64       `json:"n"`
}

func (q *Queries) CountDagRunStatesInWindow(ctx context.Context, arg CountDagRunStatesInWindowParams) ([]CountDagRunStatesInWindowRow, error) {
	rows, err := q.db.Query(ctx, countDagRunStatesInWindow, arg.TenantID, arg.LogicalDate, arg.LogicalDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDagRunStatesInWindowRow{}
	for rows.Next() {
		var i CountDagRunStatesInWindowRow
		if err := rows.Scan(&i.State, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDagRunsByDag = `-- name: CountDagRunsByDag :one
SELECT count(*) FROM dag_runs WHERE dag_id = $1
`

func (q *Queries) CountDagRunsByDag(ctx context.Context, dagID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDagRunsByDag, dagID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDagsByLatestRunState = `-- name: CountDagsByLatestRunState :many
SELECT lr.state AS state, count(*) AS n
FROM (
    SELECT DISTINCT ON (r.dag_id) r.state
    FROM dag_runs r
    JOIN dags d ON d.id = r.dag_id
    WHERE d.tenant_id = $1
    ORDER BY r.dag_id, r.logical_date DESC
) lr
GROUP BY lr.state
`

type CountDagsByLatestRunStateRow struct {
	State DagRunState `json:"state"`
	N     int64       `json:"n"`
}

func (q *Queries) CountDagsByLatestRunState(ctx context.Context, tenantID pgtype.UUID) ([]CountDagsByLatestRunStateRow, error) {
	rows, err := q.db.Query(ctx, countDagsByLatestRunState, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDagsByLatestRunStateRow{}
	for rows.Next() {
		var i CountDagsByLatestRunStateRow
		if err := rows.Scan(&i.State, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTaskInstanceStatesInWindow = `-- name: CountTaskInstanceStatesInWindow :many
SELECT ti.state AS state, count(*) AS n
FROM task_instances ti
JOIN dag_runs r ON r.id = ti.dag_run_id
JOIN dags d ON d.id = r.dag_id
WHERE d.tenant_id = $1 AND r.logical_date >= $2 AND r.logical_date <= $3
GROUP BY ti.state
`

type CountTaskInstanceStatesInWindowParams struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	LogicalDate   pgtype.Timestamptz `json:"logical_date"`
	LogicalDate_2 pgtype.Timestamptz `json:"logical_date_2"`
}

type CountTaskInstanceStatesInWindowRow struct {
	State TaskState `json:"state"`
	N     int64     `json:"n"`
}

func (q *Queries) CountTaskInstanceStatesInWindow(ctx context.Context, arg CountTaskInstanceStatesInWindowParams) ([]CountTaskInstanceStatesInWindowRow, error) {
	rows, err := q.db.Query(ctx, countTaskInstanceStatesInWindow, arg.TenantID, arg.LogicalDate, arg.LogicalDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountTaskInstanceStatesInWindowRow{}
	for rows.Next() {
		var i CountTaskInstanceStatesInWindowRow
		if err := rows.Scan(&i.State, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDagRun = `-- name: CreateDagRun :one
INSERT INTO dag_runs (tenant_id, dag_id, dag_version_id, run_id, logical_date, state, trigger, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, dag_id, dag_version_id, run_id, logical_date, data_interval_start, data_interval_end, state, trigger, conf, triggered_by, queued_at, started_at, ended_at, note
`

type CreateDagRunParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	DagID        pgtype.UUID        `json:"dag_id"`
	DagVersionID pgtype.UUID        `json:"dag_version_id"`
	RunID        string             `json:"run_id"`
	LogicalDate  pgtype.Timestamptz `json:"logical_date"`
	State        DagRunState        `json:"state"`
	Trigger      DagRunTrigger      `json:"trigger"`
	Note         *string            `json:"note"`
}

func (q *Queries) CreateDagRun(ctx context.Context, arg CreateDagRunParams) (DagRun, error) {
	row := q.db.QueryRow(ctx, createDagRun,
		arg.TenantID,
		arg.DagID,
		arg.DagVersionID,
		arg.RunID,
		arg.LogicalDate,
		arg.State,
		arg.Trigger,
		arg.Note,
	)
	var i DagRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DagID,
		&i.DagVersionID,
		&i.RunID,
		&i.LogicalDate,
		&i.DataIntervalStart,
		&i.DataIntervalEnd,
		&i.State,
		&i.Trigger,
		&i.Conf,
		&i.TriggeredBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Note,
	)
	return i, err
}

const createScheduledRunByDagID = `-- name: CreateScheduledRunByDagID :exec
INSERT INTO dag_runs (tenant_id, dag_id, dag_version_id, run_id, logical_date, state, trigger)
SELECT d.tenant_id, d.id, d.current_version_id, $1, $2, 'queued', 'scheduled'
FROM dags d
JOIN tenants t ON t.id = d.tenant_id
WHERE t.name = $3 AND d.dag_id = $4 AND d.current_version_id IS NOT NULL
ON CONFLICT (dag_id, run_id) DO NOTHING
`

type CreateScheduledRunByDagIDParams struct {
	RunID       string             `json:"run_id"`
	LogicalDate pgtype.Timestamptz `json:"logical_date"`
	Tenant      string             `json:"tenant"`
	DagID       string             `json:"dag_id"`
}

func (q *Queries) CreateScheduledRunByDagID(ctx context.Context, arg CreateScheduledRunByDagIDParams) error {
	_, err := q.db.Exec(ctx, createScheduledRunByDagID,
		arg.RunID,
		arg.LogicalDate,
		arg.Tenant,
		arg.DagID,
	)
	return err
}

const createTaskInstance = `-- name: CreateTaskInstance :one
INSERT INTO task_instances (tenant_id, dag_run_id, task_id, operator, max_tries, state)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, dag_run_id, task_id, map_index, try_number, max_tries, state, pool, operator, queued_at, started_at, ended_at, duration_seconds, pod_name, node_name, exit_code, error_message, log_url, hostname, note
`

type CreateTaskInstanceParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	DagRunID pgtype.UUID `json:"dag_run_id"`
	TaskID   string      `json:"task_id"`
	Operator string      `json:"operator"`
	MaxTries int32       `json:"max_tries"`
	State    TaskState   `json:"state"`
}

func (q *Queries) CreateTaskInstance(ctx context.Context, arg CreateTaskInstanceParams) (TaskInstance, error) {
	row := q.db.QueryRow(ctx, createTaskInstance,
		arg.TenantID,
		arg.DagRunID,
		arg.TaskID,
		arg.Operator,
		arg.MaxTries,
		arg.State,
	)
	var i TaskInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DagRunID,
		&i.TaskID,
		&i.MapIndex,
		&i.TryNumber,
		&i.MaxTries,
		&i.State,
		&i.Pool,
		&i.Operator,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.PodName,
		&i.NodeName,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.LogUrl,
		&i.Hostname,
		&i.Note,
	)
	return i, err
}

const failTaskInstanceIfActive = `-- name: FailTaskInstanceIfActive :exec
UPDATE task_instances
SET state = 'failed', ended_at = now(), error_message = $2
WHERE id = $1 AND state IN ('scheduled', 'queued', 'running')
`

type FailTaskInstanceIfActiveParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage *string     `json:"error_message"`
}

func (q *Queries) FailTaskInstanceIfActive(ctx context.Context, arg FailTaskInstanceIfActiveParams) error {
	_, err := q.db.Exec(ctx, failTaskInstanceIfActive, arg.ID, arg.ErrorMessage)
	return err
}

const getDagRun = `-- name: GetDagRun :one
SELECT id, tenant_id, dag_id, dag_version_id, run_id, logical_date, data_interval_start, data_interval_end, state, trigger, conf, triggered_by, queued_at, started_at, ended_at, note FROM dag_runs WHERE dag_id = $1 AND run_id = $2
`

type GetDagRunParams struct {
	DagID pgtype.UUID `json:"dag_id"`
	RunID string      `json:"run_id"`
}

func (q *Queries) GetDagRun(ctx context.Context, arg GetDagRunParams) (DagRun, error) {
	row := q.db.QueryRow(ctx, getDagRun, arg.DagID, arg.RunID)
	var i DagRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DagID,
		&i.DagVersionID,
		&i.RunID,
		&i.LogicalDate,
		&i.DataIntervalStart,
		&i.DataIntervalEnd,
		&i.State,
		&i.Trigger,
		&i.Conf,
		&i.TriggeredBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Note,
	)
	return i, err
}

const getDagRunByID = `-- name: GetDagRunByID :one
SELECT id, tenant_id, dag_id, dag_version_id, run_id, logical_date, data_interval_start, data_interval_end, state, trigger, conf, triggered_by, queued_at, started_at, ended_at, note FROM dag_runs WHERE id = $1
`

func (q *Queries) GetDagRunByID(ctx context.Context, id pgtype.UUID) (DagRun, error) {
	row := q.db.QueryRow(ctx, getDagRunByID, id)
	var i DagRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DagID,
		&i.DagVersionID,
		&i.RunID,
		&i.LogicalDate,
		&i.DataIntervalStart,
		&i.DataIntervalEnd,
		&i.State,
		&i.Trigger,
		&i.Conf,
		&i.TriggeredBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Note,
	)
	return i, err
}

const getDagVersionByID = `-- name: GetDagVersionByID :one
SELECT id, dag_id, version, image_reference, spec, spec_hash, created_by, created_at FROM dag_versions WHERE id = $1
`

func (q *Queries) GetDagVersionByID(ctx context.Context, id pgtype.UUID) (DagVersion, error) {
	row := q.db.QueryRow(ctx, getDagVersionByID, id)
	var i DagVersion
	err := row.Scan(
		&i.ID,
		&i.DagID,
		&i.Version,
		&i.ImageReference,
		&i.Spec,
		&i.SpecHash,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const latestRunsForDags = `-- name: LatestRunsForDags :many
SELECT d.dag_id AS dag_id_text,
       r.run_id, r.logical_date, r.state, r.trigger, r.queued_at, r.started_at, r.ended_at
FROM dags d
JOIN LATERAL (
    SELECT dr.run_id, dr.logical_date, dr.state, dr.trigger, dr.queued_at, dr.started_at, dr.ended_at
    FROM dag_runs dr
    WHERE dr.dag_id = d.id
    ORDER BY dr.logical_date DESC
    LIMIT $3
) r ON true
WHERE d.tenant_id = $1 AND d.dag_id = ANY($2::text[])
ORDER BY d.dag_id, r.logical_date DESC
`

type LatestRunsForDagsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Column2  []string    `json:"column_2"`
	Limit    int32       `json:"limit"`
}

type LatestRunsForDagsRow struct {
	DagIDText   string             `json:"dag_id_text"`
	RunID       string             `json:"run_id"`
	LogicalDate pgtype.Timestamptz `json:"logical_date"`
	State       DagRunState        `json:"state"`
	Trigger     DagRunTrigger      `json:"trigger"`
	QueuedAt    pgtype.Timestamptz `json:"queued_at"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) LatestRunsForDags(ctx context.Context, arg LatestRunsForDagsParams) ([]LatestRunsForDagsRow, error) {
	rows, err := q.db.Query(ctx, latestRunsForDags, arg.TenantID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestRunsForDagsRow{}
	for rows.Next() {
		var i LatestRunsForDagsRow
		if err := rows.Scan(
			&i.DagIDText,
			&i.RunID,
			&i.LogicalDate,
			&i.State,
			&i.Trigger,
			&i.QueuedAt,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveDagRuns = `-- name: ListActiveDagRuns :many
SELECT id, tenant_id, dag_id, dag_version_id, run_id, logical_date, data_interval_start, data_interval_end, state, trigger, conf, triggered_by, queued_at, started_at, ended_at, note FROM dag_runs
WHERE state IN ('queued', 'running')
ORDER BY queued_at
`

func (q *Queries) ListActiveDagRuns(ctx context.Context) ([]DagRun, error) {
	rows, err := q.db.Query(ctx, listActiveDagRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DagRun{}
	for rows.Next() {
		var i DagRun
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DagID,
			&i.DagVersionID,
			&i.RunID,
			&i.LogicalDate,
			&i.DataIntervalStart,
			&i.DataIntervalEnd,
			&i.State,
			&i.Trigger,
			&i.Conf,
			&i.TriggeredBy,
			&i.QueuedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDagRunsByDag = `-- name: ListDagRunsByDag :many
SELECT id, tenant_id, dag_id, dag_version_id, run_id, logical_date, data_interval_start, data_interval_end, state, trigger, conf, triggered_by, queued_at, started_at, ended_at, note FROM dag_runs
WHERE dag_id = $1
ORDER BY logical_date DESC
LIMIT $2 OFFSET $3
`

type ListDagRunsByDagParams struct {
	DagID  pgtype.UUID `json:"dag_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListDagRunsByDag(ctx context.Context, arg ListDagRunsByDagParams) ([]DagRun, error) {
	rows, err := q.db.Query(ctx, listDagRunsByDag, arg.DagID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DagRun{}
	for rows.Next() {
		var i DagRun
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DagID,
			&i.DagVersionID,
			&i.RunID,
			&i.LogicalDate,
			&i.DataIntervalStart,
			&i.DataIntervalEnd,
			&i.State,
			&i.Trigger,
			&i.Conf,
			&i.TriggeredBy,
			&i.QueuedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledDags = `-- name: ListScheduledDags :many
SELECT d.dag_id, d.schedule,
  (SELECT max(dr.logical_date) FROM dag_runs dr WHERE dr.dag_id = d.id) AS last_logical
FROM dags d
WHERE d.is_active = true AND d.is_paused = false
  AND d.schedule IS NOT NULL AND d.current_version_id IS NOT NULL
`

type ListScheduledDagsRow struct {
	DagID       string      `json:"dag_id"`
	Schedule    *string     `json:"schedule"`
	LastLogical interface{} `json:"last_logical"`
}

func (q *Queries) ListScheduledDags(ctx context.Context) ([]ListScheduledDagsRow, error) {
	rows, err := q.db.Query(ctx, listScheduledDags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduledDagsRow{}
	for rows.Next() {
		var i ListScheduledDagsRow
		if err := rows.Scan(&i.DagID, &i.Schedule, &i.LastLogical); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskInstancesByRun = `-- name: ListTaskInstancesByRun :many
SELECT id, tenant_id, dag_run_id, task_id, map_index, try_number, max_tries, state, pool, operator, queued_at, started_at, ended_at, duration_seconds, pod_name, node_name, exit_code, error_message, log_url, hostname, note FROM task_instances
WHERE dag_run_id = $1
ORDER BY task_id
`

func (q *Queries) ListTaskInstancesByRun(ctx context.Context, dagRunID pgtype.UUID) ([]TaskInstance, error) {
	rows, err := q.db.Query(ctx, listTaskInstancesByRun, dagRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskInstance{}
	for rows.Next() {
		var i TaskInstance
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DagRunID,
			&i.TaskID,
			&i.MapIndex,
			&i.TryNumber,
			&i.MaxTries,
			&i.State,
			&i.Pool,
			&i.Operator,
			&i.QueuedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.PodName,
			&i.NodeName,
			&i.ExitCode,
			&i.ErrorMessage,
			&i.LogUrl,
			&i.Hostname,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportTaskResult = `-- name: ReportTaskResult :exec
UPDATE task_instances
SET state = $3::task_state,
    exit_code = $4,
    error_message = $5,
    started_at = CASE WHEN $3::task_state = 'running' AND started_at IS NULL THEN now() ELSE started_at END,
    ended_at = CASE WHEN $3::task_state IN ('success', 'failed', 'skipped', 'upstream_failed') THEN now() ELSE ended_at END,
    duration_seconds = CASE WHEN $3::task_state IN ('success', 'failed') AND started_at IS NOT NULL
        THEN EXTRACT(EPOCH FROM (now() - started_at)) ELSE duration_seconds END
WHERE dag_run_id = $1 AND task_id = $2
`

type ReportTaskResultParams struct {
	DagRunID     pgtype.UUID `json:"dag_run_id"`
	TaskID       string      `json:"task_id"`
	Column3      TaskState   `json:"column_3"`
	ExitCode     *int32      `json:"exit_code"`
	ErrorMessage *string     `json:"error_message"`
}

// $3 is cast to task_state in every usage: without the cast Postgres deduces an
// enum type from `state = $3` but text from the literal comparisons below and
// rejects the parameter as having inconsistent types (SQLSTATE 42P08). The pod
// agent path is the first to exercise this query end-to-end.
func (q *Queries) ReportTaskResult(ctx context.Context, arg ReportTaskResultParams) error {
	_, err := q.db.Exec(ctx, reportTaskResult,
		arg.DagRunID,
		arg.TaskID,
		arg.Column3,
		arg.ExitCode,
		arg.ErrorMessage,
	)
	return err
}

const resetAllFailedTaskInstances = `-- name: ResetAllFailedTaskInstances :execrows
UPDATE task_instances
SET state = 'none', started_at = NULL, ended_at = NULL, try_number = try_number + 1
WHERE dag_run_id = $1
  AND state IN ('failed', 'upstream_failed', 'up_for_retry')
`

func (q *Queries) ResetAllFailedTaskInstances(ctx context.Context, dagRunID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, resetAllFailedTaskInstances, dagRunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetFailedTaskInstance = `-- name: ResetFailedTaskInstance :execrows
UPDATE task_instances
SET state = 'none', started_at = NULL, ended_at = NULL, try_number = try_number + 1
WHERE dag_run_id = $1 AND task_id = $2
  AND state IN ('failed', 'upstream_failed', 'up_for_retry')
`

type ResetFailedTaskInstanceParams struct {
	DagRunID pgtype.UUID `json:"dag_run_id"`
	TaskID   string      `json:"task_id"`
}

func (q *Queries) ResetFailedTaskInstance(ctx context.Context, arg ResetFailedTaskInstanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetFailedTaskInstance, arg.DagRunID, arg.TaskID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetTaskInstanceToNone = `-- name: ResetTaskInstanceToNone :exec
UPDATE task_instances
SET state = 'none', started_at = NULL, ended_at = NULL, try_number = try_number + 1
WHERE dag_run_id = $1 AND task_id = $2
`

type ResetTaskInstanceToNoneParams struct {
	DagRunID pgtype.UUID `json:"dag_run_id"`
	TaskID   string      `json:"task_id"`
}

func (q *Queries) ResetTaskInstanceToNone(ctx context.Context, arg ResetTaskInstanceToNoneParams) error {
	_, err := q.db.Exec(ctx, resetTaskInstanceToNone, arg.DagRunID, arg.TaskID)
	return err
}

const resolveRunRef = `-- name: ResolveRunRef :one
SELECT t.id AS tenant_id, dr.id AS dag_run_id
FROM dag_runs dr
JOIN dags d ON d.id = dr.dag_id
JOIN tenants t ON t.id = d.tenant_id
WHERE t.name = $1 AND d.dag_id = $2 AND dr.run_id = $3
`

type ResolveRunRefParams struct {
	Name  string `json:"name"`
	DagID string `json:"dag_id"`
	RunID string `json:"run_id"`
}

type ResolveRunRefRow struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	DagRunID pgtype.UUID `json:"dag_run_id"`
}

func (q *Queries) ResolveRunRef(ctx context.Context, arg ResolveRunRefParams) (ResolveRunRefRow, error) {
	row := q.db.QueryRow(ctx, resolveRunRef, arg.Name, arg.DagID, arg.RunID)
	var i ResolveRunRefRow
	err := row.Scan(&i.TenantID, &i.DagRunID)
	return i, err
}

const setTaskInstanceNote = `-- name: SetTaskInstanceNote :exec
UPDATE task_instances
SET note = $3
WHERE dag_run_id = $1 AND task_id = $2
`

type SetTaskInstanceNoteParams struct {
	DagRunID pgtype.UUID `json:"dag_run_id"`
	TaskID   string      `json:"task_id"`
	Note     *string     `json:"note"`
}

func (q *Queries) SetTaskInstanceNote(ctx context.Context, arg SetTaskInstanceNoteParams) error {
	_, err := q.db.Exec(ctx, setTaskInstanceNote, arg.DagRunID, arg.TaskID, arg.Note)
	return err
}

const taskInstancesForDagRuns = `-- name: TaskInstancesForDagRuns :many
SELECT dr.run_id, ti.task_id, ti.try_number, ti.state,
       ti.started_at, ti.ended_at
FROM task_instances ti
JOIN dag_runs dr ON dr.id = ti.dag_run_id
JOIN dags d ON d.id = dr.dag_id
WHERE d.tenant_id = $1 AND d.dag_id = $2 AND dr.run_id = ANY($3::text[])
ORDER BY dr.run_id, ti.task_id, ti.try_number
`

type TaskInstancesForDagRunsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	DagID    string      `json:"dag_id"`
	Column3  []string    `json:"column_3"`
}

type TaskInstancesForDagRunsRow struct {
	RunID     string             `json:"run_id"`
	TaskID    string             `json:"task_id"`
	TryNumber int32              `json:"try_number"`
	State     TaskState          `json:"state"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	EndedAt   pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) TaskInstancesForDagRuns(ctx context.Context, arg TaskInstancesForDagRunsParams) ([]TaskInstancesForDagRunsRow, error) {
	rows, err := q.db.Query(ctx, taskInstancesForDagRuns, arg.TenantID, arg.DagID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskInstancesForDagRunsRow{}
	for rows.Next() {
		var i TaskInstancesForDagRunsRow
		if err := rows.Scan(
			&i.RunID,
			&i.TaskID,
			&i.TryNumber,
			&i.State,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDagRunState = `-- name: UpdateDagRunState :one
UPDATE dag_runs
SET state = $2, started_at = $3, ended_at = $4
WHERE id = $1
RETURNING id, tenant_id, dag_id, dag_version_id, run_id, logical_date, data_interval_start, data_interval_end, state, trigger, conf, triggered_by, queued_at, started_at, ended_at, note
`

type UpdateDagRunStateParams struct {
	ID        pgtype.UUID        `json:"id"`
	State     DagRunState        `json:"state"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	EndedAt   pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) UpdateDagRunState(ctx context.Context, arg UpdateDagRunStateParams) (DagRun, error) {
	row := q.db.QueryRow(ctx, updateDagRunState,
		arg.ID,
		arg.State,
		arg.StartedAt,
		arg.EndedAt,
	)
	var i DagRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DagID,
		&i.DagVersionID,
		&i.RunID,
		&i.LogicalDate,
		&i.DataIntervalStart,
		&i.DataIntervalEnd,
		&i.State,
		&i.Trigger,
		&i.Conf,
		&i.TriggeredBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Note,
	)
	return i, err
}

const updateTaskInstanceState = `-- name: UpdateTaskInstanceState :one
UPDATE task_instances
SET state = $2, started_at = $3, ended_at = $4
WHERE id = $1
RETURNING id, tenant_id, dag_run_id, task_id, map_index, try_number, max_tries, state, pool, operator, queued_at, started_at, ended_at, duration_seconds, pod_name, node_name, exit_code, error_message, log_url, hostname, note
`

type UpdateTaskInstanceStateParams struct {
	ID        pgtype.UUID        `json:"id"`
	State     TaskState          `json:"state"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	EndedAt   pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) UpdateTaskInstanceState(ctx context.Context, arg UpdateTaskInstanceStateParams) (TaskInstance, error) {
	row := q.db.QueryRow(ctx, updateTaskInstanceState,
		arg.ID,
		arg.State,
		arg.StartedAt,
		arg.EndedAt,
	)
	var i TaskInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DagRunID,
		&i.TaskID,
		&i.MapIndex,
		&i.TryNumber,
		&i.MaxTries,
		&i.State,
		&i.Pool,
		&i.Operator,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.PodName,
		&i.NodeName,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.LogUrl,
		&i.Hostname,
		&i.Note,
	)
	return i, err
}

const updateTaskInstanceStateByRunTask = `-- name: UpdateTaskInstanceStateByRunTask :exec
UPDATE task_instances SET state = $3
WHERE dag_run_id = $1 AND task_id = $2
`

type UpdateTaskInstanceStateByRunTaskParams struct {
	DagRunID pgtype.UUID `json:"dag_run_id"`
	TaskID   string      `json:"task_id"`
	State    TaskState   `json:"state"`
}

func (q *Queries) UpdateTaskInstanceStateByRunTask(ctx context.Context, arg UpdateTaskInstanceStateByRunTaskParams) error {
	_, err := q.db.Exec(ctx, updateTaskInstanceStateByRunTask, arg.DagRunID, arg.TaskID, arg.State)
	return err
}
