// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDagRunsByDag = `-- name: CountDagRunsByDag :one
SELECT count(*) FROM dag_runs WHERE dag_id = $1
`

func (q *Queries) CountDagRunsByDag(ctx context.Context, dagID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDagRunsByDag, dagID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDagRun = `-- name: CreateDagRun :one
INSERT INTO dag_runs (tenant_id, dag_id, dag_version_id, run_id, logical_date, state, trigger, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, dag_id, dag_version_id, run_id, logical_date, data_interval_start, data_interval_end, state, trigger, conf, triggered_by, queued_at, started_at, ended_at, note
`

type CreateDagRunParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	DagID        pgtype.UUID        `json:"dag_id"`
	DagVersionID pgtype.UUID        `json:"dag_version_id"`
	RunID        string             `json:"run_id"`
	LogicalDate  pgtype.Timestamptz `json:"logical_date"`
	State        DagRunState        `json:"state"`
	Trigger      DagRunTrigger      `json:"trigger"`
	Note         *string            `json:"note"`
}

func (q *Queries) CreateDagRun(ctx context.Context, arg CreateDagRunParams) (DagRun, error) {
	row := q.db.QueryRow(ctx, createDagRun,
		arg.TenantID,
		arg.DagID,
		arg.DagVersionID,
		arg.RunID,
		arg.LogicalDate,
		arg.State,
		arg.Trigger,
		arg.Note,
	)
	var i DagRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DagID,
		&i.DagVersionID,
		&i.RunID,
		&i.LogicalDate,
		&i.DataIntervalStart,
		&i.DataIntervalEnd,
		&i.State,
		&i.Trigger,
		&i.Conf,
		&i.TriggeredBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Note,
	)
	return i, err
}

const createScheduledRunByDagID = `-- name: CreateScheduledRunByDagID :exec
INSERT INTO dag_runs (tenant_id, dag_id, dag_version_id, run_id, logical_date, state, trigger)
SELECT d.tenant_id, d.id, d.current_version_id, $1, $2, 'queued', 'scheduled'
FROM dags d
JOIN tenants t ON t.id = d.tenant_id
WHERE t.name = $3 AND d.dag_id = $4 AND d.current_version_id IS NOT NULL
ON CONFLICT (dag_id, run_id) DO NOTHING
`

type CreateScheduledRunByDagIDParams struct {
	RunID       string             `json:"run_id"`
	LogicalDate pgtype.Timestamptz `json:"logical_date"`
	Tenant      string             `json:"tenant"`
	DagID       string             `json:"dag_id"`
}

func (q *Queries) CreateScheduledRunByDagID(ctx context.Context, arg CreateScheduledRunByDagIDParams) error {
	_, err := q.db.Exec(ctx, createScheduledRunByDagID,
		arg.RunID,
		arg.LogicalDate,
		arg.Tenant,
		arg.DagID,
	)
	return err
}

const createTaskInstance = `-- name: CreateTaskInstance :one
INSERT INTO task_instances (tenant_id, dag_run_id, task_id, operator, max_tries, state)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, dag_run_id, task_id, map_index, try_number, max_tries, state, pool, operator, queued_at, started_at, ended_at, duration_seconds, pod_name, node_name, exit_code, error_message, log_url, hostname
`

type CreateTaskInstanceParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	DagRunID pgtype.UUID `json:"dag_run_id"`
	TaskID   string      `json:"task_id"`
	Operator string      `json:"operator"`
	MaxTries int32       `json:"max_tries"`
	State    TaskState   `json:"state"`
}

func (q *Queries) CreateTaskInstance(ctx context.Context, arg CreateTaskInstanceParams) (TaskInstance, error) {
	row := q.db.QueryRow(ctx, createTaskInstance,
		arg.TenantID,
		arg.DagRunID,
		arg.TaskID,
		arg.Operator,
		arg.MaxTries,
		arg.State,
	)
	var i TaskInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DagRunID,
		&i.TaskID,
		&i.MapIndex,
		&i.TryNumber,
		&i.MaxTries,
		&i.State,
		&i.Pool,
		&i.Operator,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.PodName,
		&i.NodeName,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.LogUrl,
		&i.Hostname,
	)
	return i, err
}

const getDagRun = `-- name: GetDagRun :one
SELECT id, tenant_id, dag_id, dag_version_id, run_id, logical_date, data_interval_start, data_interval_end, state, trigger, conf, triggered_by, queued_at, started_at, ended_at, note FROM dag_runs WHERE dag_id = $1 AND run_id = $2
`

type GetDagRunParams struct {
	DagID pgtype.UUID `json:"dag_id"`
	RunID string      `json:"run_id"`
}

func (q *Queries) GetDagRun(ctx context.Context, arg GetDagRunParams) (DagRun, error) {
	row := q.db.QueryRow(ctx, getDagRun, arg.DagID, arg.RunID)
	var i DagRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DagID,
		&i.DagVersionID,
		&i.RunID,
		&i.LogicalDate,
		&i.DataIntervalStart,
		&i.DataIntervalEnd,
		&i.State,
		&i.Trigger,
		&i.Conf,
		&i.TriggeredBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Note,
	)
	return i, err
}

const getDagRunByID = `-- name: GetDagRunByID :one
SELECT id, tenant_id, dag_id, dag_version_id, run_id, logical_date, data_interval_start, data_interval_end, state, trigger, conf, triggered_by, queued_at, started_at, ended_at, note FROM dag_runs WHERE id = $1
`

func (q *Queries) GetDagRunByID(ctx context.Context, id pgtype.UUID) (DagRun, error) {
	row := q.db.QueryRow(ctx, getDagRunByID, id)
	var i DagRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DagID,
		&i.DagVersionID,
		&i.RunID,
		&i.LogicalDate,
		&i.DataIntervalStart,
		&i.DataIntervalEnd,
		&i.State,
		&i.Trigger,
		&i.Conf,
		&i.TriggeredBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Note,
	)
	return i, err
}

const getDagVersionByID = `-- name: GetDagVersionByID :one
SELECT id, dag_id, version, image_reference, spec, spec_hash, created_by, created_at FROM dag_versions WHERE id = $1
`

func (q *Queries) GetDagVersionByID(ctx context.Context, id pgtype.UUID) (DagVersion, error) {
	row := q.db.QueryRow(ctx, getDagVersionByID, id)
	var i DagVersion
	err := row.Scan(
		&i.ID,
		&i.DagID,
		&i.Version,
		&i.ImageReference,
		&i.Spec,
		&i.SpecHash,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveDagRuns = `-- name: ListActiveDagRuns :many
SELECT id, tenant_id, dag_id, dag_version_id, run_id, logical_date, data_interval_start, data_interval_end, state, trigger, conf, triggered_by, queued_at, started_at, ended_at, note FROM dag_runs
WHERE state IN ('queued', 'running')
ORDER BY queued_at
`

func (q *Queries) ListActiveDagRuns(ctx context.Context) ([]DagRun, error) {
	rows, err := q.db.Query(ctx, listActiveDagRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DagRun{}
	for rows.Next() {
		var i DagRun
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DagID,
			&i.DagVersionID,
			&i.RunID,
			&i.LogicalDate,
			&i.DataIntervalStart,
			&i.DataIntervalEnd,
			&i.State,
			&i.Trigger,
			&i.Conf,
			&i.TriggeredBy,
			&i.QueuedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDagRunsByDag = `-- name: ListDagRunsByDag :many
SELECT id, tenant_id, dag_id, dag_version_id, run_id, logical_date, data_interval_start, data_interval_end, state, trigger, conf, triggered_by, queued_at, started_at, ended_at, note FROM dag_runs
WHERE dag_id = $1
ORDER BY logical_date DESC
LIMIT $2 OFFSET $3
`

type ListDagRunsByDagParams struct {
	DagID  pgtype.UUID `json:"dag_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListDagRunsByDag(ctx context.Context, arg ListDagRunsByDagParams) ([]DagRun, error) {
	rows, err := q.db.Query(ctx, listDagRunsByDag, arg.DagID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DagRun{}
	for rows.Next() {
		var i DagRun
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DagID,
			&i.DagVersionID,
			&i.RunID,
			&i.LogicalDate,
			&i.DataIntervalStart,
			&i.DataIntervalEnd,
			&i.State,
			&i.Trigger,
			&i.Conf,
			&i.TriggeredBy,
			&i.QueuedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledDags = `-- name: ListScheduledDags :many
SELECT d.dag_id, d.schedule,
  (SELECT max(dr.logical_date) FROM dag_runs dr WHERE dr.dag_id = d.id) AS last_logical
FROM dags d
WHERE d.is_active = true AND d.is_paused = false
  AND d.schedule IS NOT NULL AND d.current_version_id IS NOT NULL
`

type ListScheduledDagsRow struct {
	DagID       string      `json:"dag_id"`
	Schedule    *string     `json:"schedule"`
	LastLogical interface{} `json:"last_logical"`
}

func (q *Queries) ListScheduledDags(ctx context.Context) ([]ListScheduledDagsRow, error) {
	rows, err := q.db.Query(ctx, listScheduledDags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduledDagsRow{}
	for rows.Next() {
		var i ListScheduledDagsRow
		if err := rows.Scan(&i.DagID, &i.Schedule, &i.LastLogical); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskInstancesByRun = `-- name: ListTaskInstancesByRun :many
SELECT id, tenant_id, dag_run_id, task_id, map_index, try_number, max_tries, state, pool, operator, queued_at, started_at, ended_at, duration_seconds, pod_name, node_name, exit_code, error_message, log_url, hostname FROM task_instances
WHERE dag_run_id = $1
ORDER BY task_id
`

func (q *Queries) ListTaskInstancesByRun(ctx context.Context, dagRunID pgtype.UUID) ([]TaskInstance, error) {
	rows, err := q.db.Query(ctx, listTaskInstancesByRun, dagRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskInstance{}
	for rows.Next() {
		var i TaskInstance
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DagRunID,
			&i.TaskID,
			&i.MapIndex,
			&i.TryNumber,
			&i.MaxTries,
			&i.State,
			&i.Pool,
			&i.Operator,
			&i.QueuedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.PodName,
			&i.NodeName,
			&i.ExitCode,
			&i.ErrorMessage,
			&i.LogUrl,
			&i.Hostname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetTaskInstanceToNone = `-- name: ResetTaskInstanceToNone :exec
UPDATE task_instances
SET state = 'none', started_at = NULL, ended_at = NULL, try_number = try_number + 1
WHERE dag_run_id = $1 AND task_id = $2
`

type ResetTaskInstanceToNoneParams struct {
	DagRunID pgtype.UUID `json:"dag_run_id"`
	TaskID   string      `json:"task_id"`
}

func (q *Queries) ResetTaskInstanceToNone(ctx context.Context, arg ResetTaskInstanceToNoneParams) error {
	_, err := q.db.Exec(ctx, resetTaskInstanceToNone, arg.DagRunID, arg.TaskID)
	return err
}

const updateDagRunState = `-- name: UpdateDagRunState :one
UPDATE dag_runs
SET state = $2, started_at = $3, ended_at = $4
WHERE id = $1
RETURNING id, tenant_id, dag_id, dag_version_id, run_id, logical_date, data_interval_start, data_interval_end, state, trigger, conf, triggered_by, queued_at, started_at, ended_at, note
`

type UpdateDagRunStateParams struct {
	ID        pgtype.UUID        `json:"id"`
	State     DagRunState        `json:"state"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	EndedAt   pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) UpdateDagRunState(ctx context.Context, arg UpdateDagRunStateParams) (DagRun, error) {
	row := q.db.QueryRow(ctx, updateDagRunState,
		arg.ID,
		arg.State,
		arg.StartedAt,
		arg.EndedAt,
	)
	var i DagRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DagID,
		&i.DagVersionID,
		&i.RunID,
		&i.LogicalDate,
		&i.DataIntervalStart,
		&i.DataIntervalEnd,
		&i.State,
		&i.Trigger,
		&i.Conf,
		&i.TriggeredBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Note,
	)
	return i, err
}

const updateTaskInstanceState = `-- name: UpdateTaskInstanceState :one
UPDATE task_instances
SET state = $2, started_at = $3, ended_at = $4
WHERE id = $1
RETURNING id, tenant_id, dag_run_id, task_id, map_index, try_number, max_tries, state, pool, operator, queued_at, started_at, ended_at, duration_seconds, pod_name, node_name, exit_code, error_message, log_url, hostname
`

type UpdateTaskInstanceStateParams struct {
	ID        pgtype.UUID        `json:"id"`
	State     TaskState          `json:"state"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	EndedAt   pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) UpdateTaskInstanceState(ctx context.Context, arg UpdateTaskInstanceStateParams) (TaskInstance, error) {
	row := q.db.QueryRow(ctx, updateTaskInstanceState,
		arg.ID,
		arg.State,
		arg.StartedAt,
		arg.EndedAt,
	)
	var i TaskInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DagRunID,
		&i.TaskID,
		&i.MapIndex,
		&i.TryNumber,
		&i.MaxTries,
		&i.State,
		&i.Pool,
		&i.Operator,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.PodName,
		&i.NodeName,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.LogUrl,
		&i.Hostname,
	)
	return i, err
}

const updateTaskInstanceStateByRunTask = `-- name: UpdateTaskInstanceStateByRunTask :exec
UPDATE task_instances SET state = $3
WHERE dag_run_id = $1 AND task_id = $2
`

type UpdateTaskInstanceStateByRunTaskParams struct {
	DagRunID pgtype.UUID `json:"dag_run_id"`
	TaskID   string      `json:"task_id"`
	State    TaskState   `json:"state"`
}

func (q *Queries) UpdateTaskInstanceStateByRunTask(ctx context.Context, arg UpdateTaskInstanceStateByRunTaskParams) error {
	_, err := q.db.Exec(ctx, updateTaskInstanceStateByRunTask, arg.DagRunID, arg.TaskID, arg.State)
	return err
}
