// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAlertAttempt = `-- name: ClaimAlertAttempt :one
UPDATE dag_runs
SET alert_attempts = alert_attempts + 1,
    next_alert_attempt_at = now() + $2::interval
WHERE id = $1
  AND alerted_at IS NULL
  AND alert_attempts < $3
  AND (next_alert_attempt_at IS NULL OR next_alert_attempt_at <= now())
RETURNING id, alert_attempts
`

type ClaimAlertAttemptParams struct {
	ID          pgtype.UUID     `json:"id"`
	Backoff     pgtype.Interval `json:"backoff"`
	MaxAttempts int32           `json:"max_attempts"`
}

type ClaimAlertAttemptRow struct {
	ID            pgtype.UUID `json:"id"`
	AlertAttempts int32       `json:"alert_attempts"`
}

// Atomically claim one on-failure ATTEMPT for a run, returning the row iff this
// call won it. Replaces the old claim-then-send (#431), which set alerted_at
// before the send and so lost the page whenever the send failed.
//
// Three predicates, one per way an attempt should be refused:
//   - alerted_at IS NULL  — already delivered; never page twice for one episode.
//   - alert_attempts < $2 — the budget is spent; a dead endpoint stops being
//     retried instead of being hit once per tick for the life of the run.
//   - next_alert_attempt_at — backoff has not elapsed yet.
//
// The attempt is consumed up front, before the send, so a crash mid-send costs one
// attempt rather than looping. A clear resets all three (ResetDagRunToVersion),
// making the next genuine failure a fresh episode with a fresh budget.
func (q *Queries) ClaimAlertAttempt(ctx context.Context, arg ClaimAlertAttemptParams) (ClaimAlertAttemptRow, error) {
	row := q.db.QueryRow(ctx, claimAlertAttempt, arg.ID, arg.Backoff, arg.MaxAttempts)
	var i ClaimAlertAttemptRow
	err := row.Scan(&i.ID, &i.AlertAttempts)
	return i, err
}

const countActiveDagRunsByDagID = `-- name: CountActiveDagRunsByDagID :one
SELECT count(*) FROM dag_runs
WHERE dag_id = $1 AND state IN ('queued', 'running')
`

// Counts queued+running runs for a single DAG; used by the manual-trigger
// path to enforce max_active_runs (#200) before insert.
func (q *Queries) CountActiveDagRunsByDagID(ctx context.Context, dagID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveDagRunsByDagID, dagID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDagRunStatesInWindow = `-- name: CountDagRunStatesInWindow :many
SELECT r.state AS state, count(*) AS n
FROM dag_runs r
JOIN dags d ON d.id = r.dag_id
WHERE d.tenant_id = $1 AND r.logical_date >= $2 AND r.logical_date <= $3
GROUP BY r.state
`

type CountDagRunStatesInWindowParams struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	LogicalDate   pgtype.Timestamptz `json:"logical_date"`
	LogicalDate_2 pgtype.Timestamptz `json:"logical_date_2"`
}

type CountDagRunStatesInWindowRow struct {
	State DagRunState `json:"state"`
	N     int64       `json:"n"`
}

func (q *Queries) CountDagRunStatesInWindow(ctx context.Context, arg CountDagRunStatesInWindowParams) ([]CountDagRunStatesInWindowRow, error) {
	rows, err := q.db.Query(ctx, countDagRunStatesInWindow, arg.TenantID, arg.LogicalDate, arg.LogicalDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDagRunStatesInWindowRow{}
	for rows.Next() {
		var i CountDagRunStatesInWindowRow
		if err := rows.Scan(&i.State, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDagRunsByDag = `-- name: CountDagRunsByDag :one
SELECT count(*) FROM dag_runs WHERE dag_id = $1
`

func (q *Queries) CountDagRunsByDag(ctx context.Context, dagID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDagRunsByDag, dagID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDagsByLatestRunState = `-- name: CountDagsByLatestRunState :many
SELECT lr.state AS state, count(*) AS n
FROM (
    SELECT DISTINCT ON (r.dag_id) r.state
    FROM dag_runs r
    JOIN dags d ON d.id = r.dag_id
    WHERE d.tenant_id = $1
    ORDER BY r.dag_id, r.logical_date DESC
) lr
GROUP BY lr.state
`

type CountDagsByLatestRunStateRow struct {
	State DagRunState `json:"state"`
	N     int64       `json:"n"`
}

func (q *Queries) CountDagsByLatestRunState(ctx context.Context, tenantID pgtype.UUID) ([]CountDagsByLatestRunStateRow, error) {
	rows, err := q.db.Query(ctx, countDagsByLatestRunState, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDagsByLatestRunStateRow{}
	for rows.Next() {
		var i CountDagsByLatestRunStateRow
		if err := rows.Scan(&i.State, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTaskInstanceStatesInWindow = `-- name: CountTaskInstanceStatesInWindow :many
SELECT ti.state AS state, count(*) AS n
FROM task_instances ti
JOIN dag_runs r ON r.id = ti.dag_run_id
JOIN dags d ON d.id = r.dag_id
WHERE d.tenant_id = $1 AND r.logical_date >= $2 AND r.logical_date <= $3
GROUP BY ti.state
`

type CountTaskInstanceStatesInWindowParams struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	LogicalDate   pgtype.Timestamptz `json:"logical_date"`
	LogicalDate_2 pgtype.Timestamptz `json:"logical_date_2"`
}

type CountTaskInstanceStatesInWindowRow struct {
	State TaskState `json:"state"`
	N     int64     `json:"n"`
}

func (q *Queries) CountTaskInstanceStatesInWindow(ctx context.Context, arg CountTaskInstanceStatesInWindowParams) ([]CountTaskInstanceStatesInWindowRow, error) {
	rows, err := q.db.Query(ctx, countTaskInstanceStatesInWindow, arg.TenantID, arg.LogicalDate, arg.LogicalDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountTaskInstanceStatesInWindowRow{}
	for rows.Next() {
		var i CountTaskInstanceStatesInWindowRow
		if err := rows.Scan(&i.State, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDagRun = `-- name: CreateDagRun :one
INSERT INTO dag_runs (tenant_id, dag_id, dag_version_id, run_id, logical_date, state, trigger, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, dag_id, dag_version_id, run_id, logical_date, data_interval_start, data_interval_end, state, trigger, conf, triggered_by, queued_at, started_at, ended_at, note, alerted_at, alert_attempts, next_alert_attempt_at
`

type CreateDagRunParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	DagID        pgtype.UUID        `json:"dag_id"`
	DagVersionID pgtype.UUID        `json:"dag_version_id"`
	RunID        string             `json:"run_id"`
	LogicalDate  pgtype.Timestamptz `json:"logical_date"`
	State        DagRunState        `json:"state"`
	Trigger      DagRunTrigger      `json:"trigger"`
	Note         *string            `json:"note"`
}

func (q *Queries) CreateDagRun(ctx context.Context, arg CreateDagRunParams) (DagRun, error) {
	row := q.db.QueryRow(ctx, createDagRun,
		arg.TenantID,
		arg.DagID,
		arg.DagVersionID,
		arg.RunID,
		arg.LogicalDate,
		arg.State,
		arg.Trigger,
		arg.Note,
	)
	var i DagRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DagID,
		&i.DagVersionID,
		&i.RunID,
		&i.LogicalDate,
		&i.DataIntervalStart,
		&i.DataIntervalEnd,
		&i.State,
		&i.Trigger,
		&i.Conf,
		&i.TriggeredBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Note,
		&i.AlertedAt,
		&i.AlertAttempts,
		&i.NextAlertAttemptAt,
	)
	return i, err
}

const createScheduledRunByDagID = `-- name: CreateScheduledRunByDagID :exec
INSERT INTO dag_runs (tenant_id, dag_id, dag_version_id, run_id, logical_date, state, trigger)
SELECT d.tenant_id, d.id, d.current_version_id, $1, $2, 'queued', 'scheduled'
FROM dags d
JOIN tenants t ON t.id = d.tenant_id
WHERE t.name = $3 AND d.dag_id = $4 AND d.current_version_id IS NOT NULL
ON CONFLICT (dag_id, run_id) DO NOTHING
`

type CreateScheduledRunByDagIDParams struct {
	RunID       string             `json:"run_id"`
	LogicalDate pgtype.Timestamptz `json:"logical_date"`
	Tenant      string             `json:"tenant"`
	DagID       string             `json:"dag_id"`
}

func (q *Queries) CreateScheduledRunByDagID(ctx context.Context, arg CreateScheduledRunByDagIDParams) error {
	_, err := q.db.Exec(ctx, createScheduledRunByDagID,
		arg.RunID,
		arg.LogicalDate,
		arg.Tenant,
		arg.DagID,
	)
	return err
}

const createTaskInstance = `-- name: CreateTaskInstance :one
INSERT INTO task_instances (tenant_id, dag_run_id, task_id, operator, max_tries, state, try_number)
VALUES ($1, $2, $3, $4, $5, $6, 1)
RETURNING id, tenant_id, dag_run_id, task_id, map_index, try_number, max_tries, state, pool, operator, queued_at, started_at, ended_at, duration_seconds, pod_name, node_name, exit_code, error_message, log_url, hostname, note, scheduled_at, last_heartbeat_at, reschedule_at, first_reschedule_at, dispatch_attempts, next_dispatch_at, last_failure_kind, infra_attempts
`

type CreateTaskInstanceParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	DagRunID pgtype.UUID `json:"dag_run_id"`
	TaskID   string      `json:"task_id"`
	Operator string      `json:"operator"`
	MaxTries int32       `json:"max_tries"`
	State    TaskState   `json:"state"`
}

// try_number starts at 1 to match Airflow (1-based attempts): the first run's
// logs live at .../1.log, which is where the UI's log view looks. Retries bump
// it via ResetForRetry.
func (q *Queries) CreateTaskInstance(ctx context.Context, arg CreateTaskInstanceParams) (TaskInstance, error) {
	row := q.db.QueryRow(ctx, createTaskInstance,
		arg.TenantID,
		arg.DagRunID,
		arg.TaskID,
		arg.Operator,
		arg.MaxTries,
		arg.State,
	)
	var i TaskInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DagRunID,
		&i.TaskID,
		&i.MapIndex,
		&i.TryNumber,
		&i.MaxTries,
		&i.State,
		&i.Pool,
		&i.Operator,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.PodName,
		&i.NodeName,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.LogUrl,
		&i.Hostname,
		&i.Note,
		&i.ScheduledAt,
		&i.LastHeartbeatAt,
		&i.RescheduleAt,
		&i.FirstRescheduleAt,
		&i.DispatchAttempts,
		&i.NextDispatchAt,
		&i.LastFailureKind,
		&i.InfraAttempts,
	)
	return i, err
}

const deleteDagRun = `-- name: DeleteDagRun :execrows
DELETE FROM dag_runs WHERE dag_id = $1 AND run_id = $2
`

type DeleteDagRunParams struct {
	DagID pgtype.UUID `json:"dag_id"`
	RunID string      `json:"run_id"`
}

// Removes one run; its task_instances and XCom rows cascade (ON DELETE CASCADE).
func (q *Queries) DeleteDagRun(ctx context.Context, arg DeleteDagRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDagRun, arg.DagID, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failDispatchExhausted = `-- name: FailDispatchExhausted :exec
UPDATE task_instances
SET state = 'failed', ended_at = now(), error_message = $3,
    next_dispatch_at = NULL
WHERE dag_run_id = $1 AND task_id = $2 AND state = 'scheduled'
`

type FailDispatchExhaustedParams struct {
	DagRunID     pgtype.UUID `json:"dag_run_id"`
	TaskID       string      `json:"task_id"`
	ErrorMessage *string     `json:"error_message"`
}

// The dispatch-attempt budget is spent (ADR 0031 Amendment A): fail the task with
// a dispatch_failed reason so the run can finalize instead of looping forever.
// error_message carries the underlying cause. Guarded to 'scheduled' for the same
// reason as RecordDispatchFailure. This is distinct from dispatch_lost (a TI that
// reached 'queued' then vanished) and from a task's own 'failed' (the code ran).
func (q *Queries) FailDispatchExhausted(ctx context.Context, arg FailDispatchExhaustedParams) error {
	_, err := q.db.Exec(ctx, failDispatchExhausted, arg.DagRunID, arg.TaskID, arg.ErrorMessage)
	return err
}

const failTaskInstanceIfActive = `-- name: FailTaskInstanceIfActive :exec
UPDATE task_instances
SET state = 'failed', ended_at = now(), error_message = $2
WHERE id = $1 AND state IN ('scheduled', 'queued', 'running')
`

type FailTaskInstanceIfActiveParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage *string     `json:"error_message"`
}

func (q *Queries) FailTaskInstanceIfActive(ctx context.Context, arg FailTaskInstanceIfActiveParams) error {
	_, err := q.db.Exec(ctx, failTaskInstanceIfActive, arg.ID, arg.ErrorMessage)
	return err
}

const getDagRun = `-- name: GetDagRun :one
SELECT id, tenant_id, dag_id, dag_version_id, run_id, logical_date, data_interval_start, data_interval_end, state, trigger, conf, triggered_by, queued_at, started_at, ended_at, note, alerted_at, alert_attempts, next_alert_attempt_at FROM dag_runs WHERE dag_id = $1 AND run_id = $2
`

type GetDagRunParams struct {
	DagID pgtype.UUID `json:"dag_id"`
	RunID string      `json:"run_id"`
}

func (q *Queries) GetDagRun(ctx context.Context, arg GetDagRunParams) (DagRun, error) {
	row := q.db.QueryRow(ctx, getDagRun, arg.DagID, arg.RunID)
	var i DagRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DagID,
		&i.DagVersionID,
		&i.RunID,
		&i.LogicalDate,
		&i.DataIntervalStart,
		&i.DataIntervalEnd,
		&i.State,
		&i.Trigger,
		&i.Conf,
		&i.TriggeredBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Note,
		&i.AlertedAt,
		&i.AlertAttempts,
		&i.NextAlertAttemptAt,
	)
	return i, err
}

const getDagRunByID = `-- name: GetDagRunByID :one
SELECT id, tenant_id, dag_id, dag_version_id, run_id, logical_date, data_interval_start, data_interval_end, state, trigger, conf, triggered_by, queued_at, started_at, ended_at, note, alerted_at, alert_attempts, next_alert_attempt_at FROM dag_runs WHERE id = $1
`

func (q *Queries) GetDagRunByID(ctx context.Context, id pgtype.UUID) (DagRun, error) {
	row := q.db.QueryRow(ctx, getDagRunByID, id)
	var i DagRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DagID,
		&i.DagVersionID,
		&i.RunID,
		&i.LogicalDate,
		&i.DataIntervalStart,
		&i.DataIntervalEnd,
		&i.State,
		&i.Trigger,
		&i.Conf,
		&i.TriggeredBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Note,
		&i.AlertedAt,
		&i.AlertAttempts,
		&i.NextAlertAttemptAt,
	)
	return i, err
}

const getDagVersionByID = `-- name: GetDagVersionByID :one
SELECT id, dag_id, version, image_reference, spec, spec_hash, created_by, created_at FROM dag_versions WHERE id = $1
`

func (q *Queries) GetDagVersionByID(ctx context.Context, id pgtype.UUID) (DagVersion, error) {
	row := q.db.QueryRow(ctx, getDagVersionByID, id)
	var i DagVersion
	err := row.Scan(
		&i.ID,
		&i.DagID,
		&i.Version,
		&i.ImageReference,
		&i.Spec,
		&i.SpecHash,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const latestRunsForDags = `-- name: LatestRunsForDags :many
SELECT d.dag_id AS dag_id_text,
       r.run_id, r.logical_date, r.state, r.trigger, r.queued_at, r.started_at, r.ended_at
FROM dags d
JOIN LATERAL (
    SELECT dr.run_id, dr.logical_date, dr.state, dr.trigger, dr.queued_at, dr.started_at, dr.ended_at
    FROM dag_runs dr
    WHERE dr.dag_id = d.id
    ORDER BY dr.logical_date DESC
    LIMIT $3
) r ON true
WHERE d.tenant_id = $1 AND d.dag_id = ANY($2::text[])
ORDER BY d.dag_id, r.logical_date DESC
`

type LatestRunsForDagsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Column2  []string    `json:"column_2"`
	Limit    int32       `json:"limit"`
}

type LatestRunsForDagsRow struct {
	DagIDText   string             `json:"dag_id_text"`
	RunID       string             `json:"run_id"`
	LogicalDate pgtype.Timestamptz `json:"logical_date"`
	State       DagRunState        `json:"state"`
	Trigger     DagRunTrigger      `json:"trigger"`
	QueuedAt    pgtype.Timestamptz `json:"queued_at"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) LatestRunsForDags(ctx context.Context, arg LatestRunsForDagsParams) ([]LatestRunsForDagsRow, error) {
	rows, err := q.db.Query(ctx, latestRunsForDags, arg.TenantID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestRunsForDagsRow{}
	for rows.Next() {
		var i LatestRunsForDagsRow
		if err := rows.Scan(
			&i.DagIDText,
			&i.RunID,
			&i.LogicalDate,
			&i.State,
			&i.Trigger,
			&i.QueuedAt,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveDagRuns = `-- name: ListActiveDagRuns :many
SELECT id, tenant_id, dag_id, dag_version_id, run_id, logical_date, data_interval_start, data_interval_end, state, trigger, conf, triggered_by, queued_at, started_at, ended_at, note, alerted_at, alert_attempts, next_alert_attempt_at FROM dag_runs
WHERE state IN ('queued', 'running')
ORDER BY queued_at
`

func (q *Queries) ListActiveDagRuns(ctx context.Context) ([]DagRun, error) {
	rows, err := q.db.Query(ctx, listActiveDagRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DagRun{}
	for rows.Next() {
		var i DagRun
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DagID,
			&i.DagVersionID,
			&i.RunID,
			&i.LogicalDate,
			&i.DataIntervalStart,
			&i.DataIntervalEnd,
			&i.State,
			&i.Trigger,
			&i.Conf,
			&i.TriggeredBy,
			&i.QueuedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.Note,
			&i.AlertedAt,
			&i.AlertAttempts,
			&i.NextAlertAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentLostCandidates = `-- name: ListAgentLostCandidates :many
SELECT ti.id AS task_instance_id,
       ti.dag_run_id AS dag_run_id,
       d.dag_id AS dag_id_text,
       ti.task_id AS task_id,
       ti.try_number AS try_number,
       ti.last_heartbeat_at AS last_heartbeat_at
FROM task_instances ti
JOIN dag_runs dr ON dr.id = ti.dag_run_id
JOIN dags d ON d.id = dr.dag_id
WHERE ti.state = 'running'
  AND ti.last_heartbeat_at IS NOT NULL
ORDER BY ti.last_heartbeat_at
LIMIT 100
`

type ListAgentLostCandidatesRow struct {
	TaskInstanceID  pgtype.UUID        `json:"task_instance_id"`
	DagRunID        pgtype.UUID        `json:"dag_run_id"`
	DagIDText       string             `json:"dag_id_text"`
	TaskID          string             `json:"task_id"`
	TryNumber       int32              `json:"try_number"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
}

// Lists running TIs that have heartbeated at least once and whose latest
// heartbeat is non-null, alongside enough identity to log + observe.
// The "non-null" filter is the safety guarantee: a TI that never heartbeated
// is either inline (no agent ever exists) or fresh — out of scope for this
// reaper. The LIMIT bounds a single tick's reap work even after a large
// outage; the rest are picked up on the next tick.
func (q *Queries) ListAgentLostCandidates(ctx context.Context) ([]ListAgentLostCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listAgentLostCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentLostCandidatesRow{}
	for rows.Next() {
		var i ListAgentLostCandidatesRow
		if err := rows.Scan(
			&i.TaskInstanceID,
			&i.DagRunID,
			&i.DagIDText,
			&i.TaskID,
			&i.TryNumber,
			&i.LastHeartbeatAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDagRunsByDag = `-- name: ListDagRunsByDag :many
SELECT id, tenant_id, dag_id, dag_version_id, run_id, logical_date, data_interval_start, data_interval_end, state, trigger, conf, triggered_by, queued_at, started_at, ended_at, note, alerted_at, alert_attempts, next_alert_attempt_at FROM dag_runs
WHERE dag_id = $1
ORDER BY logical_date DESC
LIMIT $2 OFFSET $3
`

type ListDagRunsByDagParams struct {
	DagID  pgtype.UUID `json:"dag_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListDagRunsByDag(ctx context.Context, arg ListDagRunsByDagParams) ([]DagRun, error) {
	rows, err := q.db.Query(ctx, listDagRunsByDag, arg.DagID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DagRun{}
	for rows.Next() {
		var i DagRun
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DagID,
			&i.DagVersionID,
			&i.RunID,
			&i.LogicalDate,
			&i.DataIntervalStart,
			&i.DataIntervalEnd,
			&i.State,
			&i.Trigger,
			&i.Conf,
			&i.TriggeredBy,
			&i.QueuedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.Note,
			&i.AlertedAt,
			&i.AlertAttempts,
			&i.NextAlertAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanCandidates = `-- name: ListOrphanCandidates :many
SELECT dr.id AS id,
       d.dag_id AS dag_id_text,
       GREATEST(
           COALESCE(MAX(ti.ended_at), 'epoch'::timestamptz),
           COALESCE(MAX(ti.started_at), 'epoch'::timestamptz),
           COALESCE(dr.started_at, 'epoch'::timestamptz),
           dr.queued_at
       )::timestamptz AS last_activity
FROM dag_runs dr
JOIN dags d ON d.id = dr.dag_id
LEFT JOIN task_instances ti ON ti.dag_run_id = dr.id
WHERE dr.state = 'running'
  AND NOT EXISTS (
      SELECT 1 FROM task_instances ti2
      WHERE ti2.dag_run_id = dr.id
        AND ti2.state IN ('scheduled', 'queued', 'running')
  )
GROUP BY dr.id, d.dag_id, dr.started_at, dr.queued_at
ORDER BY dr.queued_at
LIMIT 100
`

type ListOrphanCandidatesRow struct {
	ID           pgtype.UUID        `json:"id"`
	DagIDText    string             `json:"dag_id_text"`
	LastActivity pgtype.Timestamptz `json:"last_activity"`
}

// Lists dag_runs currently in 'running' whose task instances are ALL terminal
// or never-started (no TI in scheduled/queued/running), alongside the
// timestamp of their most recent observable activity. The "no active TI"
// filter is the critical safety guarantee: a legitimately-active task (slow
// image pull, long-running job) keeps its run out of the candidate set, so
// the reaper can never kill a live execution. The shape this catches is the
// post-crash one: TIs settled (success/failed/skipped/upstream_failed) but
// FinalizeRun did not transition the dag_run — e.g. the server died between
// the last TI report and the next scheduler tick. The LIMIT bounds a single
// tick's reap work even after a multi-hour outage; the rest are picked up
// on the next tick (the reaper is a backstop, not a sprint).
func (q *Queries) ListOrphanCandidates(ctx context.Context) ([]ListOrphanCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listOrphanCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrphanCandidatesRow{}
	for rows.Next() {
		var i ListOrphanCandidatesRow
		if err := rows.Scan(&i.ID, &i.DagIDText, &i.LastActivity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningTasks = `-- name: ListRunningTasks :many
SELECT ti.id AS task_instance_id,
       ti.dag_run_id AS dag_run_id,
       d.dag_id AS dag_id_text,
       ti.task_id AS task_id,
       ti.try_number AS try_number,
       ti.started_at AS started_at
FROM task_instances ti
JOIN dag_runs dr ON dr.id = ti.dag_run_id
JOIN dags d ON d.id = dr.dag_id
WHERE ti.state = 'running'
ORDER BY ti.started_at NULLS LAST
LIMIT 100
`

type ListRunningTasksRow struct {
	TaskInstanceID pgtype.UUID        `json:"task_instance_id"`
	DagRunID       pgtype.UUID        `json:"dag_run_id"`
	DagIDText      string             `json:"dag_id_text"`
	TaskID         string             `json:"task_id"`
	TryNumber      int32              `json:"try_number"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
}

// Lists every TI currently in `running` alongside the timestamp it entered
// running, for the pod-lost reaper (#527). A running TI whose backing pod
// vanished before its first heartbeat is invisible to the agent-lost reaper
// (its null-heartbeat zero-guard) and to the reconciler (which only sees pods
// that still exist), so it would sit `running` until the 5-minute orphan reaper.
// The reaper applies the grace period + a pod-liveness check per candidate in
// Go, so the SQL stays simple. The LIMIT bounds a single tick's reap work even
// after a large outage; the rest are picked up next tick.
func (q *Queries) ListRunningTasks(ctx context.Context) ([]ListRunningTasksRow, error) {
	rows, err := q.db.Query(ctx, listRunningTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunningTasksRow{}
	for rows.Next() {
		var i ListRunningTasksRow
		if err := rows.Scan(
			&i.TaskInstanceID,
			&i.DagRunID,
			&i.DagIDText,
			&i.TaskID,
			&i.TryNumber,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledDags = `-- name: ListScheduledDags :many
SELECT d.dag_id, d.schedule, d.catchup, d.start_date, d.max_active_runs,
  (SELECT max(dr.logical_date) FROM dag_runs dr WHERE dr.dag_id = d.id) AS last_logical
FROM dags d
WHERE d.is_active = true AND d.is_paused = false
  AND d.schedule IS NOT NULL AND d.current_version_id IS NOT NULL
`

type ListScheduledDagsRow struct {
	DagID         string             `json:"dag_id"`
	Schedule      *string            `json:"schedule"`
	Catchup       bool               `json:"catchup"`
	StartDate     pgtype.Timestamptz `json:"start_date"`
	MaxActiveRuns int32              `json:"max_active_runs"`
	LastLogical   interface{}        `json:"last_logical"`
}

// Returns each cron-scheduled DAG with the bits the scheduler needs to decide
// both "is there a slot due?" (schedule + last_logical), "how many slots
// should I backfill on this tick?" (catchup + start_date, see #129), and
// "may this DAG take another active run?" (max_active_runs, see #200).
func (q *Queries) ListScheduledDags(ctx context.Context) ([]ListScheduledDagsRow, error) {
	rows, err := q.db.Query(ctx, listScheduledDags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduledDagsRow{}
	for rows.Next() {
		var i ListScheduledDagsRow
		if err := rows.Scan(
			&i.DagID,
			&i.Schedule,
			&i.Catchup,
			&i.StartDate,
			&i.MaxActiveRuns,
			&i.LastLogical,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleQueuedTaskInstances = `-- name: ListStaleQueuedTaskInstances :many
SELECT ti.id AS task_instance_id,
       ti.dag_run_id,
       d.dag_id AS dag_id_text,
       ti.task_id,
       ti.try_number,
       ti.queued_at
FROM task_instances ti
JOIN dag_runs dr ON dr.id = ti.dag_run_id
JOIN dags d ON d.id = dr.dag_id
WHERE ti.state = 'queued'
ORDER BY ti.queued_at NULLS LAST
LIMIT 100
`

type ListStaleQueuedTaskInstancesRow struct {
	TaskInstanceID pgtype.UUID        `json:"task_instance_id"`
	DagRunID       pgtype.UUID        `json:"dag_run_id"`
	DagIDText      string             `json:"dag_id_text"`
	TaskID         string             `json:"task_id"`
	TryNumber      int32              `json:"try_number"`
	QueuedAt       pgtype.Timestamptz `json:"queued_at"`
}

// Lists every TI currently in `queued` alongside its queued_at timestamp for
// the dispatch-lost reaper (#202). The reaper applies the threshold per
// candidate so the SQL stays simple and the decision is purely in Go. The
// LIMIT bounds a tick's reap work after a long outage; the rest are picked
// up next tick (backstop, not sprint).
func (q *Queries) ListStaleQueuedTaskInstances(ctx context.Context) ([]ListStaleQueuedTaskInstancesRow, error) {
	rows, err := q.db.Query(ctx, listStaleQueuedTaskInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleQueuedTaskInstancesRow{}
	for rows.Next() {
		var i ListStaleQueuedTaskInstancesRow
		if err := rows.Scan(
			&i.TaskInstanceID,
			&i.DagRunID,
			&i.DagIDText,
			&i.TaskID,
			&i.TryNumber,
			&i.QueuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskInstanceAttempts = `-- name: ListTaskInstanceAttempts :many
SELECT
    ti.id AS task_instance_id,
    ti.map_index,
    ti.operator,
    ti.max_tries,
    h.try_number,
    h.state,
    h.queued_at,
    h.scheduled_at,
    h.started_at,
    h.ended_at,
    h.duration_seconds,
    h.exit_code,
    h.error_message,
    h.hostname,
    h.pod_name,
    h.node_name,
    h.note
FROM task_instance_history h
JOIN task_instances ti ON ti.id = h.task_instance_id
WHERE ti.dag_run_id = $1 AND ti.task_id = $2
UNION ALL
SELECT
    ti.id AS task_instance_id,
    ti.map_index,
    ti.operator,
    ti.max_tries,
    ti.try_number,
    ti.state,
    ti.queued_at,
    ti.scheduled_at,
    ti.started_at,
    ti.ended_at,
    ti.duration_seconds,
    ti.exit_code,
    ti.error_message,
    ti.hostname,
    ti.pod_name,
    ti.node_name,
    ti.note
FROM task_instances ti
WHERE ti.dag_run_id = $1 AND ti.task_id = $2
ORDER BY try_number
`

type ListTaskInstanceAttemptsParams struct {
	DagRunID pgtype.UUID `json:"dag_run_id"`
	TaskID   string      `json:"task_id"`
}

type ListTaskInstanceAttemptsRow struct {
	TaskInstanceID  pgtype.UUID        `json:"task_instance_id"`
	MapIndex        int32              `json:"map_index"`
	Operator        string             `json:"operator"`
	MaxTries        int32              `json:"max_tries"`
	TryNumber       int32              `json:"try_number"`
	State           TaskState          `json:"state"`
	QueuedAt        pgtype.Timestamptz `json:"queued_at"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	DurationSeconds *float64           `json:"duration_seconds"`
	ExitCode        *int32             `json:"exit_code"`
	ErrorMessage    *string            `json:"error_message"`
	Hostname        *string            `json:"hostname"`
	PodName         *string            `json:"pod_name"`
	NodeName        *string            `json:"node_name"`
	Note            *string            `json:"note"`
}

// Returns every attempt for (run, task), oldest first. UNIONs the current
// task_instances row with all archived task_instance_history rows so the UI's
// /tries endpoint can render one navigable tab per attempt (Lima bug #241).
// Each row carries the per-attempt fields PLUS the run-constant fields
// (operator, max_tries, map_index) copied from the current TI; archived rows
// get them via the JOIN.
func (q *Queries) ListTaskInstanceAttempts(ctx context.Context, arg ListTaskInstanceAttemptsParams) ([]ListTaskInstanceAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listTaskInstanceAttempts, arg.DagRunID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskInstanceAttemptsRow{}
	for rows.Next() {
		var i ListTaskInstanceAttemptsRow
		if err := rows.Scan(
			&i.TaskInstanceID,
			&i.MapIndex,
			&i.Operator,
			&i.MaxTries,
			&i.TryNumber,
			&i.State,
			&i.QueuedAt,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.ExitCode,
			&i.ErrorMessage,
			&i.Hostname,
			&i.PodName,
			&i.NodeName,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskInstancesByRun = `-- name: ListTaskInstancesByRun :many
SELECT id, tenant_id, dag_run_id, task_id, map_index, try_number, max_tries, state, pool, operator, queued_at, started_at, ended_at, duration_seconds, pod_name, node_name, exit_code, error_message, log_url, hostname, note, scheduled_at, last_heartbeat_at, reschedule_at, first_reschedule_at, dispatch_attempts, next_dispatch_at, last_failure_kind, infra_attempts FROM task_instances
WHERE dag_run_id = $1
ORDER BY task_id
`

func (q *Queries) ListTaskInstancesByRun(ctx context.Context, dagRunID pgtype.UUID) ([]TaskInstance, error) {
	rows, err := q.db.Query(ctx, listTaskInstancesByRun, dagRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskInstance{}
	for rows.Next() {
		var i TaskInstance
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DagRunID,
			&i.TaskID,
			&i.MapIndex,
			&i.TryNumber,
			&i.MaxTries,
			&i.State,
			&i.Pool,
			&i.Operator,
			&i.QueuedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.PodName,
			&i.NodeName,
			&i.ExitCode,
			&i.ErrorMessage,
			&i.LogUrl,
			&i.Hostname,
			&i.Note,
			&i.ScheduledAt,
			&i.LastHeartbeatAt,
			&i.RescheduleAt,
			&i.FirstRescheduleAt,
			&i.DispatchAttempts,
			&i.NextDispatchAt,
			&i.LastFailureKind,
			&i.InfraAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunAlertDelivered = `-- name: MarkRunAlertDelivered :exec
UPDATE dag_runs
SET alerted_at = now(), next_alert_attempt_at = NULL
WHERE id = $1 AND alert_attempts = $2
`

type MarkRunAlertDeliveredParams struct {
	ID      pgtype.UUID `json:"id"`
	Attempt int32       `json:"attempt"`
}

// Stamp a run's on-failure alert as DELIVERED. Called only after a successful
// send, which is the whole point of the split: alerted_at now answers "did the
// page get through", not "did we try".
//
// Guarded on the attempt it is reporting for. The send runs in a goroutine
// detached from the tick, so an operator clear can land between the claim and the
// stamp: the clear resets alert_attempts to 0 and starts a NEW failure episode,
// and an unguarded stamp from the old in-flight send would mark that new episode
// delivered without ever paging it. Requiring the attempt to still match means a
// stamp from a superseded episode simply matches no row. Same shape as the guard
// on ReportTaskResult: a late writer must never clobber newer state.
func (q *Queries) MarkRunAlertDelivered(ctx context.Context, arg MarkRunAlertDeliveredParams) error {
	_, err := q.db.Exec(ctx, markRunAlertDelivered, arg.ID, arg.Attempt)
	return err
}

const markRunOrphanedRun = `-- name: MarkRunOrphanedRun :execrows
UPDATE dag_runs
SET state = 'failed',
    ended_at = now(),
    note = 'orphaned: no scheduler activity within the orphan window — see #120'
WHERE id = $1 AND state = 'running'
`

// Fails an orphaned dag run. The `state = 'running'` guard makes the reap a
// safety net, never a takeover: a competing finalizer (the normal scheduler
// path) cannot be overwritten. Idempotent: a second call on a run already
// failed updates zero rows.
func (q *Queries) MarkRunOrphanedRun(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markRunOrphanedRun, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRunOrphanedTaskInstances = `-- name: MarkRunOrphanedTaskInstances :exec
UPDATE task_instances
SET state = 'failed',
    ended_at = now(),
    error_message = 'orphaned: scheduler restart left this task without a runner'
WHERE dag_run_id = $1
  AND state IN ('scheduled', 'queued', 'running')
`

// Fails any still-active task instance under an orphaned run. Called together
// with MarkRunOrphanedRun inside a single transaction (the repository owns the
// atomicity); split because sqlc cannot generate a CTE+UPDATE that reuses one
// parameter across an UPDATE-inside-WITH and the outer UPDATE.
func (q *Queries) MarkRunOrphanedTaskInstances(ctx context.Context, dagRunID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markRunOrphanedTaskInstances, dagRunID)
	return err
}

const markTaskAgentLost = `-- name: MarkTaskAgentLost :execrows
UPDATE task_instances
SET state = 'failed',
    ended_at = now(),
    last_failure_kind = 'infra',
    error_message = 'agent_lost: no heartbeat within the threshold — see #128'
WHERE id = $1 AND state = 'running'
`

// Fails a TI whose agent went silent. The WHERE state='running' guard
// prevents overwriting a TI the agent's last terminal report finally
// delivered between our list and our write (defense in depth — a late
// report wins over the reaper). Idempotent on a second call.
func (q *Queries) MarkTaskAgentLost(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markTaskAgentLost, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markTaskDispatchFailed = `-- name: MarkTaskDispatchFailed :exec
UPDATE task_instances
SET state = 'failed',
    ended_at = now(),
    error_message = $3
WHERE dag_run_id = $1
  AND task_id = $2
  AND state IN ('scheduled', 'queued')
`

type MarkTaskDispatchFailedParams struct {
	DagRunID     pgtype.UUID `json:"dag_run_id"`
	TaskID       string      `json:"task_id"`
	ErrorMessage *string     `json:"error_message"`
}

// Fails a TI whose asynchronous dispatch (BufferedDispatcher worker) errored
// inside the inner dispatcher. Targets the active row by (dag_run_id,
// task_id) and the active states (scheduled/queued) — a TI that already
// moved to running/terminal between the worker accepting the request and
// the dispatch failing is left alone (defense in depth).
func (q *Queries) MarkTaskDispatchFailed(ctx context.Context, arg MarkTaskDispatchFailedParams) error {
	_, err := q.db.Exec(ctx, markTaskDispatchFailed, arg.DagRunID, arg.TaskID, arg.ErrorMessage)
	return err
}

const markTaskDispatchLost = `-- name: MarkTaskDispatchLost :exec
UPDATE task_instances
SET state = 'failed',
    ended_at = now(),
    last_failure_kind = 'infra',
    error_message = 'dispatch_lost: scheduler crashed before dispatch landed; will be retried by the run reaper'
WHERE id = $1 AND state = 'queued'
`

// Fails one queued TI with a dispatch_lost error. The WHERE state='queued'
// guard makes the operation idempotent: a second call on a TI that has
// since transitioned (real dispatch landed, or already failed) is a no-op,
// never overwriting a more meaningful state.
func (q *Queries) MarkTaskDispatchLost(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markTaskDispatchLost, id)
	return err
}

const markTaskPodLost = `-- name: MarkTaskPodLost :execrows
UPDATE task_instances
SET state = 'failed',
    ended_at = now(),
    last_failure_kind = 'infra',
    error_message = 'pod_lost: the task pod vanished with no live pod past the grace period — see #527'
WHERE id = $1 AND state = 'running'
`

// Fails a running TI whose pod has vanished (deleted/evicted/node lost). The
// WHERE state='running' guard makes it idempotent and prevents overwriting a
// late terminal report that landed between our list and our write (a live
// report wins over the reaper). Idempotent on a second call.
func (q *Queries) MarkTaskPodLost(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markTaskPodLost, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordDispatchFailure = `-- name: RecordDispatchFailure :exec
UPDATE task_instances
SET dispatch_attempts = dispatch_attempts + 1,
    next_dispatch_at = $3
WHERE dag_run_id = $1 AND task_id = $2 AND state = 'scheduled'
`

type RecordDispatchFailureParams struct {
	DagRunID       pgtype.UUID        `json:"dag_run_id"`
	TaskID         string             `json:"task_id"`
	NextDispatchAt pgtype.Timestamptz `json:"next_dispatch_at"`
}

// A synchronous dispatch attempt failed (ADR 0031 Amendment A). Increment the
// consecutive-failure counter and back off the next attempt to $3, so the planner
// (which gates scheduled->queued on next_dispatch_at) does not re-attempt every
// tick. Guarded to 'scheduled' so a report that raced the dispatch cannot clobber
// a row that has since progressed. try_number is untouched: this is infra, not a
// task failure.
func (q *Queries) RecordDispatchFailure(ctx context.Context, arg RecordDispatchFailureParams) error {
	_, err := q.db.Exec(ctx, recordDispatchFailure, arg.DagRunID, arg.TaskID, arg.NextDispatchAt)
	return err
}

const recordTaskHeartbeat = `-- name: RecordTaskHeartbeat :execrows
UPDATE task_instances
SET last_heartbeat_at = now()
WHERE dag_run_id = $1
  AND task_id = $2
  AND try_number = $3
  AND state IN ('queued', 'running')
`

type RecordTaskHeartbeatParams struct {
	DagRunID  pgtype.UUID `json:"dag_run_id"`
	TaskID    string      `json:"task_id"`
	TryNumber int32       `json:"try_number"`
}

// Stamps last_heartbeat_at on the active TI of an attempt. Bounded by the
// (dag_run_id, task_id, try_number) tuple to match the agent's identity. The
// state IN guard avoids stamping a heartbeat on a TI the scheduler already
// transitioned to terminal between the agent's last heartbeat and now — a
// terminal TI must stay terminal even if a late heartbeat arrives.
//
// Returns the affected row count. Zero means the heartbeating agent's attempt
// no longer matches the live row — its try_number is behind, or a reaper
// already settled the row terminal — the same "moved on" predicate the state
// report is guarded by (#467). The agent RPC turns a zero here into a
// should_terminate signal so a reaped-but-alive pod stops itself (#474).
func (q *Queries) RecordTaskHeartbeat(ctx context.Context, arg RecordTaskHeartbeatParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordTaskHeartbeat, arg.DagRunID, arg.TaskID, arg.TryNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const redispatchRescheduledTaskInstance = `-- name: RedispatchRescheduledTaskInstance :exec
UPDATE task_instances
SET state = 'none',
    started_at = NULL,
    ended_at = NULL,
    queued_at = NULL,
    scheduled_at = NULL,
    reschedule_at = NULL
WHERE dag_run_id = $1 AND task_id = $2 AND state = 'up_for_reschedule'
`

type RedispatchRescheduledTaskInstanceParams struct {
	DagRunID pgtype.UUID `json:"dag_run_id"`
	TaskID   string      `json:"task_id"`
}

// Re-dispatch a task parked in up_for_reschedule once its reschedule_at has passed:
// back to 'none' with the per-attempt timestamps cleared (so the next dispatch
// stamps fresh — queued_at MUST be NULL or the dispatch-lost reaper re-flags it)
// and reschedule_at cleared. Unlike ResetTaskInstanceToNone (retry), try_number is
// PRESERVED and no task_instance_history row is archived: reschedule is not a retry,
// it consumes no attempt (#380). Guarded to the parked state so it is idempotent.
func (q *Queries) RedispatchRescheduledTaskInstance(ctx context.Context, arg RedispatchRescheduledTaskInstanceParams) error {
	_, err := q.db.Exec(ctx, redispatchRescheduledTaskInstance, arg.DagRunID, arg.TaskID)
	return err
}

const reportTaskResult = `-- name: ReportTaskResult :execrows
UPDATE task_instances
SET state = $3::task_state,
    exit_code = $4,
    error_message = $5,
    started_at = CASE WHEN $3::task_state = 'running' AND started_at IS NULL THEN now() ELSE started_at END,
    ended_at = CASE WHEN $3::task_state IN ('success', 'failed', 'skipped', 'upstream_failed') THEN now() ELSE ended_at END,
    duration_seconds = CASE WHEN $3::task_state IN ('success', 'failed') AND started_at IS NOT NULL
        THEN EXTRACT(EPOCH FROM (now() - started_at)) ELSE duration_seconds END
WHERE dag_run_id = $1 AND task_id = $2
  AND try_number = $6
  AND state IN ('none', 'scheduled', 'queued', 'running')
`

type ReportTaskResultParams struct {
	DagRunID     pgtype.UUID `json:"dag_run_id"`
	TaskID       string      `json:"task_id"`
	Column3      TaskState   `json:"column_3"`
	ExitCode     *int32      `json:"exit_code"`
	ErrorMessage *string     `json:"error_message"`
	TryNumber    int32       `json:"try_number"`
}

// $3 is cast to task_state in every usage: without the cast Postgres deduces an
// enum type from `state = $3` but text from the literal comparisons below and
// rejects the parameter as having inconsistent types (SQLSTATE 42P08). The pod
// agent path is the first to exercise this query end-to-end.
//
// Guarded on both the source state and the attempt, matching the other three
// writes to this table (FailTaskInstanceIfActive, RescheduleTaskInstance,
// RecordHeartbeat). Two writers touch task_instances — the scheduler tick and
// this report — so an unguarded UPDATE lets a report that arrives late land
// wherever the row happens to be:
//   - after a reaper settled the row, it resurrects a terminal state (a run
//     reports success on work the system already abandoned, and downstream
//     tasks fire on it);
//   - after a retry, it lands on the next attempt, because ResetTaskInstanceToNone
//     bumps try_number in place rather than inserting a new row.
//
// The agent token already carries the try_number it was dispatched with, so the
// value that tells the attempts apart is present at the call site.
// Returns the affected row count so the caller can tell a real write from a
// rejected late report instead of dropping it silently.
//
// The state set is deliberately wider than the siblings' ('scheduled','queued',
// 'running'): it also admits 'none'. Those writes are driven by the scheduler,
// which only touches rows it has already advanced; this one is driven by the
// agent, which starts reporting earlier. launchQueued dispatches the pod BEFORE
// recording `queued`, so between those two statements a fast-starting task —
// routine under the Lite subprocess executor — legitimately reports `running`
// while the row is still `none`. Excluding it would reject a correct report,
// trading a rare silent corruption for a frequent one. The settled states
// (success/failed/skipped/upstream_failed) are what this guard is for.
func (q *Queries) ReportTaskResult(ctx context.Context, arg ReportTaskResultParams) (int64, error) {
	result, err := q.db.Exec(ctx, reportTaskResult,
		arg.DagRunID,
		arg.TaskID,
		arg.Column3,
		arg.ExitCode,
		arg.ErrorMessage,
		arg.TryNumber,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rescheduleTaskInstance = `-- name: RescheduleTaskInstance :exec
UPDATE task_instances
SET state = 'up_for_reschedule'::task_state,
    reschedule_at = $3,
    -- Stamp the FIRST reschedule once and preserve it across re-dispatches so the
    -- delivered get_first_reschedule_date lets the sensor honor cumulative timeout.
    first_reschedule_at = COALESCE(first_reschedule_at, now())
WHERE dag_run_id = $1 AND task_id = $2
  AND state IN ('running', 'queued', 'scheduled')
`

type RescheduleTaskInstanceParams struct {
	DagRunID     pgtype.UUID        `json:"dag_run_id"`
	TaskID       string             `json:"task_id"`
	RescheduleAt pgtype.Timestamptz `json:"reschedule_at"`
}

// A reschedule-mode sensor (mode='reschedule') poked not-ready: park the active TI
// in up_for_reschedule with its next-poke time ($3) so the scheduler re-dispatches
// it once reschedule_at passes (#380), without consuming retry budget. Guarded to
// the active states so a late report never clobbers a terminal row. ended_at is
// left untouched (the task is not finished); started_at is preserved.
func (q *Queries) RescheduleTaskInstance(ctx context.Context, arg RescheduleTaskInstanceParams) error {
	_, err := q.db.Exec(ctx, rescheduleTaskInstance, arg.DagRunID, arg.TaskID, arg.RescheduleAt)
	return err
}

const resetAllFailedTaskInstances = `-- name: ResetAllFailedTaskInstances :execrows
WITH archived AS (
    INSERT INTO task_instance_history (
        task_instance_id, try_number, state,
        queued_at, scheduled_at, started_at, ended_at, duration_seconds,
        exit_code, error_message, hostname, pod_name, node_name, note
    )
    SELECT
        src.id, src.try_number, src.state,
        src.queued_at, src.scheduled_at, src.started_at, src.ended_at, src.duration_seconds,
        src.exit_code, src.error_message, src.hostname, src.pod_name, src.node_name, src.note
    FROM task_instances src
    WHERE src.dag_run_id = $1
      AND src.state IN ('failed', 'upstream_failed', 'up_for_retry')
    ON CONFLICT (task_instance_id, try_number) DO NOTHING
    RETURNING task_instance_id
)
UPDATE task_instances ti
SET state = 'none',
    started_at = NULL,
    ended_at = NULL,
    queued_at = NULL,
    scheduled_at = NULL,
    dispatch_attempts = 0,
    next_dispatch_at = NULL,
    try_number = ti.try_number + 1
WHERE ti.dag_run_id = $1
  AND ti.state IN ('failed', 'upstream_failed', 'up_for_retry')
`

// Archives every failed attempt in the run into task_instance_history then
// resets. See ResetTaskInstanceToNone for the per-attempt rationale.
func (q *Queries) ResetAllFailedTaskInstances(ctx context.Context, dagRunID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, resetAllFailedTaskInstances, dagRunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetDagRunToVersion = `-- name: ResetDagRunToVersion :exec
UPDATE dag_runs
SET state = 'queued', started_at = NULL, ended_at = NULL, alerted_at = NULL,
    alert_attempts = 0, next_alert_attempt_at = NULL,
    dag_version_id = $2
WHERE id = $1
`

type ResetDagRunToVersionParams struct {
	ID           pgtype.UUID `json:"id"`
	DagVersionID pgtype.UUID `json:"dag_version_id"`
}

// Clear re-binds the run to the DAG's current registered version (ADR 0020): a
// re-run after a code/yaml fix picks up the newest image and config — in dev that
// is the last hot-reload, in prod the last deploy — while everything within a
// version stays reproducible. Clearing the alert bookkeeping (#431) makes the clear
// a new failure episode, so a genuine re-failure re-pages while a re-tick of the
// same failed state does not. All three columns reset together: leaving
// alert_attempts behind would carry a spent retry budget into an episode that has
// not been attempted, so a cleared run could exhaust its attempts without ever
// having tried.
func (q *Queries) ResetDagRunToVersion(ctx context.Context, arg ResetDagRunToVersionParams) error {
	_, err := q.db.Exec(ctx, resetDagRunToVersion, arg.ID, arg.DagVersionID)
	return err
}

const resetFailedTaskInstance = `-- name: ResetFailedTaskInstance :execrows
WITH archived AS (
    INSERT INTO task_instance_history (
        task_instance_id, try_number, state,
        queued_at, scheduled_at, started_at, ended_at, duration_seconds,
        exit_code, error_message, hostname, pod_name, node_name, note
    )
    SELECT
        src.id, src.try_number, src.state,
        src.queued_at, src.scheduled_at, src.started_at, src.ended_at, src.duration_seconds,
        src.exit_code, src.error_message, src.hostname, src.pod_name, src.node_name, src.note
    FROM task_instances src
    WHERE src.dag_run_id = $1 AND src.task_id = $2
      AND src.state IN ('failed', 'upstream_failed', 'up_for_retry')
    ON CONFLICT (task_instance_id, try_number) DO NOTHING
    RETURNING task_instance_id
)
UPDATE task_instances ti
SET state = 'none',
    started_at = NULL,
    ended_at = NULL,
    queued_at = NULL,
    scheduled_at = NULL,
    dispatch_attempts = 0,
    next_dispatch_at = NULL,
    try_number = ti.try_number + 1
WHERE ti.dag_run_id = $1 AND ti.task_id = $2
  AND ti.state IN ('failed', 'upstream_failed', 'up_for_retry')
`

type ResetFailedTaskInstanceParams struct {
	DagRunID pgtype.UUID `json:"dag_run_id"`
	TaskID   string      `json:"task_id"`
}

// Archives the current attempt into task_instance_history then resets the
// live row. See ResetTaskInstanceToNone for the per-attempt rationale.
func (q *Queries) ResetFailedTaskInstance(ctx context.Context, arg ResetFailedTaskInstanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetFailedTaskInstance, arg.DagRunID, arg.TaskID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetTaskInstanceForRetry = `-- name: ResetTaskInstanceForRetry :execrows
WITH archived AS (
    INSERT INTO task_instance_history (
        task_instance_id, try_number, state,
        queued_at, scheduled_at, started_at, ended_at, duration_seconds,
        exit_code, error_message, hostname, pod_name, node_name, note
    )
    SELECT
        src.id, src.try_number, src.state,
        src.queued_at, src.scheduled_at, src.started_at, src.ended_at, src.duration_seconds,
        src.exit_code, src.error_message, src.hostname, src.pod_name, src.node_name, src.note
    FROM task_instances src
    WHERE src.dag_run_id = $1 AND src.task_id = $2 AND src.state = 'up_for_retry'
    ON CONFLICT (task_instance_id, try_number) DO NOTHING
    RETURNING task_instance_id
)
UPDATE task_instances ti
SET state = 'none',
    started_at = NULL,
    ended_at = NULL,
    queued_at = NULL,
    scheduled_at = NULL,
    dispatch_attempts = 0,
    next_dispatch_at = NULL,
    reschedule_at = NULL,
    first_reschedule_at = NULL,
    last_failure_kind = NULL,
    try_number = ti.try_number + 1
WHERE ti.dag_run_id = $1 AND ti.task_id = $2 AND ti.state = 'up_for_retry'
`

type ResetTaskInstanceForRetryParams struct {
	DagRunID pgtype.UUID `json:"dag_run_id"`
	TaskID   string      `json:"task_id"`
}

// The scheduler retry rail's reset: identical to ResetTaskInstanceToNone but
// GUARDED to state='up_for_retry' on both the history snapshot and the update.
// The planner emits up_for_retry → none, but by apply time the TI may have been
// re-dispatched (a stale/concurrent decision); without this guard the reset
// would yank a now-running TI back to none and bump try_number, orphaning its
// live pod. Mirrors the source-state guard on RedispatchRescheduledTaskInstance.
// The admin clear-task path deliberately uses the unguarded primitive above.
func (q *Queries) ResetTaskInstanceForRetry(ctx context.Context, arg ResetTaskInstanceForRetryParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetTaskInstanceForRetry, arg.DagRunID, arg.TaskID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetTaskInstanceInfraReplace = `-- name: ResetTaskInstanceInfraReplace :execrows
WITH archived AS (
    INSERT INTO task_instance_history (
        task_instance_id, try_number, state,
        queued_at, scheduled_at, started_at, ended_at, duration_seconds,
        exit_code, error_message, hostname, pod_name, node_name, note
    )
    SELECT
        src.id, src.try_number, src.state,
        src.queued_at, src.scheduled_at, src.started_at, src.ended_at, src.duration_seconds,
        src.exit_code, src.error_message, src.hostname, src.pod_name, src.node_name, src.note
    FROM task_instances src
    WHERE src.dag_run_id = $1 AND src.task_id = $2
      AND src.state = 'failed' AND src.last_failure_kind = 'infra'
    ON CONFLICT (task_instance_id, try_number) DO NOTHING
    RETURNING task_instance_id
)
UPDATE task_instances ti
SET state = 'none',
    started_at = NULL,
    ended_at = NULL,
    queued_at = NULL,
    scheduled_at = NULL,
    dispatch_attempts = 0,
    next_dispatch_at = NULL,
    reschedule_at = NULL,
    first_reschedule_at = NULL,
    last_failure_kind = NULL,
    infra_attempts = ti.infra_attempts + 1
WHERE ti.dag_run_id = $1 AND ti.task_id = $2
  AND ti.state = 'failed' AND ti.last_failure_kind = 'infra'
`

type ResetTaskInstanceInfraReplaceParams struct {
	DagRunID pgtype.UUID `json:"dag_run_id"`
	TaskID   string      `json:"task_id"`
}

// The scheduler infra-fault rail's reset (ADR 0051 Phase 1): re-place a task that
// a reaper failed as infra (agent/pod/dispatch lost, last_failure_kind='infra')
// back to 'none' WITHOUT consuming the retry budget — try_number is left
// untouched and infra_attempts is bumped instead, mirroring how dispatch_attempts
// counts synchronous-dispatch faults. GUARDED to state='failed' AND
// last_failure_kind='infra' on both the history snapshot and the update: by apply
// time a late terminal report may have moved the TI, and only a genuine infra
// failure may re-place off-budget (an app failure at state='failed' must fall to
// the normal retry rail). last_failure_kind is cleared so the next attempt's
// outcome is classified fresh.
func (q *Queries) ResetTaskInstanceInfraReplace(ctx context.Context, arg ResetTaskInstanceInfraReplaceParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetTaskInstanceInfraReplace, arg.DagRunID, arg.TaskID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetTaskInstanceToNone = `-- name: ResetTaskInstanceToNone :exec
WITH archived AS (
    INSERT INTO task_instance_history (
        task_instance_id, try_number, state,
        queued_at, scheduled_at, started_at, ended_at, duration_seconds,
        exit_code, error_message, hostname, pod_name, node_name, note
    )
    SELECT
        src.id, src.try_number, src.state,
        src.queued_at, src.scheduled_at, src.started_at, src.ended_at, src.duration_seconds,
        src.exit_code, src.error_message, src.hostname, src.pod_name, src.node_name, src.note
    FROM task_instances src
    WHERE src.dag_run_id = $1 AND src.task_id = $2
    ON CONFLICT (task_instance_id, try_number) DO NOTHING
    RETURNING task_instance_id
)
UPDATE task_instances ti
SET state = 'none',
    started_at = NULL,
    ended_at = NULL,
    queued_at = NULL,
    scheduled_at = NULL,
    dispatch_attempts = 0,
    next_dispatch_at = NULL,
    reschedule_at = NULL,
    first_reschedule_at = NULL,
    last_failure_kind = NULL,
    try_number = ti.try_number + 1
WHERE ti.dag_run_id = $1 AND ti.task_id = $2
`

type ResetTaskInstanceToNoneParams struct {
	DagRunID pgtype.UUID `json:"dag_run_id"`
	TaskID   string      `json:"task_id"`
}

// Resets a TI for retry: snapshot the current per-attempt state into
// task_instance_history (so the UI's /tries endpoint can render one tab per
// attempt, Lima bug #241), then state back to `none`, all per-attempt
// timestamps cleared (including queued_at), and try_number bumped. queued_at
// MUST be NULLed so the next TransitionTaskState(queued) stamps a fresh now()
// — without that, the dispatch-lost reaper sees the stale pre-clear timestamp
// and re-marks the TI dispatch_lost on every tick (Lima Bug 1).
// This is the UNCONDITIONAL clear primitive: the admin "clear task" action
// (ClearTaskInstances, onlyFailed=false) resets a TI to none from ANY state, so
// it carries no source-state guard. The scheduler's retry rail uses the guarded
// ResetTaskInstanceForRetry instead — do not add a guard here or clear-task
// silently no-ops on non-up_for_retry tasks.
func (q *Queries) ResetTaskInstanceToNone(ctx context.Context, arg ResetTaskInstanceToNoneParams) error {
	_, err := q.db.Exec(ctx, resetTaskInstanceToNone, arg.DagRunID, arg.TaskID)
	return err
}

const resolveRunRef = `-- name: ResolveRunRef :one
SELECT t.id AS tenant_id, dr.id AS dag_run_id
FROM dag_runs dr
JOIN dags d ON d.id = dr.dag_id
JOIN tenants t ON t.id = d.tenant_id
WHERE t.name = $1 AND d.dag_id = $2 AND dr.run_id = $3
`

type ResolveRunRefParams struct {
	Name  string `json:"name"`
	DagID string `json:"dag_id"`
	RunID string `json:"run_id"`
}

type ResolveRunRefRow struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	DagRunID pgtype.UUID `json:"dag_run_id"`
}

func (q *Queries) ResolveRunRef(ctx context.Context, arg ResolveRunRefParams) (ResolveRunRefRow, error) {
	row := q.db.QueryRow(ctx, resolveRunRef, arg.Name, arg.DagID, arg.RunID)
	var i ResolveRunRefRow
	err := row.Scan(&i.TenantID, &i.DagRunID)
	return i, err
}

const setTaskInstanceNote = `-- name: SetTaskInstanceNote :exec
UPDATE task_instances
SET note = $3
WHERE dag_run_id = $1 AND task_id = $2
`

type SetTaskInstanceNoteParams struct {
	DagRunID pgtype.UUID `json:"dag_run_id"`
	TaskID   string      `json:"task_id"`
	Note     *string     `json:"note"`
}

func (q *Queries) SetTaskInstanceNote(ctx context.Context, arg SetTaskInstanceNoteParams) error {
	_, err := q.db.Exec(ctx, setTaskInstanceNote, arg.DagRunID, arg.TaskID, arg.Note)
	return err
}

const stampDagRunState = `-- name: StampDagRunState :exec
UPDATE dag_runs
SET state = $1::dag_run_state,
    started_at = CASE WHEN $1::dag_run_state = 'running' AND started_at IS NULL THEN now() ELSE started_at END,
    ended_at = CASE WHEN $1::dag_run_state IN ('success', 'failed') THEN now() ELSE ended_at END
WHERE id = $2
`

type StampDagRunStateParams struct {
	State DagRunState `json:"state"`
	ID    pgtype.UUID `json:"id"`
}

// Transitions a run's state and stamps the run's own timestamps so the UI can
// show its duration: started_at on first entry into 'running', ended_at on a
// terminal state. Other timestamps are preserved (the scheduler may re-run).
func (q *Queries) StampDagRunState(ctx context.Context, arg StampDagRunStateParams) error {
	_, err := q.db.Exec(ctx, stampDagRunState, arg.State, arg.ID)
	return err
}

const taskInstanceFirstRescheduleAt = `-- name: TaskInstanceFirstRescheduleAt :one
SELECT first_reschedule_at FROM task_instances
WHERE dag_run_id = $1 AND task_id = $2
`

type TaskInstanceFirstRescheduleAtParams struct {
	DagRunID pgtype.UUID `json:"dag_run_id"`
	TaskID   string      `json:"task_id"`
}

// The time a reschedule-mode sensor first entered reschedule (NULL until it does).
// Delivered to each re-dispatched pod so get_first_reschedule_date returns the real
// value and the sensor honors its cumulative timeout across pokes (#380).
func (q *Queries) TaskInstanceFirstRescheduleAt(ctx context.Context, arg TaskInstanceFirstRescheduleAtParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, taskInstanceFirstRescheduleAt, arg.DagRunID, arg.TaskID)
	var first_reschedule_at pgtype.Timestamptz
	err := row.Scan(&first_reschedule_at)
	return first_reschedule_at, err
}

const taskInstancesForDagRuns = `-- name: TaskInstancesForDagRuns :many
SELECT dr.run_id, ti.task_id, ti.try_number, ti.state,
       ti.started_at, ti.ended_at
FROM task_instances ti
JOIN dag_runs dr ON dr.id = ti.dag_run_id
JOIN dags d ON d.id = dr.dag_id
WHERE d.tenant_id = $1 AND d.dag_id = $2 AND dr.run_id = ANY($3::text[])
ORDER BY dr.run_id, ti.task_id, ti.try_number
`

type TaskInstancesForDagRunsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	DagID    string      `json:"dag_id"`
	Column3  []string    `json:"column_3"`
}

type TaskInstancesForDagRunsRow struct {
	RunID     string             `json:"run_id"`
	TaskID    string             `json:"task_id"`
	TryNumber int32              `json:"try_number"`
	State     TaskState          `json:"state"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	EndedAt   pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) TaskInstancesForDagRuns(ctx context.Context, arg TaskInstancesForDagRunsParams) ([]TaskInstancesForDagRunsRow, error) {
	rows, err := q.db.Query(ctx, taskInstancesForDagRuns, arg.TenantID, arg.DagID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskInstancesForDagRunsRow{}
	for rows.Next() {
		var i TaskInstancesForDagRunsRow
		if err := rows.Scan(
			&i.RunID,
			&i.TaskID,
			&i.TryNumber,
			&i.State,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDagRunState = `-- name: UpdateDagRunState :one
UPDATE dag_runs
SET state = $2, started_at = $3, ended_at = $4
WHERE id = $1
RETURNING id, tenant_id, dag_id, dag_version_id, run_id, logical_date, data_interval_start, data_interval_end, state, trigger, conf, triggered_by, queued_at, started_at, ended_at, note, alerted_at, alert_attempts, next_alert_attempt_at
`

type UpdateDagRunStateParams struct {
	ID        pgtype.UUID        `json:"id"`
	State     DagRunState        `json:"state"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	EndedAt   pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) UpdateDagRunState(ctx context.Context, arg UpdateDagRunStateParams) (DagRun, error) {
	row := q.db.QueryRow(ctx, updateDagRunState,
		arg.ID,
		arg.State,
		arg.StartedAt,
		arg.EndedAt,
	)
	var i DagRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DagID,
		&i.DagVersionID,
		&i.RunID,
		&i.LogicalDate,
		&i.DataIntervalStart,
		&i.DataIntervalEnd,
		&i.State,
		&i.Trigger,
		&i.Conf,
		&i.TriggeredBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Note,
		&i.AlertedAt,
		&i.AlertAttempts,
		&i.NextAlertAttemptAt,
	)
	return i, err
}

const updateTaskInstanceState = `-- name: UpdateTaskInstanceState :one
UPDATE task_instances
SET state = $2, started_at = $3, ended_at = $4
WHERE id = $1
RETURNING id, tenant_id, dag_run_id, task_id, map_index, try_number, max_tries, state, pool, operator, queued_at, started_at, ended_at, duration_seconds, pod_name, node_name, exit_code, error_message, log_url, hostname, note, scheduled_at, last_heartbeat_at, reschedule_at, first_reschedule_at, dispatch_attempts, next_dispatch_at, last_failure_kind, infra_attempts
`

type UpdateTaskInstanceStateParams struct {
	ID        pgtype.UUID        `json:"id"`
	State     TaskState          `json:"state"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	EndedAt   pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) UpdateTaskInstanceState(ctx context.Context, arg UpdateTaskInstanceStateParams) (TaskInstance, error) {
	row := q.db.QueryRow(ctx, updateTaskInstanceState,
		arg.ID,
		arg.State,
		arg.StartedAt,
		arg.EndedAt,
	)
	var i TaskInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DagRunID,
		&i.TaskID,
		&i.MapIndex,
		&i.TryNumber,
		&i.MaxTries,
		&i.State,
		&i.Pool,
		&i.Operator,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.PodName,
		&i.NodeName,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.LogUrl,
		&i.Hostname,
		&i.Note,
		&i.ScheduledAt,
		&i.LastHeartbeatAt,
		&i.RescheduleAt,
		&i.FirstRescheduleAt,
		&i.DispatchAttempts,
		&i.NextDispatchAt,
		&i.LastFailureKind,
		&i.InfraAttempts,
	)
	return i, err
}

const updateTaskInstanceStateByRunTask = `-- name: UpdateTaskInstanceStateByRunTask :exec
UPDATE task_instances
SET state = $1::task_state,
    scheduled_at = CASE WHEN $1::task_state = 'scheduled' AND scheduled_at IS NULL THEN now() ELSE scheduled_at END,
    queued_at = CASE WHEN $1::task_state = 'queued' AND queued_at IS NULL THEN now() ELSE queued_at END,
    started_at = CASE WHEN $1::task_state = 'running' AND started_at IS NULL THEN now() ELSE started_at END
WHERE dag_run_id = $2 AND task_id = $3
`

type UpdateTaskInstanceStateByRunTaskParams struct {
	State    TaskState   `json:"state"`
	DagRunID pgtype.UUID `json:"dag_run_id"`
	TaskID   string      `json:"task_id"`
}

// Stamps the per-state entry timestamps the UI shows (scheduled_when /
// queued_when / start_date). Each is set on first entry only ("IS NULL"), so a
// re-emitted transition does not move the recorded time. $3 is cast to
// task_state (see ReportTaskResult for why the cast is required).
func (q *Queries) UpdateTaskInstanceStateByRunTask(ctx context.Context, arg UpdateTaskInstanceStateByRunTaskParams) error {
	_, err := q.db.Exec(ctx, updateTaskInstanceStateByRunTask, arg.State, arg.DagRunID, arg.TaskID)
	return err
}
