// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: staging_volumes.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listActiveStagingVolumes = `-- name: ListActiveStagingVolumes :many
SELECT s.pvc_name, s.created_at, r.state AS run_state, r.ended_at AS run_ended_at
FROM staging_volumes s
LEFT JOIN dag_runs r ON r.id::text = s.run_id
WHERE s.state = 'active'
`

type ListActiveStagingVolumesRow struct {
	PvcName    string             `json:"pvc_name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	RunState   *DagRunState       `json:"run_state"`
	RunEndedAt pgtype.Timestamptz `json:"run_ended_at"`
}

// run_id is the dag_run's UUID (StagingClaimName uses it), so join on dag_runs.id,
// which is globally unique. run_state is NULL only when the run row is truly gone.
func (q *Queries) ListActiveStagingVolumes(ctx context.Context) ([]ListActiveStagingVolumesRow, error) {
	rows, err := q.db.Query(ctx, listActiveStagingVolumes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveStagingVolumesRow{}
	for rows.Next() {
		var i ListActiveStagingVolumesRow
		if err := rows.Scan(
			&i.PvcName,
			&i.CreatedAt,
			&i.RunState,
			&i.RunEndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStagingDeleted = `-- name: MarkStagingDeleted :exec
UPDATE staging_volumes
SET state = 'deleted', deleted_at = now(), delete_reason = $1
WHERE pvc_name = $2 AND state <> 'deleted'
`

type MarkStagingDeletedParams struct {
	Reason  *string `json:"reason"`
	PvcName string  `json:"pvc_name"`
}

func (q *Queries) MarkStagingDeleted(ctx context.Context, arg MarkStagingDeletedParams) error {
	_, err := q.db.Exec(ctx, markStagingDeleted, arg.Reason, arg.PvcName)
	return err
}

const recordStagingVolume = `-- name: RecordStagingVolume :exec
INSERT INTO staging_volumes (tenant_id, dag_id, run_id, pvc_name, size, state)
VALUES ($1, $2, $3, $4, $5, 'active')
ON CONFLICT (pvc_name) DO NOTHING
`

type RecordStagingVolumeParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	DagID    string      `json:"dag_id"`
	RunID    string      `json:"run_id"`
	PvcName  string      `json:"pvc_name"`
	Size     string      `json:"size"`
}

func (q *Queries) RecordStagingVolume(ctx context.Context, arg RecordStagingVolumeParams) error {
	_, err := q.db.Exec(ctx, recordStagingVolume,
		arg.TenantID,
		arg.DagID,
		arg.RunID,
		arg.PvcName,
		arg.Size,
	)
	return err
}
