// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDefaultTenant = `-- name: GetDefaultTenant :one
SELECT id, name FROM tenants WHERE name = 'default'
`

type GetDefaultTenantRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) GetDefaultTenant(ctx context.Context) (GetDefaultTenantRow, error) {
	row := q.db.QueryRow(ctx, getDefaultTenant)
	var i GetDefaultTenantRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTenantByName = `-- name: GetTenantByName :one
SELECT id, name FROM tenants WHERE name = $1
`

type GetTenantByNameRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) GetTenantByName(ctx context.Context, name string) (GetTenantByNameRow, error) {
	row := q.db.QueryRow(ctx, getTenantByName, name)
	var i GetTenantByNameRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT u.id, u.tenant_id, u.email, u.password_hash, u.is_active
FROM users u
JOIN tenants t ON t.id = u.tenant_id
WHERE t.name = $1 AND u.email = $2
`

type GetUserByEmailParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type GetUserByEmailRow struct {
	ID           pgtype.UUID `json:"id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	Email        string      `json:"email"`
	PasswordHash *string     `json:"password_hash"`
	IsActive     bool        `json:"is_active"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Name, arg.Email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id, t.name AS tenant, u.email, u.is_active
FROM users u
JOIN tenants t ON t.id = u.tenant_id
WHERE u.id = $1
`

type GetUserByIDRow struct {
	ID       pgtype.UUID `json:"id"`
	Tenant   string      `json:"tenant"`
	Email    string      `json:"email"`
	IsActive bool        `json:"is_active"`
}

// The by-id lookup backing the per-request authz reload. Returns the tenant
// name (not the uuid) so the reconstructed principal matches the login path's
// User.TenantID, plus the active flag the authenticator gates on.
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Tenant,
		&i.Email,
		&i.IsActive,
	)
	return i, err
}

const getUserByOIDCSubject = `-- name: GetUserByOIDCSubject :one
SELECT u.id, t.name AS tenant, u.email, u.is_active
FROM users u
JOIN tenants t ON t.id = u.tenant_id
WHERE u.oidc_provider = $1 AND u.oidc_subject = $2
`

type GetUserByOIDCSubjectParams struct {
	OidcProvider *string `json:"oidc_provider"`
	OidcSubject  *string `json:"oidc_subject"`
}

type GetUserByOIDCSubjectRow struct {
	ID       pgtype.UUID `json:"id"`
	Tenant   string      `json:"tenant"`
	Email    string      `json:"email"`
	IsActive bool        `json:"is_active"`
}

// Resolve an OIDC identity to a Leoflow user by its immutable (provider,
// subject) pair (the trusted link key). Returns the tenant name (not the uuid)
// so the reconstructed principal matches the login path's User.TenantID, plus
// the active flag the login gates on. Never selects password_hash.
func (q *Queries) GetUserByOIDCSubject(ctx context.Context, arg GetUserByOIDCSubjectParams) (GetUserByOIDCSubjectRow, error) {
	row := q.db.QueryRow(ctx, getUserByOIDCSubject, arg.OidcProvider, arg.OidcSubject)
	var i GetUserByOIDCSubjectRow
	err := row.Scan(
		&i.ID,
		&i.Tenant,
		&i.Email,
		&i.IsActive,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT DISTINCT p.action, p.resource
FROM user_roles ur
JOIN role_permissions rp ON rp.role_id = ur.role_id
JOIN permissions p ON p.id = rp.permission_id
WHERE ur.user_id = $1
`

type GetUserPermissionsRow struct {
	Action   string `json:"action"`
	Resource string `json:"resource"`
}

func (q *Queries) GetUserPermissions(ctx context.Context, userID pgtype.UUID) ([]GetUserPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserPermissionsRow{}
	for rows.Next() {
		var i GetUserPermissionsRow
		if err := rows.Scan(&i.Action, &i.Resource); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.name
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
`

func (q *Queries) GetUserRoles(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOIDCUser = `-- name: InsertOIDCUser :one
INSERT INTO users (tenant_id, email, oidc_provider, oidc_subject)
VALUES ($1, $2, $3, $4)
RETURNING id, email, is_active, created_at
`

type InsertOIDCUserParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	Email        string      `json:"email"`
	OidcProvider *string     `json:"oidc_provider"`
	OidcSubject  *string     `json:"oidc_subject"`
}

type InsertOIDCUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Just-in-time provisioning insert for a first OIDC login: an OIDC-only user
// (NULL password) linked by (oidc_provider, oidc_subject). The unique
// (oidc_provider, oidc_subject) constraint makes a concurrent double-provision
// surface as a conflict rather than a duplicate identity.
func (q *Queries) InsertOIDCUser(ctx context.Context, arg InsertOIDCUserParams) (InsertOIDCUserRow, error) {
	row := q.db.QueryRow(ctx, insertOIDCUser,
		arg.TenantID,
		arg.Email,
		arg.OidcProvider,
		arg.OidcSubject,
	)
	var i InsertOIDCUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (tenant_id, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, is_active, created_at
`

type InsertUserParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	Email        string      `json:"email"`
	PasswordHash *string     `json:"password_hash"`
}

type InsertUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Mirrors the bootstrap CreateUser insert (tenant_id, email, password_hash) but
// returns the columns the admin create-user API echoes back to the caller.
func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.TenantID, arg.Email, arg.PasswordHash)
	var i InsertUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.email, u.is_active, u.created_at,
    COALESCE(array_remove(array_agg(r.name), NULL), '{}')::text[] AS roles
FROM users u
LEFT JOIN user_roles ur ON ur.user_id = u.id
LEFT JOIN roles r ON r.id = ur.role_id
WHERE u.tenant_id = $1
GROUP BY u.id, u.email, u.is_active, u.created_at
ORDER BY u.created_at DESC, u.id DESC
LIMIT $2 OFFSET $3
`

type ListUsersParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type ListUsersRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Roles     []string           `json:"roles"`
}

// One row per user in the tenant, newest first, with every granted role name
// aggregated into a text array (empty when the user holds none). Paged by the
// caller. Never selects password_hash — the list must not expose secrets.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.IsActive,
			&i.CreatedAt,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users
SET password_hash = $3
WHERE email = $2
  AND tenant_id = (SELECT id FROM tenants WHERE name = $1)
`

type UpdateUserPasswordParams struct {
	Name         string  `json:"name"`
	Email        string  `json:"email"`
	PasswordHash *string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.Name, arg.Email, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
