// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: variables.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVariables = `-- name: CountVariables :one
SELECT count(*) FROM variables WHERE tenant_id = $1
`

func (q *Queries) CountVariables(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVariables, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteVariable = `-- name: DeleteVariable :execrows
DELETE FROM variables WHERE tenant_id = $1 AND key = $2
`

type DeleteVariableParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Key      string      `json:"key"`
}

func (q *Queries) DeleteVariable(ctx context.Context, arg DeleteVariableParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVariable, arg.TenantID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVariable = `-- name: GetVariable :one
SELECT key, value, description
FROM variables
WHERE tenant_id = $1 AND key = $2
`

type GetVariableParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Key      string      `json:"key"`
}

type GetVariableRow struct {
	Key         string  `json:"key"`
	Value       string  `json:"value"`
	Description *string `json:"description"`
}

func (q *Queries) GetVariable(ctx context.Context, arg GetVariableParams) (GetVariableRow, error) {
	row := q.db.QueryRow(ctx, getVariable, arg.TenantID, arg.Key)
	var i GetVariableRow
	err := row.Scan(&i.Key, &i.Value, &i.Description)
	return i, err
}

const listVariables = `-- name: ListVariables :many
SELECT key, value, description
FROM variables
WHERE tenant_id = $1
ORDER BY key
LIMIT $2 OFFSET $3
`

type ListVariablesParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type ListVariablesRow struct {
	Key         string  `json:"key"`
	Value       string  `json:"value"`
	Description *string `json:"description"`
}

func (q *Queries) ListVariables(ctx context.Context, arg ListVariablesParams) ([]ListVariablesRow, error) {
	rows, err := q.db.Query(ctx, listVariables, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVariablesRow{}
	for rows.Next() {
		var i ListVariablesRow
		if err := rows.Scan(&i.Key, &i.Value, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVariable = `-- name: UpsertVariable :exec
INSERT INTO variables (tenant_id, key, value, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, key) DO UPDATE SET
    value = EXCLUDED.value,
    description = EXCLUDED.description,
    updated_at = now()
`

type UpsertVariableParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	Key         string      `json:"key"`
	Value       string      `json:"value"`
	Description *string     `json:"description"`
}

func (q *Queries) UpsertVariable(ctx context.Context, arg UpsertVariableParams) error {
	_, err := q.db.Exec(ctx, upsertVariable,
		arg.TenantID,
		arg.Key,
		arg.Value,
		arg.Description,
	)
	return err
}
