// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: xcom.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredXComIndex = `-- name: DeleteExpiredXComIndex :exec
DELETE FROM xcom_index WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredXComIndex(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredXComIndex)
	return err
}

const getXComEntry = `-- name: GetXComEntry :one
SELECT redis_key, content_type, size_bytes, created_at
FROM xcom_index
WHERE dag_run_id = $1 AND task_id = $2 AND key = $3 AND expires_at > now()
`

type GetXComEntryParams struct {
	DagRunID pgtype.UUID `json:"dag_run_id"`
	TaskID   string      `json:"task_id"`
	Key      string      `json:"key"`
}

type GetXComEntryRow struct {
	RedisKey    string             `json:"redis_key"`
	ContentType string             `json:"content_type"`
	SizeBytes   int32              `json:"size_bytes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetXComEntry(ctx context.Context, arg GetXComEntryParams) (GetXComEntryRow, error) {
	row := q.db.QueryRow(ctx, getXComEntry, arg.DagRunID, arg.TaskID, arg.Key)
	var i GetXComEntryRow
	err := row.Scan(
		&i.RedisKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const recordXCom = `-- name: RecordXCom :exec
INSERT INTO xcom_index (tenant_id, dag_run_id, task_id, key, redis_key, size_bytes, content_type, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (dag_run_id, task_id, key) DO UPDATE SET
    redis_key = EXCLUDED.redis_key,
    size_bytes = EXCLUDED.size_bytes,
    content_type = EXCLUDED.content_type,
    created_at = now(),
    expires_at = EXCLUDED.expires_at
`

type RecordXComParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	DagRunID    pgtype.UUID        `json:"dag_run_id"`
	TaskID      string             `json:"task_id"`
	Key         string             `json:"key"`
	RedisKey    string             `json:"redis_key"`
	SizeBytes   int32              `json:"size_bytes"`
	ContentType string             `json:"content_type"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) RecordXCom(ctx context.Context, arg RecordXComParams) error {
	_, err := q.db.Exec(ctx, recordXCom,
		arg.TenantID,
		arg.DagRunID,
		arg.TaskID,
		arg.Key,
		arg.RedisKey,
		arg.SizeBytes,
		arg.ContentType,
		arg.ExpiresAt,
	)
	return err
}
